
<?php if (count($this->hashtags)): ?>
    <!-- hashtags_table -->
    <?php foreach ($this->hashtags as $hashtag): ?>
        <div class="my-4">
            <a class="h3 color-gray-800 text-decoration-none" href="<?= $hashtag->getURL($this->lang) ?>">
                #<?= $hashtag->title ?>
            </a>
            <div class="small mt-1 color-gray-500">

                <a rel="nofollow" href="#">
                    Подписаться
                </a>
                <span class="mx-1 color-gray-900 font-weight-bold">&middot;</span>
                1 вопрос
                <span class="mx-1 color-gray-900 font-weight-bold">&middot;</span>
                2 подписчика

            </div>
        </div>
    <?php endforeach; ?>
    <!-- / hashtags_table -->
<?php endif; ?>
