
<?php if (count($this->hashtags)): ?>
    <!-- hashtags_table -->
    <table class="table">
        <thead>
            <tr>
                <th class="w-6" scope="col"></th>
                <th scope="col">Тема</th>
                <th class="d-none d-sm-table-cell" scope="col">
                    <i class="far fa-question-circle" style="color: #e51e24;"></i>
                </th>
                <th class="d-none d-sm-table-cell" scope="col">
                    <i class="fas fa-user-friends" style="color: #444444;"></i>
                </th>
                <th class="d-none d-sm-table-cell" scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->hashtags as $hashtag): ?>
                <tr>
                    <td class="w-4">
                        <a class="wh-2" href="<?= $hashtag->getURL($this->lang) ?>">
                            <img class="wh-2 rounded" src="https://answeropedia.org/uploads/avatar/0_100.jpg">
                        </a>
                    </td>
                    <td>
                        <div class="font-weight-bold">
                            <a class="color-gray-900 text-decoration-none" href="<?= $hashtag->getURL($this->lang) ?>" title="#<?= $hashtag->title ?>">
                                #<?= $hashtag->title ?>
                            </a>
                        </div>
                    </td>
                    <td>
                        <?= (int) (1 + strlen($hashtag->title) / 2) ?>
                    </td>
                    <td>
                        <?= strlen($hashtag->title) ?>
                    </td>
                    <td class="d-none d-sm-table-cell">
                        <button class="btn btn-sm btn-outline-success" role="button">
                            Подписаться
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <!-- / hashtags_table -->
<?php endif; ?>
