<div class="mb-4 mt-1">
    <p class="text-muted mb-0"><?= $this->translator->get('settings', 'title') ?></p>
    <h1 class="font-size-15 line-height-13 text-dark font-weight-bold">
        <a class="text-dark text-decoration-none" href="<?= $this->authUser->get_URL($this->lang) ?>">
            <?= $this->authUser->name ? $this->authUser->name : $this->authUser->username; ?>
        </a>
    </h1>
</div>