<div class="mb-5">
    <p class="lead text-muted mb-1"><?= $this->translator->get('settings', 'title') ?></p>
    <h1 class="mt-0">
        <a class="text-dark text-decoration-none" href="<?= $this->authUser->get_URL($this->lang) ?>">
            <?= $this->authUser->name ? $this->authUser->name : $this->authUser->username; ?>
        </a>
    </h1>
</div>

<div class="border-top my-5 pt-4">
    <h4><?= $this->translator->get('settings', 'avatar__title') ?></h4>
    <img class="rounded wh-6 mt-3 mb-4" id="settings_pg__user_avatar" src="<?= $this->authUser->get_avatar_URL_medium() ?>" />
    <form action="/api/v1/avatar.json" id="form__upload_avatar" method="POST" enctype="multipart/form-data">
        <div class="form-group">
            <label for="form__update_name__name">
                <?= $this->translator->get('settings', 'avatar__note') ?>
            </label>
            <input type="file" name="new_avatar_file" class="form-control-file w-100">
        </div>
        <div class="form-group">
            <button type="submit" id="form__upload_avatar__submit_btn" class="btn btn-primary submit_button">
                <?= $this->translator->get('settings', 'avatar__btn_upload') ?>
            </button>
        </div>
    </form>
</div>

<div class="border-top my-5 pt-4">
    <h4><?= $this->translator->get('settings', 'real_name_title') ?></h4>
    <form id="form__update_name" data-user-id="<?= $this->authUser->id ?>">
        <div class="form-group">
            <label for="form__update_name__name">
                <?= $this->translator->get('settings', 'real_name_note') ?>.
            </label>
            <input id="form__update_name__name" type="text" class="form-control" value="<?= @$this->authUser->name ?>">
        </div>
        <div class="form-group">
            <button type="submit" id="form__update_name__submit" class="btn btn-primary">
                <?= $this->translator->get('settings', 'save') ?>
            </button>
        </div>
    </form>
</div>

<div class="border-top my-5 pt-4">
    <h4><?= $this->translator->get('settings', 'signature_title') ?></h4>
    <form id="form__update_signature" data-user-id="<?= $this->authUser->id ?>">
        <div class="form-group">
            <label for="form__update_signature__signature">
                <?= $this->translator->get('settings', 'signature_note') ?>
            </label>
            <input id="form__update_signature__signature" type="text" class="form-control" value="<?= @$this->authUser->signature ?>" placeholder="<?= $this->translator->get('settings', 'signature_placeholder') ?>">
        </div>
        <div class="form-group mt-3">
            <button type="submit" id="form__update_signature__submit" class="btn btn-primary">
                <?= $this->translator->get('settings', 'save') ?>
            </button>
        </div>
    </form>
</div>

<div class="border-top my-5 pt-4">
    <h4><?= $this->translator->get('settings', 'site_title') ?></h4>
    <form id="frm__update_site" data-user-id="<?= $this->authUser->id ?>">
        <div class="form-group">
            <label for="frm__update_site__site">
                <?= $this->translator->get('settings', 'site_note') ?>
            </label>
            <input id="frm__update_site__site" type="text" class="form-control" value="<?= @$this->authUser->site ?>">
        </div>
        <div class="form-group">
            <button type="submit" id="frm__update_site__submit" class="btn btn-primary">
                <?= $this->translator->get('settings', 'save') ?>
            </button>
        </div>
    </form>
</div>