<!-- real name -->
<div class="border rounded p-3 pt-2 bg-white my-4">

    <div class="semi-small font-weight-bold text-uppercase text-black mb-3">
        <?= $this->translator->get('settings', 'real_name_title') ?>
    </div>

    <form id="form__update_name" data-user-id="<?= $this->authUser->id ?>">
        <div class="form-group">
            <label class="semi-small text-muted" for="form__update_name__name">
                <?= $this->translator->get('settings', 'real_name_note') ?>.
            </label>
            <input id="form__update_name__name" type="text" class="form-control" value="<?= @$this->authUser->name ?>">
        </div>
        <div class="form-group mb-0">
            <button type="submit" id="form__update_name__submit" class="btn btn-sm btn-primary">
                <?= $this->translator->get('settings', 'save') ?>
            </button>
        </div>
    </form>
</div>
<!-- / real name -->