<!DOCTYPE html>
<html lang="<?= $this->lang ?>">

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>

    <?php if (isset($this->alternateURLPrefix)) : ?>
        <!-- alternate URL`s -->
        <link rel="alternate" hreflang="x-default" href="<?= $this->canonicalURL ?>" />
        <link rel="alternate" hreflang="ru" href="<?= $this->alternateURLPrefix ?>l=ru" />
        <link rel="alternate" hreflang="en" href="<?= $this->alternateURLPrefix ?>l=en" />
    <?php endif; ?>

</head>

<body>
    <?php require __DIR__ . '/navbar.phtml'; ?>
    <?php require __DIR__ . '/jumbotron.phtml'; ?>

    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-10 mx-auto">
                <?php require_once __DIR__ . '/langlist.phtml'; ?>
            </div>
        </div>
    </div>

    <?php require_once __DIR__ . '/modal_support.phtml'; ?>

    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>
</body>

</html>