
<!-- header_topics -->
<div>
	<?php if (count($this->question->getTopics())): ?>

		<?php foreach ($this->question->getFirstTwoTopics() as $topic): ?>
			<a class="font-weight-bold text-decoration-none mb-2 mr-2" href="<?= Topic_URL_Helper::getURLFromTitle($this->lang, $topic) ?>">
				#<?= $topic ?>
			</a>
		<?php endforeach; ?>

		<?php if (count($this->question->getTopics()) > count($this->question->getFirstTwoTopics())): ?>
			<a class="text-secondary text-decoration-none mb-2 mr-2" data-scroll href="#question_topics_list">
				+<?= $this->question->getHumanizedMoreHashtags() ?>
			</a>
		<?php endif; ?>

	<?php endif; ?>
</div>
<!-- / header_topics -->
