
<!-- header_topics -->
<div>
    <?php if (count($this->question->getTopics())): ?>

        <?php foreach ($this->question->getFirstTwoTopics() as $topic): ?>
            <a class="badge badge-sm badge-secondary mb-2 mr-2" href="<?= Topic_URL_Helper::getURLFromTitle($this->lang, $topic) ?>">
                <?= $topic ?>
            </a>
        <?php endforeach; ?>

        <?php if (count($this->question->getTopics()) > count($this->question->getFirstTwoTopics())): ?>
            <a class="badge badge-sm badge-secondary mb-2 mr-2" data-scroll href="#question_topics_list">
                +<?= count($this->question->getTopics()) - count($this->question->getFirstTwoTopics()) ?>
            </a>
        <?php endif; ?>

        <?php if ($this->authUser): ?>
            <a class="badge badge-sm badge-primary mb-2 mr-2" href="<?= $this->question->getUpdateTopicsURL($this->lang) ?>">
                <i class="far fa-edit mr-1"></i>    
                <?= _('Update topics') ?>
            </a>
        <?php endif; ?>

    <?php else: ?>

        <?php if ($this->authUser): ?>
            <!-- / header_topics -->
            <a class="badge badge-sm badge-primary mb-2 mr-2" href="<?= $this->question->getUpdateTopicsURL($this->lang) ?>">
                <i class="fas fa-cog mr-1"></i>
                <?= _('Set question topics') ?>
            </a>
            <!-- / header_topics -->
        <?php else: ?>
            <!-- / fake header_topics -->
            <a class="badge badge-sm badge-primary mb-2 mr-2" href="#">
                <i class="fas fa-cog mr-1"></i>
                <?= _('Set question topics') ?>
            </a>
            <!-- / fake header_topics -->
        <?php endif; ?>

    <?php endif; ?>
</div>
<!-- / header_topics -->
