
<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js" async="async" charset="utf-8"></script>
<script src="//yastatic.net/share2/share.js" async="async" charset="utf-8"></script>
<div class="ya-share2" style="min-height: 24px;" data-services="twitter,vkontakte,facebook,gplus,pinterest,delicious,digg,reddit,pocket,tumblr,collections,telegram" data-title="<?= $this->shareLink['title'] ?>" data-description="<?= $this->shareLink['description'] ?>" data-url="<?= $this->shareLink['url'] ?>" data-image="<?= $this->shareLink['image'] ?>" data-limit="3"></div>
