
<div class="my-4">

    <!-- edit answer -->
    <?php if ($this->authUser): ?>
        <a href="<?= $this->question->getEditURL($this->lang) ?>" role="button" class="btn btn-primary my-2 mr-2">
            <i class="fas fa-edit"></i>
            <?= _('Edit answer') ?>
        </a>
    <?php else: ?>
        <button type="button" class="btn btn-primary my-2 mr-2" data-toggle="modal" data-target="#modal_lure__edit_answer">
            <?= _('Edit answer') ?>
        </button>
        <?php require_once TEMPLATE_PATH.'/question/modal/edit_answer_lure.phtml' ?>
    <?php endif; ?>
    <!-- / edit answer -->

    <?php if ($this->authUser): ?>
        <button
            class="btn follow_question_button my-2 mr-2 <?= $this->followed ? 'followed btn-success' : 'btn-outline-secondary'; ?>"
            data-question-id="<?= $this->question->getID() ?>"
            data-follow-title="<?= _('Follow') ?>"
            data-followed-title="<?= _('Followed') ?>"
            data-unfollow-title="<?= _('Unfollow') ?>"
            type="button">
            <span><?= $this->followed ? _('Followed') : _('Follow'); ?></span>
        </button>
    <?php else: ?>
        <button type="button" class="btn btn-outline-secondary my-2 mr-2" data-toggle="modal" data-target="#modal__follow_question_lure">
            <span><?= _('Follow'); ?></span>
        </button>
        <?php require_once TEMPLATE_PATH.'/question/modal/follow_question_lure.phtml' ?>
    <?php endif; ?>

    <?php if (mb_strlen($this->answer->getText()) > 0): ?>
        <a href="<?= $this->question->getHistoryURL($this->lang) ?>" class="btn btn-outline-secondary my-2 mr-2">
            <?= _('History') ?>
        </a>
    <?php endif; ?>

    <div class="dropdown d-inline-block float-lg-right">
        <button class="btn btn-outline-secondary dropdown-toggle my-2 mr-2" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <?= _('More') ?>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <?php if ($this->authUser): ?>

                <!-- Show "Upload image" modal -->
                <a class="dropdown-item" rel="nofollow" href="#" data-toggle="modal" data-target="#modal_upload_image">
                    <i class="fas fa-camera mr-1"></i>
                    <?= _('Upload image') ?>
                </a>

                <!-- Button trigger modal "Question rename" -->
                <a class="dropdown-item" rel="nofollow" href="#" data-toggle="modal" data-target="#modal_rename">
                    <i class="fas fa-edit mr-1"></i>
                    <?= _('Rename question') ?>
                </a>
            <?php endif; ?>
            <a class="dropdown-item" rel="nofollow" href="#">
                <i class="fas fa-edit mr-1"></i>
                <?= _('Report') ?>
            </a>
        </div>
    </div>
</div>
