
<?php if (count($this->contributors_tail)): ?>
    <div class="my-5">
        <div class="border-bottom pb-3" id="contributors_full_list">
            <span class="color-gray-400 float-right">
                <?= (new Contributors_Humanizer($this->l))->humanize(count($this->contributors)) ?>
            </span>
            <span class="title">Авторы ответа</span> <!-- Answer contributor -->
        </div>

        <?php foreach ($this->contributors_tail as $contributor): ?>
            <div class="flex-container my-4">
                <div class="width-6">
                    <a class="size-6" href="<?= $contributor->getURL($this->lang) ?>">
                        <img class="size-6 rounded-circle" src="<?= $contributor->getAvatarMediumURL() ?>">
                    </a>
                </div>
                <div class="flex-grow-4 ml-3">
                    <div class="font-weight-700">
                        <a class="color-gray-900 no_underline" href="<?= $contributor->getURL($this->lang) ?>">
                            <?= $contributor->getName() ?>
                        </a>
                    </div>
                    <div class="small color-gray-600">
                        <?= $contributor->getSignature() ? $contributor->getSignature() : '+'.$contributor->getUsername() ?>

                        <?php if ($contributor->getSite()): ?>
                            <span class="color-gray-800 mx-1 font-weight-800">&middot;</span>
                            <a href="<?= $contributor->getSite() ?>">
                                <?= parse_url($contributor->getSite(), PHP_URL_HOST) ?>
                            </a>
                        <?php endif; ?>

                        <?php if ($contributor->getID() == $this->lastContributorID): ?>
                            <span class="color-gray-800 mx-1 font-weight-800">&middot;</span>
                            <span class="badge badge-success badge-sm">
                                Последняя правка
                            </span>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="width-11 d-none d-sm-block text-nowrap">
                    <img class="size-18px mt-minus-4px" src="https://png.icons8.com/ios-glyphs/18/78909C/pull-request.png">
                    <span class="color-gray-700">
                        <?= Contribution_Humanizer::humanizeCount($contributor->getContribution()) ?>
                    </span>
                </div>
                <div class="width-2 d-none d-sm-block">
                    <?php $tail_max_contribution = $this->contributors_tail[0]->getContribution(); ?>
                    <?php $percentage = $contributor->getContribution() * (1 / $tail_max_contribution); ?>
                    <?php $contribution_color = ColorMixer_Helper::colorBetween('1E88E5', '8BC34A', $percentage); ?>
                    <span class="status ml-1" style="background-color: #<?= $contribution_color ?>;"></span>
                </div>
            </div>
        <?php endforeach; ?>

    </div>

<?php endif; ?>
