
<!-- info_about_question -->
<div class="row">
    <div class="col-12">
        <div class="color-gray-500 small py-3 my-3 border-top border-bottom">

            <?php if (count($this->contributors)): ?>
                <a href="#contributors_full_list" class="color-gray-500">
                    <?= count($this->contributors).' '.mb_strtolower(ngettext("Contributor", "Contributors", count($this->contributors))) ?>
                </a>
            <?php else: ?>
                <a href="<?= $this->question->getEditURL($this->lang) ?>" class="color-gray-500 no-underline-hover">
                    <?= _('Edit answer') ?>
                </a>
            <?php endif; ?>

            <!-- time to read -->
            <span class="color-gray-900 font-weight-800 mx-1">&middot;</span>
            <?= _('Answer updated').' '.DateTime_Humanizer::humanizeTimestamp($this->lang, $this->answer->getUpdatedAt()) ?>
            <!-- / time to read -->

            <?php if ($this->answer->getText()): ?>
                <span class="d-none d-md-inline color-gray-900 font-weight-800 mx-1">&middot;</span>
                <span class="d-none d-md-inline">
                    <?= $this->question->getHumanizedMinutesToRead() ?>
                </span>
            <?php endif; ?>

        </div>
    </div>
</div>
<!-- / info_about_question -->
