
<div class="my-5">
    <?php if ($this->answer->getText()): ?>
        <p class="mb-3">
            <?= _('If you like the answer or you know someone to whom it might be interesting, share a link with your friends.') ?>
        </p>
    <?php else: ?>
        <p class="mb-3">
            <?= _('If you have friends who know the answer to this question, share the link.') ?>
        </p>
    <?php endif; ?>
    <script src="//yastatic.net/share2/share.js" async="async" charset="utf-8"></script>
    <div class="ya-share2" style="min-height: 24px;" data-services="twitter,vkontakte,facebook,gplus,pinterest,delicious,digg,reddit,pocket,tumblr,collections,telegram" data-size="m" data-counter="" data-title="<?= $this->shareLink['title'] ?>" data-description="<?= $this->shareLink['description'] ?>" data-url="<?= $this->shareLink['url'] ?>" data-image="<?= $this->shareLink['image'] ?>"></div>
</div>
