
<!-- how_it_works -->
<div class="border-bottom my-5 pb-4">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="mb-4">
                    <?= _('How it works?') ?>
                </h2>
            </div>
        </div>
        <div class="row">
            <div class="col-2 col-sm-1 text-center">
                <p class="h1 text-center" style="color: #3498db;">
                    <i class="far fa-question-circle"></i>
                </p>
            </div>
            <div class="col-10 col-sm-3">
                <p class="color-gray-600">
                    <?= _('You ask a question about any hashtag of interest to you') ?>?
                </p>
            </div>

            <div class="col-2 col-sm-1 text-center">
                <p class="h1 text-center" style="color: #7458E1;">
                    <i class="fas fa-users"></i>
                </p>
            </div>
            <div class="col-10 col-sm-3">
                <p class="color-gray-600">
                    <?= _('We find a specialist who can give a competent answer') ?>?
                </p>
            </div>

            <div class="col-2 col-sm-1 text-center">
                <p class="h1 text-center" style="color: #228C4C;">
                    <i class="far fa-paper-plane"></i>
                </p>
            </div>
            <div class="col-10 col-sm-3">
                <p class="color-gray-600">
                    <?= _('You receive an answer to the email') ?>?
                </p>
            </div>
        </div>
    </div>
</div>
<!-- / how_it_works -->
