
<!-- how_it_works -->

<h3 class="mb-4 mt-5">
    <?= $this->translator->get('main', 'how_it_works', 'title') ?>
</h3>

<div class="card-deck">
	<div class="card">
		<img src="https://answeropedia.org/assets/img/step_1.jpg" class="card-img-top" alt="...">
    	<div class="card-body">
    		<h5 class="card-title"><?= $this->translator->get('main', 'how_it_works', 'step_1_title') ?></h5>
    		<p class="card-text">
				<?= $this->translator->get('main', 'how_it_works', 'step_1_msg') ?>
			</p>
    		<p class="card-text"><small class="text-muted">Подробнее</small></p>
    	</div>
	</div>
	<div class="card">
		<img src="https://answeropedia.org/assets/img/step_2.jpg" class="card-img-top" alt="...">
    	<div class="card-body">
    		<h5 class="card-title"><?= $this->translator->get('main', 'how_it_works', 'step_2_title') ?></h5>
    		<p class="card-text"><?= $this->translator->get('main', 'how_it_works', 'step_2_msg') ?></p>
    		<p class="card-text"><small class="text-muted">Подробнее</small></p>
    	</div>
	</div>
	<div class="card">
		<img src="https://answeropedia.org/assets/img/step_3.jpg" class="card-img-top" alt="...">
    	<div class="card-body">
    		<h5 class="card-title"><?= $this->translator->get('main', 'how_it_works', 'step_3_title') ?></h5>
    		<p class="card-text">
				<?= $this->translator->get('main', 'how_it_works', 'step_3_msg') ?>
			</p>
    		<p class="card-text"><small class="text-muted">Подробнее</small></p>
    	</div>
	</div>
</div>

<!-- / how_it_works -->
