
<!-- jumbotron -->
<div class="jumbotron bg-color-gray-200 border-bottom">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 mx-auto text-center">
                <h1>
                    <?= _('Ask a question and get one complete answer') ?>
                </h1>
                <p class="color-gray-600 mt-3">
                    <?= _('What do you mean complete?') ?>
                </p>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12 col-md-10 mx-auto">
                <form id="form__question_create_from_main">
                    <div class="form-group">
                        <textarea class="form-control form-control-lg" id="form__question_create_from_main__title" rows="6" placeholder="<?= _('What is your question?') ?>?"></textarea>
                    </div>
                    <button type="submit" id="form__question_create_from_main__submit" class="btn btn-lg btn-block btn-primary">
                        <?= _('Ask a question') ?>
                    </button>
                    <!-- <div class="color-gray-700 mt-4">
                        или
                        <a href="https://answeropedia.org/ru/signup">присоединяйтесь</a>
                    </div> -->
                </form>
            </div>
        </div>
    </div>
</div>
<!-- / jumbotron -->
