
<h2 class=""></h2>
<div class="h3 mb-4 mt-5">
    <?= $this->translator->get('main', 'recent_questions', 'title') ?>
</div>

<!-- interesting questions -->
<?php if (isset($this->recent_questions)): ?>
    <?php foreach ($this->recent_questions as $question): ?>
        <div class="my-4">
            
            <div class="mb-2">
                <a class="lead color-secondary-dark-4 text-decoration-none" href="<?= $question->getURL($this->lang) ?>">
                    <?= $question->title ?>
                </a>
            </div>

            <?php if ($question->getShortAnswer()): ?>
                <div class="color-secondary-dark-2 my-2">
                    <?= $question->getShortAnswer(); ?>
                </div>
            <?php endif; ?>

            <?php if ($question->imageBaseName): ?>
                <a class="d-block max-width-240px" href="<?= $question->getURL($this->lang) ?>">
                    <img class="max-width-240px" src="<?= $question->getImageURLMedium($this->lang) ?>" alt="<?= $question->title ?>">
                </a>
            <?php endif; ?>

            <div class="mt-2">
                <?php if ((strtotime("now") - strtotime($question->answer->updatedAt)) < (60*60*24)): ?>
                    <span class="badge badge-primary mr-2">Новый</span>
                <?php endif; ?>

                <?php if (strlen($question->answer->text)): ?>
                    <span class="small color-secondary-light-1">2 автора</a>
                    <span class="mx-1 color-secondary-dark-2 font_weight_800">&middot;</span>
                    <i class="far fa-clock"></i>
                    <span class="small color-secondary-light-1"><?= $question->getMinutesToRead() ?></span>
                    <span class="mx-1 color-secondary-dark-2 font_weight_800">&middot;</span>
                <?php endif; ?>

                <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->answer->updatedAt) ?>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<!-- /interesting questions -->

<!-- question item -->

<!-- / question item -->
