
<div class="my-5">
    <div class="h3 mb-3">
        <?= $this->translator->get('main', 'share_link', 'title') ?>
    </div>
    <p class=""><?= $this->translator->get('main', 'share_link', 'note') ?></p>

    <script src="//yastatic.net/share2/share.js" async="async" charset="utf-8"></script>
    <div class="ya-share2"
        data-services="twitter,vkontakte,facebook,gplus,pinterest,delicious,digg,reddit,pocket,tumblr,collections,telegram"
        data-size="m"
        data-counter=""
        data-title="<?= $this->shareLink['title'] ?>"
        data-description="<?= $this->shareLink['description'] ?>"
        data-url="<?= $this->shareLink['url'] ?>"
        data-image="<?= $this->shareLink['image'] ?>">
    </div>
    
</div>