<!-- 1,000,000+ content pages -->
<div class="border rounded bg-white p-3 my-4">

    <h2 class="lead border-bottom text-center pb-3 pt-0 mb-4">
        <?= __('page_root.langlist.lang_launched') ?>
    </h2>

    <div class="mx-2">
        <div class="row mb-md-2">
            <div class="col-12 col-md-3 mb-2 mb-md-0">
                <ul class="list-unstyled mb-0">
                    <li>
                        <a href="https://answeropedia.org/en" lang="en">English</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-md-3 mb-2 mb-md-0">
                <ul class="list-unstyled mb-0">
                    <li>
                        <a href="https://answeropedia.org/ru" lang="ru">Русский</a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-md-3 mb-2 mb-md-0">
                <ul class="list-unstyled mb-0">
                    <li>
                        <a class="text-primary text-decoration-none" href="#foo" data-toggle="modal" data-target="#modal-root-support">
                            <i class="material-icons mr-1">translate</i>&nbsp;<?= __('page_root.langlist.request_lang') ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-md-3">
                <!-- x -->
            </div>
        </div>
    </div>

</div>

<!-- 100,000+ content pages -->
<div class="border rounded bg-white p-3 mt-4 mb-5">

    <h2 class="lead border-bottom text-center pb-3 pt-0 mb-4">
        <?= __('page_root.langlist.lang_future') ?>
    </h2>

    <div class="mx-2">
        <div class="row">
            <div class="col-12 col-md-3">
                <ul class="list-unstyled mb-0">
                    <li><a href="#de" data-toggle="modal" data-target="#modal-root-support" lang="de">Deutsch</a></li>
                    <li><a href="#es" data-toggle="modal" data-target="#modal-root-support" lang="es">Español</a></li>
                    <li><a href="#fr" data-toggle="modal" data-target="#modal-root-support" lang="fr">Français</a></li>
                    <li><a href="#it" data-toggle="modal" data-target="#modal-root-support" lang="it">Italiano</a></li>
                    <li><a href="#nl" data-toggle="modal" data-target="#modal-root-support" lang="nl">Nederlands</a></li>
                    <li><a href="#ja" data-toggle="modal" data-target="#modal-root-support" lang="ja" title="Nihongo">日本語</a></li>
                    <li><a href="#pl" data-toggle="modal" data-target="#modal-root-support" lang="pl">Polski</a></li>
                    <li><a href="#simple" data-toggle="modal" data-target="#modal-root-support" lang="en">Simple English</a></li>
                    <li><a href="#ceb" data-toggle="modal" data-target="#modal-root-support" lang="ceb">Sinugboanong Binisaya</a></li>
                    <li><a href="#sv" data-toggle="modal" data-target="#modal-root-support" lang="sv">Svenska</a></li>
                    <li><a href="#vi" data-toggle="modal" data-target="#modal-root-support" lang="vi">Tiếng Việt</a></li>
                    <li><a href="#war" data-toggle="modal" data-target="#modal-root-support" lang="war">Winaray</a></li>
                    <li><a href="#pt" data-toggle="modal" data-target="#modal-root-support" lang="pt">Português</a></li>
                    <li><a href="#da" data-toggle="modal" data-target="#modal-root-support" lang="da">Dansk</a></li>
                </ul>
            </div>
            <div class="col-12 col-md-3">
                <ul class="list-unstyled mb-0">
                    <li><a href="#ar" data-toggle="modal" data-target="#modal-root-support" lang="ar" title="Al-ʿArabīyah"><bdi dir="rtl">العربية</bdi></a></li>
                    <li><a href="#az" data-toggle="modal" data-target="#modal-root-support" lang="az">Azərbaycanca</a></li>
                    <li><a href="#bg" data-toggle="modal" data-target="#modal-root-support" lang="bg" title="Bǎlgarski">Български</a></li>
                    <li><a href="#zh-min-nan" data-toggle="modal" data-target="#modal-root-support" lang="nan">Bân-lâm-gú / Hō-ló-oē</a></li>
                    <li><a href="#be" data-toggle="modal" data-target="#modal-root-support" lang="be" title="Belaruskaya (Akademichnaya)">Беларуская (Акадэмічная)</a></li>
                    <li><a href="#la" data-toggle="modal" data-target="#modal-root-support" lang="la">Latina</a></li>
                    <li><a href="#ca" data-toggle="modal" data-target="#modal-root-support" lang="ca">Català</a></li>
                    <li><a href="#cs" data-toggle="modal" data-target="#modal-root-support" lang="cs">Čeština</a></li>
                    <li><a href="#et" data-toggle="modal" data-target="#modal-root-support" lang="et">Eesti</a></li>
                    <li><a href="#el" data-toggle="modal" data-target="#modal-root-support" lang="el" title="Ellīniká">Ελληνικά</a></li>
                    <li><a href="#eo" data-toggle="modal" data-target="#modal-root-support" lang="eo">Esperanto</a></li>
                    <li><a href="#eu" data-toggle="modal" data-target="#modal-root-support" lang="eu">Euskara</a></li>
                    <li><a href="#fa" data-toggle="modal" data-target="#modal-root-support" lang="fa" title="Fārsi"><bdi dir="rtl">فارسی</bdi></a></li>
                    <li><a href="#gl" data-toggle="modal" data-target="#modal-root-support" lang="gl">Galego</a></li>
                </ul>
            </div>
            <div class="col-12 col-md-3">
                <ul class="list-unstyled mb-0">
                    <li><a href="#ko" data-toggle="modal" data-target="#modal-root-support" lang="ko" title="Hangugeo">한국어</a></li>
                    <li><a href="#hy" data-toggle="modal" data-target="#modal-root-support" lang="hy" title="Hayeren">Հայերեն</a></li>
                    <li><a href="#hi" data-toggle="modal" data-target="#modal-root-support" lang="hi" title="Hindī">हिन्दी</a></li>
                    <li><a href="#hr" data-toggle="modal" data-target="#modal-root-support" lang="hr">Hrvatski</a></li>
                    <li><a href="#id" data-toggle="modal" data-target="#modal-root-support" lang="id">Bahasa Indonesia</a></li>
                    <li><a href="#he" data-toggle="modal" data-target="#modal-root-support" lang="he" title="ʿIvrit"><bdi dir="rtl">עברית</bdi></a></li>
                    <li><a href="#ka" data-toggle="modal" data-target="#modal-root-support" lang="ka" title="Kartuli">ქართული</a></li>
                    <li><a href="#lt" data-toggle="modal" data-target="#modal-root-support" lang="lt">Lietuvių</a></li>
                    <li><a href="#hu" data-toggle="modal" data-target="#modal-root-support" lang="hu">Magyar</a></li>
                    <li><a href="#ms" data-toggle="modal" data-target="#modal-root-support" lang="ms">Bahasa Melayu</a></li>
                    <li><a href="#min" data-toggle="modal" data-target="#modal-root-support" lang="min">Bahaso Minangkabau</a></li>
                    <li><a href="#ce" data-toggle="modal" data-target="#modal-root-support" lang="ce" title="Noxçiyn">Нохчийн</a></li>
                    <li><a href="#uz" data-toggle="modal" data-target="#modal-root-support" lang="uz">Oʻzbekcha / Ўзбекча</a></li>
                    <li><a href="#kk" data-toggle="modal" data-target="#modal-root-support" lang="kk"><span lang="kk-Cyrl">Қазақша</span> / <span lang="kk-Latn">Qazaqşa</span> / <bdi lang="kk-Arab" dir="rtl">قازاقشا</bdi></a></li>
                    <li><a href="#zh" data-toggle="modal" data-target="#modal-root-support" lang="zh" title="Zhōngwén">中文</a></li>
                </ul>
            </div>
            <div class="col-3">
                <ul class="list-unstyled">
                    <li><a href="#ro" data-toggle="modal" data-target="#modal-root-support" lang="ro">Română</a></li>
                    <li><a href="#sk" data-toggle="modal" data-target="#modal-root-support" lang="sk">Slovenčina</a></li>
                    <li><a href="#sl" data-toggle="modal" data-target="#modal-root-support" lang="sl">Slovenščina</a></li>
                    <li><a href="#sr" data-toggle="modal" data-target="#modal-root-support" lang="sr">Српски / Srpski</a></li>
                    <li><a href="#sh" data-toggle="modal" data-target="#modal-root-support" lang="sh">Srpskohrvatski / Српскохрватски</a></li>
                    <li><a href="#no" data-toggle="modal" data-target="#modal-root-support" lang="nb">Norsk (Bokmål)</a></li>
                    <li><a href="#nn" data-toggle="modal" data-target="#modal-root-support" lang="nn">Norsk (Nynorsk)</a></li>
                    <li><a href="#fi" data-toggle="modal" data-target="#modal-root-support" lang="fi">Suomi</a></li>
                    <li><a href="#ta" data-toggle="modal" data-target="#modal-root-support" lang="ta" title="Tamiḻ">தமிழ்</a></li>
                    <li><a href="#th" data-toggle="modal" data-target="#modal-root-support" lang="th" title="Phasa Thai">ภาษาไทย</a></li>
                    <li><a href="#tr" data-toggle="modal" data-target="#modal-root-support" lang="tr" title="Turkce">Türkçe</a></li>
                    <li><a href="#uk" data-toggle="modal" data-target="#modal-root-support" lang="uk" title="Ukrayins’ka">Українська</a></li>
                    <li><a href="#ur" data-toggle="modal" data-target="#modal-root-support" lang="ur" title="Urdu"><bdi dir="rtl">اردو</bdi></a></li>
                    <li><a href="#vo" data-toggle="modal" data-target="#modal-root-support" lang="vo">Volapük</a></li>
                </ul>
            </div>
        </div>
    </div>

</div>