<!-- modal support -->
<div class="modal fade" id="modal-root-support" tabindex="-1" role="dialog" aria-labelledby="modal-root-support-title" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-root-support-title">
                    <?= __('page_root.modal.title') ?>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <?= __('page_root.modal.msg') ?>
                <div class="my-3">
                    <a href="https://www.facebook.com/hello.gomzyakov" target="_blank">
                        <?= __('common.social_networks.facebook') ?>
                    </a>
                    <span class="text-black-50 mx-1">&middot;</span>
                    <a href="https://vk.com/alexandergomzyakov" target="_blank">
                        <?= __('common.social_networks.vk') ?>
                    </a>
                    <span class="text-black-50 mx-1">&middot;</span>
                    <a href="mailto:alexander.gomzyakov@gmail.com">
                        <?= __('common.social_networks.email') ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- / modal support -->