<!-- navbar -->

<header class="navbar sticky-top navbar-expand-lg navbar-light">
    <div class="container">
        <a class="navbar-brand mr-3" href="<?= SITE_URL ?>">
            <?= __('common.answeropedia') ?>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-supported-content" aria-controls="navbar-supported-content" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-supported-content">
            <ul class="navbar-nav pt-3 pt-lg-0">
                <li class="nav-item d-none d-lg-block navbar-text text-muted">
                    <?= __('page_root.navbar.note') ?>
                </li>
            </ul>

            <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">

                <li class="nav-item">
                    <a class="nav-link text-primary" href="<?= $this->questionAboutAnsweropedia->getURL($this->lang) ?>">
                        <?= __('About Answeropedia') ?>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</header>
<!-- / navbar -->