
<div class="text-center my-8">
    <p class="lead"><?= $this->l->t('main_pg__share__intro') ?></p>
    <script src="//yastatic.net/share2/share.js" async="async" charset="utf-8"></script>
    <div class="ya-share2"
        data-services="twitter,vkontakte,facebook,gplus,pinterest,delicious,digg,reddit,pocket,tumblr,collections,telegram"
        data-size="m"
        data-counter=""
        data-title="<?= $this->shareLink['title'] ?>"
        data-description="<?= $this->shareLink['description'] ?>"
        data-url="<?= $this->shareLink['url'] ?>"
        data-image="<?= $this->shareLink['image'] ?>">
    </div>
</div>
