	
<nav class="collapse bd-links" id="bd-docs-nav">
	
	<div class="bd-toc-item active">
		<a class="bd-toc-link" href="#">
			<?= $this->translator->get('Tools') ?>
		</a>
		<ul class="nav bd-sidenav">
			<li>
				<a href="<?= $this->question->getHistoryURL($this->lang) ?>">
					<?= $this->translator->get('Change history') ?>
				</a>
			</li>
			<li>
				<a href="#" data-toggle="modal" data-target="#modal_rename">
					<?= $this->translator->get('Rename question') ?>
				</a>
			</li>
			<li>
				<a href="#">
					<s>Ссылки сюда</s>
				</a>
			</li>
			<li>
				<a href="#">
					<s>Сведения о странице</s>
				</a>
			</li>
		</ul>
	</div>

</nav>

