
<nav class="ml-2 my-4">
	<div class="subtitle-1 color-secondary-dark-1">
        <?= $this->translator->get('Tools') ?>
	</div>
	<ul class="list-links">
        <li>
            <a href="<?= $this->question->getHistoryURL($this->lang) ?>">
                <?= $this->translator->get('Change history') ?>
            </a>
        </li>
        <li>
            <a href="#" data-toggle="modal" data-target="#modal_rename_question">
                <?= $this->translator->get('Rename question') ?>
            </a>
        </li>
        <li>
            <a href="#">
                <s>Ссылки сюда</s>
            </a>
        </li>
        <li>
            <a href="#">
                <s>Сведения о странице</s>
            </a>
        </li>
	</ul>
</nav>


