
<!-- header info -->
<div class="color-gray-500 small mt-4">

    <?php if ($this->answer->getText()): ?>
        <?= $this->question->getHumanizedMinutesToRead() ?>
        <span class="color-gray-900 font-weight-800 mx-1">&middot;</span>
    <?php endif; ?>

    <?php if (count($this->contributors)): ?>
        <a href="#contributors_full_list" class="color-gray-500 no-underline-hover">
            <?= (new Contributors_Humanizer($this->l))->humanize(count($this->contributors)) ?>
        </a>
    <?php else: ?>
        <a href="<?= $this->question->getEditURL($this->lang) ?>" class="color-gray-500 no-underline-hover">
            <?= _('Edit answer') ?>
        </a>
    <?php endif; ?>

    <!-- time to read -->
    <span class="d-none d-md-inline color-gray-900 font-weight-800 mx-1">&middot;</span>
    <span class="d-none d-md-inline">
        <?= _('Answer updated').' '.DateTime_Humanizer::humanizeTimestamp($this->lang, $this->answer->getUpdatedAt()) ?>
    </span>
    <!-- / time to read -->

</div>
<!-- / header info -->
