
<?php if (!$this->authUser): ?>
<div class="container max-width-md">
    <div class="row">
        <div class="col-12 my-5">
            <div class="alert alert-warning">
                <div class="text-center">
                    <img class="wh-96 mx-auto mt-4 mb-4" alt="<?= _('OctoAnswers is a wiki-based site where users can ask questions, respond to them and supplement other people’s answers') ?>" src="https://png.icons8.com/office/96/e74c3c/astronaut-helmet.png">
                </div>

                <p><strong><?= _('Signup') ?></strong></p>
                <p><?= _('OctoAnswers is a wiki-based site where users can ask questions, respond to them and supplement other people’s answers') ?></p>

                <div class="mt-4">
                    <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#modal_login">
                        <?= _('Login') ?>
                    </a>
                    <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#modal_signup">
                        <?= _('Signup') ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
