
<?php if (!$this->authUser): ?>
<div class="container-fluid max-width-md">
    <div class="row">
        <div class="col-12 my-5">
            <div class="alert alert-warning">
                <div class="text-center">
                    <img class="wh-96 mx-auto mt-4 mb-4" alt="<?= _('Users - Signup lure - Image alt') ?>" src="https://png.icons8.com/office/96/e74c3c/astronaut-helmet.png">
                </div>

                <p><strong><?= _('Users - Signup lure - Title') ?></strong></p>
                <p><?= _('Users - Signup lure - Text') ?></p>

                <div class="mt-4">
                    <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#modal_login">
                        <?= _('Navbar - Login') ?>
                    </a>
                    <a class="btn btn-outline-primary" href="#" data-toggle="modal" data-target="#modal_signup">
                        <?= _('Navbar - Signup') ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
