
<?php if (count($this->users)): ?>
    <?php foreach ($this->users as $user): ?>
        <div class="my-4">
            <div class="border-bottom pb-4">
                <div class="float-right">
                    <a class="size-6" href="<?= User_URL_Helper::getURL($this->lang, $user) ?>">
                        <img class="size-6 img-cover rounded-circle mt-1" src="<?= User_URL_Helper::getAvatarSmallURL($user) ?>">
                    </a>
                </div>
                <div class="mr-8">
                    <div class="pr-3 pr-sm-4">
                        <a class="h3 align-middle link_gray_900 no_underline mr-3" href="<?= User_URL_Helper::getURL($this->lang, $user) ?>">
                            <?= $user->getName() ?>
                        </a>
                        <button class="btn btn-sm btn-outline-success align-middle" role="button">
                            Подписаться
                        </button>
                    </div>
                    <div class="color-gray-500 my-2">
                        <?php if ($user->getSignature()): ?>
                            <?= $user->getSignature() ?>
                        <?php endif; ?>

                        <?php if ($user->getSignature() && $user->getSite()): ?>
                            <span class="mx-1 color-gray-900 font_weight_800">&middot;</span>
                        <?php endif; ?>

                        <?php if ($user->getSite()): ?>
                            <a href="<?= $user->getSite() ?>">
                                <?= parse_url($user->getSite(), PHP_URL_HOST) ?>
                            </a>
                        <?php endif; ?>
                    </div>
                    <div class="mt-2 small color-gray-700">
                        26 ответов
                        <span class="mx-1 color-gray-900 font_weight_800">&middot;</span>
                        12 подписчиков
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
