
<div class="row">
    <div class="col-12 mt-5">
        <div class="h2 mb-2">
            Авторы ответов
        </div>
        <ul class="nav_underlined">
            <li>
                <a class="active" href="<?= Users_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= $this->l->t('users__filter__newest') ?>
                </a>
            </li>
            <li>
                <a href="#">
                    <?= $this->l->t('users__filter__popular') ?>
                </a>
            </li>
        </ul>
    </div>
</div>
