
<?php if (count($this->users)): ?>
    <!-- users_table -->
    <table class="table table-box">
        <thead>
            <tr>
                <th class="width-6" scope="col"></th>
                <th scope="col">Автор</th>
                <th scope="col">
                    <i class="fas fa-edit" style="color: #1e88e5;"></i>
                </th>
                <th class="d-none d-sm-table-cell" scope="col">
                    <i class="far fa-question-circle" style="color: #e51e24;"></i>
                </th>
                <th class="d-none d-sm-table-cell" scope="col">
                    <i class="fas fa-user-friends" style="color: #444444;"></i>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->users as $user): ?>
                <tr>
                    <td class="width-6">
                        <a class="size-6" href="<?= $user->getURL($this->lang) ?>">
                            <img class="size-6 rounded" src="<?= $user->getAvatarSmallURL() ?>">
                        </a>
                    </td>
                    <td>
                        <div class="font-weight-700">
                            <a class="color-gray-900 no_underline" href="<?= $user->getURL($this->lang) ?>">
                                <?= $user->getName() ?>
                            </a>
                        </div>
                        <div class="small color-gray-600">
                            <?php if ($user->getSignature()): ?>
                                <?= $user->getSignature() ?>
                            <?php endif; ?>

                            <?php if ($user->getSignature() && $user->getSite()): ?>
                                <span class="font-weight-800 mx-1 color-gray-800">&middot;</span>
                            <?php endif; ?>

                            <?php if ($user->getSite()): ?>
                                <a href="<?= $user->getSite() ?>">
                                    <?= parse_url($user->getSite(), PHP_URL_HOST) ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        2.0K
                    </td>
                    <td class="d-none d-sm-table-cell">
                        26
                    </td>
                    <td class="d-none d-sm-table-cell">
                        16
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <!-- / users_table -->
<?php endif; ?>
