
<?php if ($this->isShowQuestionsFollowLure): ?>
    <!-- lure follow_3_questions -->
    <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-3">
        <div class="mr-3 d-none d-sm-block">
            <i class="fas fa-check"></i>
        </div>
        <div class="width-full">
            <div class="color-gray-900 font-weight-bold mb-2">
                <?= _('Follow some questions') ?>
            </div>
            <div class="small color-gray-700 mb-3">
                <?= _('By subscribing to interesting questions, you can follow their edits. Find and subscribe to three or more questions.') ?>.
            </div>
            <a  class="btn btn-sm btn-outline-primary" href="<?= Questions_URL_Helper::getNewestURL($this->lang) ?>">
                <?= _('Views a questions') ?>
            </a>
        </div>
    </div>
    <!-- / lure follow_3_questions -->
<?php endif; ?>
