
<?php if ($this->isShowHashtagsFollowLure): ?>
    <!-- lure follow_3_hashtags -->
    <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-3">
        <div class="mr-3 d-none d-sm-block">
            <i class="fas fa-check"></i>
        </div>
        <div class="width-full">
            <div class="color-gray-900 font-weight-bold mb-2">
                <?= _('Subscribe to several hashtags') ?>
            </div>
            <div class="small color-gray-700 mb-3">
                <?= _('Select and subscribe to three topics close to you. Questions on these topics will appear in your news feed.') ?>
            </div>
            <a  class="btn btn-sm btn-outline-primary" href="<?= Hashtags_URL_Helper::getNewestURL($this->lang) ?>">
                <?= _('View popular hashtags') ?>
            </a>
        </div>
    </div>
    <!-- / lure follow_3_hashtags -->
<?php endif; ?>
