
<?php if ($this->isShowTopicsFollowLure): ?>
    <!-- lure follow_3_topics -->
    <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-3">
        <div class="mr-3 d-none d-sm-block">
            <i class="fas fa-check"></i>
        </div>
        <div class="width-full">
            <div class="color-gray-900 font-weight-600 mb-2">
                Подпишитесь на несколько тем
            </div>
            <div class="small color-gray-700 mb-3">
                Выберите и подпишитесь на три близких вам темы. Вопросы на эти темы будут появляться у вас в ленте новостей.
            </div>
            <a  class="btn btn-sm btn-outline-primary" href="<?= Topics_URL_Helper::getNewestURL($this->lang) ?>">
                Посмотреть темы
            </a>
        </div>
    </div>
    <!-- / lure follow_3_topics -->
<?php endif; ?>
