
<?php if ($this->isShowUsersFollowLure): ?>
    <!-- lure follow_3_users -->
    <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-3">
        <div class="mr-3 d-none d-sm-block">
            <i class="fas fa-check"></i>
        </div>
        <div class="width-full">
            <div class="color-gray-900 font-weight-600 mb-2">
                Найдите первых друзей
            </div>
            <div class="small color-gray-700 mb-3">
                Найдите и подпишитесь на три интересных вам пользователя. Вопросы, ответы и прочие активности этих пользователей будут появляться у вас в ленте новостей.
            </div>
            <a  class="btn btn-sm btn-outline-primary" href="<?= Users_URL_Helper::getNewestURL($this->lang) ?>">
                Посмотреть пользователей
            </a>
        </div>
    </div>
    <!-- / lure follow_3_users -->
<?php endif; ?>
