
<?php if (strlen($this->authUser->signature) == 0): ?>
    <!-- lure set_signature -->
    <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-3">
        <div class="mr-3 d-none d-sm-block">
            <i class="fas fa-check"></i>
        </div>
        <div class="width-full">
            <div class="color-secondary-dark-4 font-weight-bold mb-2">
                Придумайте подпись
            </div>
            <div class="small color-secondary-dark-2 mb-3">
                Подпись описывает ваши профессиональные навыки и знания. Она показываться рядом с правками ответов, которые вы делаете.
            </div>
            <a  class="btn btn-sm btn-outline-primary" href="<?= Settings_URL_Helper::getSignatureURL($this->lang) ?>">
                Задать подпись
            </a>
        </div>
    </div>
    <!-- / lure set_signature -->
<?php endif; ?>
