<?php if ($this->authUser->username == $this->authUser->name) : ?>
    <!-- lure set_real_name -->
    <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-3">
        <div class="mr-3 d-none d-sm-block">
            <i class="material-icons md-24">check</i>
        </div>
        <div class="width-full">
            <div class="text-dark font-weight-bold mb-2">
                <?= $this->translator->get('feed', 'set_real_name', 'title') ?>
            </div>
            <div class="small text-muted mb-3">
                <?= $this->translator->get('feed', 'set_real_name', 'msg') ?>
            </div>
            <a class="btn btn-sm btn-outline-primary" href="<?= \Helper\URL\Settings::get_real_name_URL($this->lang) ?>">
                <?= $this->translator->get('feed', 'set_real_name', 'action') ?>
            </a>
        </div>
    </div>
    <!-- / lure set_real_name -->
<?php endif; ?>