
<?php if (false): ?>
    <!-- lure write_answer -->
    <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-3">
        <div class="mr-3 d-none d-sm-block">
            XXX
        </div>
        <div class="width-full">
            <div class="color-gray-900 font-weight-bold mb-2">
                <?= _('FEED.LURE.WRITE_ANSWER.TITLE') ?>
            </div>
            <div class="small color-gray-700 mb-3">
                <?= _('FEED.LURE.WRITE_ANSWER.MSG') ?>.
            </div>
            <a  class="btn btn-sm btn-outline-primary" href="<?= Sandbox_URL_Helper::getWithoutAnswersURL($this->lang) ?>">
                <?= _('FEED.LURE.WRITE_ANSWER.LINK') ?>
            </a>
        </div>
    </div>
    <!-- / lure write_answer -->
<?php endif; ?>
