
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link <?= ($this->list == 'with-answers') ? 'active' : '' ?>" href="<?= Questions_URL_Helper::getNewestURL($this->lang) ?>">
            <?= $this->translator->get('questions', 'nav', 'newest') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?= ($this->list == 'recently_updated') ? 'active' : '' ?>" href="<?= Questions_URL_Helper::getRecentlyUpdatedURL($this->lang) ?>">
            <?= $this->translator->get('questions', 'nav', 'recently_updated') ?>
        </a>
    </li>
    <!-- <li class="nav-item">
        <a class="nav-link disabled <?= ($this->list == 'without-answers') ? 'active' : '' ?>" href="#">
            <?= $this->translator->get('questions', 'nav', 'popular') ?>
        </a>
    </li> -->
</ul>
