<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>

    <!-- SimpleMDE CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
</head>
<body>
    <?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-10 col-md-9 mx-auto pb-5">

                <?php require_once TEMPLATE_PATH.'/answer/edit/header.phtml'; ?>

                <form id="form__update_answer" data-answer-id="<?= $this->answer->getID() ?>">
                    <div class="form-group">
                        <textarea id="form__update_answer__answer_text" name="answer_text" class="form-control" rows="10"><?= $this->answer->getText() ?></textarea>
                        <label class="mt-0 small text-muted"><?= _('Description of changes') ?></label>
                        <input id="form__update_answer__changes_comment" type="text" class="form-control">
                    </div>
                    <div class="form-group mt-4">
                        <button type="submit" id="form__update_answer__submit" class="btn btn-success btn-lg btn-block">
                            <?= _('Save') ?>
                        </button>
                    </div>
                </form>

                <?php require_once TEMPLATE_PATH.'/answer/edit/simplemde.phtml'; ?>
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
