<!-- modal_ask -->
<div class="modal fade" id="modal_ask" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <?= __('modals.ask.title') ?>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form__question_create">
                <div class="modal-body">
                    <div class="form-group">
                        <label class="small text-muted mb-3">
                            <?= __('modals.ask.note') ?>.
                        </label>
                        <textarea class="form-control" id="question_title" rows="6" placeholder="<?= __('modals.ask.input_placeholder') ?>"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="form__question_create__submit" class="btn btn-block btn-primary">
                        <?= __('modals.ask.btn_ask') ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- / modal_ask -->