<!-- modal login -->
<div class="modal fade" id="modal_login" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <?= $this->translator->get('modal', 'login', 'title') ?>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form__login">
                <div class="modal-body">
                    <div class="form-group">
                        <label><?= $this->translator->get('modal', 'login', 'email') ?></label>
                        <input id="form__login__email" type="email" class="form-control">
                    </div>
                    <div class="form-group">
                        <label><?= $this->translator->get('modal', 'login', 'password') ?></label>
                        <input id="form__login__password" type="password" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="form__login__submit" class="btn btn-lg btn-primary btn-block">
                        <?= $this->translator->get('modal', 'login', 'btn_login') ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /modal login -->