
<?php if ($this->isShowTopicsFollowLure): ?>
    <div class="activity__lure my-4">
        <div class="icon">
            <img src="https://png.icons8.com/wired/64/D81B60/topic.png">
        </div>
        <div class="info">
            <p class="title">Подпишитесь на несколько хештегов</p>
            <p class="message">Выберите и подпишитесь на три или более хештега, тематика которых вам близка. Вопросы с этими хештегами будут появляться у вас в ленте новостей.</p>
            <a href="<?= Topics_URL_Helper::getNewestURL($this->lang) ?>" class="btn btn-primary">
                Исследовать #хештеги
            </a>
        </div>
    </div>
<?php endif; ?>
