
<?php if (true): ?>
    <div class="activity__lure my-4">
        <div class="icon">
            <img src="https://png.icons8.com/wired/64/9C27B0/faq.png">
        </div>
        <div class="info">
            <p class="title">Напишите первый ответ</p>
            <p class="message">Посмотрите вопросы на которые еще никто не написал ответа и станьте первым автором.</p>
            <a href="<?= Sandbox_URL_Helper::getWithoutAnswersURL($this->lang) ?>" class="btn btn-primary">
                Вопросы без ответов
            </a>
        </div>
    </div>
<?php endif; ?>
