
<ul class="list-inline small mb-4">
    <li class="list-inline-item">
        <a class="color-gray-500" href="#">
            <?= _('Footer - About') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" rel="nofollow" target="_blank" href="https://vk.com/alexandergomzyakov">
            <?= _('Footer - Support') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" href="<?= Users_URL_Helper::getNewestURL($this->lang) ?>">
            <?= _('Footer - Users') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" href="<?= Page_URL_Helper::getFlowURL($this->lang) ?>">
            <?= _('Footer - Flow') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" href="#">
            <?= _('Footer - Rules') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" rel="nofollow" target="_blank" href="https://icons8.com">
            <?= _('Footer - Icon pack by icons8') ?>
        </a>
    </li>
</ul>
