
<ul class="list-inline small mb-4">
    <li class="list-inline-item">
        <a class="color-gray-500" href="#">
            <?= _('About OctoAnswers') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" rel="nofollow" target="_blank" href="https://vk.com/alexandergomzyakov">
            <?= _('Support') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" href="<?= Users_URL_Helper::getNewestURL($this->lang) ?>">
            <?= _('Users') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" href="<?= Page_URL_Helper::getFlowURL($this->lang) ?>">
            <?= _('Flow') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" href="#">
            <?= _('Rules') ?>
        </a>
    </li>
    <li class="list-inline-item">
        <a class="color-gray-500" rel="nofollow" target="_blank" href="https://icons8.com">
            <?= _('Icon pack by icons8') ?>
        </a>
    </li>
</ul>
