
<div class="mt-4 mb-5 mb-5 py-2 border-top border-bottom">

    <!-- edit answer -->
    <?php if ($this->authUser): ?>
        <a href="<?= $this->question->getEditURL($this->lang) ?>" class="btn btn-link p-0 my-2 mr-3">
            <?= _('Edit answer') ?>
        </a>
    <?php else: ?>
        <button type="button" class="btn btn-link p-0 my-2 mr-3" data-toggle="modal" data-target="#modal_lure__edit_answer">
            <?= _('Edit answer') ?>
        </button>
        <?php require_once TEMPLATE_PATH.'/question/modal/edit_answer_lure.phtml' ?>
    <?php endif; ?>
    <!-- / edit answer -->

    <a class="btn btn-link color-gray-600 p-0 my-2 mr-3" href="#" data-question-id="14858" data-follow-title="Подписаться" data-followed-title="Подписан" data-unfollow-title="Отписаться">
        <?= $this->followed ? _('Followed') : _('Follow'); ?>
    </a>

    <?php if (mb_strlen($this->answer->getText()) > 0): ?>
        <a href="<?= $this->question->getHistoryURL($this->lang) ?>" class="btn btn-link color-gray-600 p-0 my-2 mr-3">
            <?= _('History') ?>
        </a>
    <?php endif; ?>

    <div class="dropdown d-inline-block float-lg-right">
        <button role="button" class="btn btn-link color-gray-600 p-0 my-2 mr-2 dropdown-toggle" href="#" id="dropdown_menu__more" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <?= _('More') ?>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdown_menu__more">
            <?php if ($this->authUser): ?>

                <!-- Show "Upload image" modal -->
                <a class="dropdown-item" rel="nofollow" href="#" data-toggle="modal" data-target="#modal_upload_image">
                    <i class="fas fa-camera mr-2"></i>
                    <?= _('Upload image') ?>
                </a>

                <!-- Button trigger modal "Question rename" -->
                <a class="dropdown-item" rel="nofollow" href="#" data-toggle="modal" data-target="#modal_rename">
                    <i class="fas fa-edit mr-2"></i>
                    <?= _('Rename question') ?>
                </a>
            <?php endif; ?>
            <a class="dropdown-item" rel="nofollow" href="#">
                <i class="fas fa-flag mr-2"></i>
                <?= _('Report') ?>
            </a>
        </div>
    </div>
</div>
