<!-- Modal -->
<div class="modal fade" id="modal_rename_question" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <?= __('modals.question_rename.title') ?>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form__rename_question" data-question-id="<?= $this->question->id ?>">
                <div class="modal-body">
                    <div class="form-group">
                        <label class="semi-small text-secondary mb-3">
                            <?= __('modals.question_rename.note') ?>
                        </label>
                        <input id="new_title" class="form-control" type="text" value="<?= $this->question->title ?>">
                    </div>
                    <div class="form-check">
                        <label class="form-check-label mt-1">
                            <input id="save_redirect" type="checkbox" class="form-check-input" checked>
                            <span class="semi-small text-secondary">
                                <?= __('modals.question_rename.leave_redirect') ?>
                            </span>
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="form__rename_question__submit" class="btn btn-primary">
                        <?= __('modals.question_rename.btn_action') ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>