
<!-- header -->
<div class="row mt-4">
    <div class="col-auto col-md-12">
        <img class="wh-4 rounded-circle mb-4" src="<?= $this->user->getAvatarMediumURL() ?>" alt="<?= $this->user->getName() ?>">
    </div>
    <div class="col-auto col-md-12">
        <h1 class="h2 mb-1"><?= $this->user->getName() ?></h1>
        <div class="mb-3 color-gray-500 small">
            +<?= $this->user->getUsername() ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?php if ($this->user->getSignature()): ?>
            <div class="color-gray-700">
                <?= $this->user->getSignature() ?>
            </div>
        <?php endif; ?>

        <?php if ($this->user->getSite()): ?>
            <div class="mt-2">
                <i class="fas fa-globe" style="color: #757575;"></i>
                <a href="<?= $this->user->getSite() ?>">
                    <?= parse_url($this->user->getSite(), PHP_URL_HOST) ?>
                </a>
            </div>
        <?php endif; ?>

        <!-- actions -->
        <div class="mt-4">
            <?php if ($this->authUser && $this->authUser->getID() != $this->user->getID()): ?>
                <button
                    class="btn btn-block follow_user_button mr-2 mb-3 <?= $this->followed ? 'followed btn-success' : 'btn-primary'; ?>"
                    data-user-id="<?= $this->user->getID() ?>"
                    data-follow-title="<?= _('Follow') ?>"
                    data-followed-title="<?= _('Followed') ?>"
                    data-unfollow-title="<?= _('Unfollow') ?>" type="button">
                    <i class="far fa-bookmark"></i>
                    <span><?= $this->followed ? _('Followed') : _('Follow'); ?></span>
                </button>
            <?php endif; ?>
            <?php if ($this->authUser && ($this->authUser->getID() == $this->user->getID())): ?>
                <a rel="nofollow" class="btn btn-sm btn-outline-secondary mr-2 mb-3" href="<?= Settings_URL_Helper::getSettingsURL($this->lang) ?>">
                    <i class="fas fa-cog"></i>
                    <?= _('Settings') ?>
                </a>
                <a rel="nofollow" class="btn btn-sm btn-outline-secondary mr-2 mb-3" href="#" data-toggle="modal" data-target="#modal__logout">
                    <i class="fas fa-sign-out-alt"></i>
                    <?= _('Logout') ?>
                </a>
            <?php endif; ?>
        </div>
        <!-- / actions -->

    </div>
</div>
<!-- / header -->
