
<!-- Modal -->
<div class="modal fade" id="modal_rename" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <?= _('Rename question') ?>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form__rename_question" data-question-id="<?= $this->question->getID() ?>">
                <div class="modal-body">
                    <div class="form-group">
                        <label>
                            <?= _('Before you rename a question, please read the basic rules for renaming') ?></label>
                        <textarea class="form-control" id="new_title" rows="6"><?= $this->question->getTitle() ?></textarea>
                    </div>
                    <div class="form-check">
                        <label class="form-check-label mt-1">
                            <input id="save_redirect" type="checkbox" class="form-check-input" checked>
                            <?= _('Leave redirect') ?>
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="form__rename_question__submit" class="btn btn-primary">
                        <?= _('Rename question') ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
