
<!--noindex-->
<!--googleoff: index-->
<div id="modal__logout" class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title ml-auto mr-auto" id="mySmallModalLabel">Выйти из системы?</h4>
            </div>
            <div class="modal-body text-center" id='modal__logout__body'>
                <button id="logout_btn" type="submit" class="btn btn-warning">Выйти</button>
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>
<!--googleon: index -->
<!--/noindex-->
