
<ul class="nav nav-tabs mt-4">
    <li class="nav-item">
        <a class="nav-link active" href="#">
            Обзор <!-- overview  -->
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">
            Вопросы
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">
            Правки
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">
            Подписки
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">
            Подписчики
        </a>
    </li>
</ul>
