<!-- ask_question -->
<div class="d-flex align-items-center box p-2 my-4">
    <div class="w-2">
        <a href="<?= $this->authUser->getURL($this->lang) ?>">
            <img class="wh-2 rounded" src="<?= $this->authUser->getAvatarSmallURL() ?>" alt="<?= $this->authUser->name ?>">
        </a>
    </div>
    <div class="ml-3">
        <a class="text-secondary text-decoration-none" href="#" data-toggle="modal" data-target="#modal_ask">
            У вас есть вопрос?
        </a>
    </div>
    <div class="ml-auto">
        <button class="btn btn-sm btn-outline-success" role="button" data-toggle="modal" data-target="#modal_ask">
            Задать вопрос
        </button>

    </div>
</div>
<!-- / ask_question -->