
<!-- ask_question -->
<div class="d-flex align-items-center box p-2 my-4">
    <div class="width-4">
        <a href="<?= $this->authUser->getURL($this->lang) ?>">
            <img class="size-4 rounded" src="<?= $this->authUser->getAvatarSmallURL() ?>" alt="<?= $this->authUser->getName() ?>">
        </a>
    </div>
    <div class="ml-3">
        <a class="color-gray-600 no-underline-hover" href="#" data-toggle="modal" data-target="#modal_ask">
            У вас есть вопрос?
        </a>
    </div>
    <div class="ml-auto">
        <button class="btn btn-sm btn-outline-success" role="button" data-toggle="modal" data-target="#modal_ask">
            Задать вопрос
        </button>

    </div>
</div>
<!-- / ask_question -->
