<div class="mb-4">

    <!-- avatar + name + username -->
    <div class="media position-relative mb-4">
        <img src="<?= $this->user->getAvatarURLMedium() ?>" class="wh-48px rounded mr-3" alt="<?= $this->user->name ?>">
        <div class="media-body">
            <h1 class="mb-0"><?= $this->user->name ?></h1>
            <div class="text-black small">
                @<?= $this->user->username ?>
            </div>
        </div>
    </div>
    <!-- / avatar + name + username -->

    <?php if ($this->user->signature) : ?>
        <div class="text-muted">
            <?= $this->user->signature ?>
        </div>
    <?php endif; ?>

    <?php if ($this->user->site) : ?>
        <div class="mt-2">
            <i class="material-icons md-18 text-secondary">link</i>
            <a target="_blank" rel="nofollow" href="<?= $this->user->site ?>">
                <?= parse_url($this->user->site, PHP_URL_HOST) ?>
            </a>
        </div>
    <?php endif; ?>

</div>