<ul class="nav nav-tabs pl-3 my-3">
    <li class="nav-item">
        <a class="nav-link active" href="#">
            <?= __('page_user.nav.revisions') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">
            <?= __('page_user.nav.questions') ?>
        </a>
    </li>
    <li class="nav-item d-none d-md-inline-block">
        <a class="nav-link disabled" href="#">
            <?= __('page_user.nav.followed') ?>
        </a>
    </li>
    <li class="nav-item d-none d-md-inline-block">
        <a class="nav-link disabled" href="#">
            <?= __('page_user.nav.followers') ?>
        </a>
    </li>
</ul>