
<!-- nav -->
<ul class="nav nav-tabs my-4">
    <li class="nav-item">
        <a class="nav-link active" href="<?= Users_URL_Helper::getNewestURL($this->lang) ?>">
            <?= $this->translator->get('Newest') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">
            <?= $this->translator->get('Popular') ?>
        </a>
    </li>
</ul>
<!-- / nav -->
