
<?php if (count($this->users)): ?>
   
    <?php foreach ($this->users as $user): ?>
	<div class="media">
		<a class="d-block wh-4 mr-3 mb-3" href="<?= $user->getURL($this->lang) ?>">
            <img class="wh-4 mr-3 rounded" src="<?= $user->getAvatarSmallURL() ?>">
        </a>
  		<div class="media-body">
			<a class="h5 color-secondary-dark-4 text-decoration-none" href="<?= $user->getURL($this->lang) ?>">
				<?= $user->name ?>
			</a>
            
			<div class="semi-small color-secondary-dark-1">
				<?php if ($user->signature): ?>
					<?= $user->signature ?>
				<?php endif; ?>

				<?php if ($user->signature && $user->site): ?>
					<span class="font-weight-bold mx-1 color-secondary-dark-3">&middot;</span>
				<?php endif; ?>

				<?php if ($user->site): ?>
					<a href="<?= $user->site ?>">
						<?= parse_url($user->site, PHP_URL_HOST) ?>
					</a>
				<?php endif; ?>
			</div>
		</div>
	</div>
    <?php endforeach; ?>
    
<?php endif; ?>
