<?php if (count($this->users)) : ?>

<?php foreach ($this->users as $user) : ?>
<div class="media mb-4">
	<a class="d-block wh-3 mr-3" href="<?= $user->get_URL($this->lang) ?>">
		<img class="wh-3 mr-3 rounded" src="<?= $user->get_avatar_URL_small() ?>">
	</a>
	<div class="media-body">
		<a class="h5 text-dark text-decoration-none" href="<?= $user->get_URL($this->lang) ?>">
			<?= $user->name ?>
		</a>

		<div class="semi-small text-secondary">
			<?php if ($user->signature) : ?>
			<?= $user->signature ?>
			<?php else : ?>
			@<?= $user->username ?>
			<?php endif; ?>

			<?php if ($user->site) : ?>
			<span class="font-weight-bold mx-1 text-dark">&middot;</span>
			<a href="<?= $user->site ?>">
				<?= parse_url($user->site, PHP_URL_HOST) ?>
			</a>
			<?php endif; ?>
		</div>
	</div>
</div>
<?php endforeach; ?>

<?php endif; ?>