<!DOCTYPE html>
<html lang="<?= $this->lang ?>">

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body>

    <?php require TEMPLATE_PATH . '/_common/navbar.phtml'; ?>

    <div class="container mt-4">
        <div class="row">

            <div class="d-none d-lg-block col-12 col-lg-2">
                <?php require TEMPLATE_PATH . '/_common/left/sections.phtml'; ?>
            </div>

            <!-- main_column -->
            <div class="col-12 col-lg-7">
                <div class="border rounded bg-white p-3 mb-4">
                    <p class="lead text-muted mb-1">500</p>
                    <h1 class="mt-0">
                        <?= $this->errorTitle ?>
                    </h1>
                    <div class="my-4 text-muted">
                        <?= $this->errorDescription ?>
                    </div>
                    <div class="mt-5">Go to <a href="<?= SITE_URL ?>">main page</a></div>
                </div>
            </div>
            <!-- / main_column -->

            <div class="d-none d-md-block col-lg-3">
                <!-- x -->
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH . '/_common/modals.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>

</body>

</html>