<!DOCTYPE html>
<html lang="<?= $this->lang ?>">

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body>

    <?php require TEMPLATE_PATH . '/_common/navbar.phtml'; ?>

    <div class="container mt-4">
        <div class="row">

            <div class="d-none d-lg-block col-12 col-lg-2">
                <?php require TEMPLATE_PATH . '/_common/left/sections.phtml'; ?>
            </div>

            <!-- main_column -->
            <div class="col-12 col-lg-7">
                <?php require __DIR__ . '/about_sandbox.phtml'; ?>

                <?php if (count($this->questions)) : ?>
                    <?php foreach ($this->questions as $question) : ?>
                        <?php if (isset($this->redirects[$question->id])) : ?>
                            <?php require __DIR__ . '/item__redirect.phtml'; ?>
                        <?php else : ?>
                            <?php require __DIR__ . '/item__question_without_answer.phtml'; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php require __DIR__ . '/next_page.phtml'; ?>
            </div>
            <!-- / main_column -->

            <div class="d-none d-md-block col-lg-3">
                <?php require __DIR__ . '/joun_the_community.phtml' ?>
                <?php require __DIR__ . '/filter.phtml' ?>
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH . '/_common/modals.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>

</body>

</html>