<!-- about_sandbox -->
<div class="alert alert-warning p-3" role="alert">
	<h4 class="alert-heading mb-3">
		<?= __('page_sandbox.about_block.title') ?>
	</h4>

	<p class="semi-small mb-2"><?= __('page_sandbox.about_block.msg_1') ?></p>
	<p class="semi-small mb-2"><?= __('page_sandbox.about_block.msg_2') ?></p>

	<?php if (isset($this->questionsCount)) : ?>
		<hr>
		<p class="semi-small mb-0">
			<?= __('page_sandbox.about_block.now_in_the_sandbox') ?>
			&middot;
			<?= $this->questionsCount ?>
		</p>
	<?php endif; ?>

</div>
<!-- / about_sandbox -->