<!-- sandbox_nav -->

<nav class="ml-2 my-4">
    <ul class="list-unstyled">
        <li>
            <a href="<?= \Helper\URL\Sandbox::get_without_answers_URL($this->lang) ?>" class="<?= ($this->list == 'without-answers') ? 'active' : '' ?>">
                <?= $this->translator->get('sandbox', 'questions_without_answers') ?>
            </a>
        </li>
        <li>
            <a href="<?= \Helper\URL\Sandbox::get_without_categories_URL($this->lang) ?>" class="<?= ($this->list == 'without_categories') ? 'active' : '' ?>">
                <?= $this->translator->get('sandbox', 'without_categories') ?>
            </a>
        </li>
        <li>
            <a href="<?= \Helper\URL\Sandbox::get_all_URL($this->lang) ?>" class="<?= ($this->list == 'newest') ? 'active' : '' ?>">
                <?= $this->translator->get('sandbox', 'all_questions') ?>
            </a>
        </li>
    </ul>
</nav>

<!-- / sandbox_nav -->