<!-- filter -->
<nav class="mt-2 mb-4">
    <div class="semi-small font-weight-bold text-uppercase text-primary mb-3">
        <?= __('page_sandbox.filters.title') ?>
    </div>

    <ul class="list-unstyled semi-small">
        <li class="my-2">
            <a class="text-dark text-decoration-none <?= ($this->list == 'without-answers') ? 'font-weight-bold' : '' ?>" href="<?= \Helper\URL\Sandbox::getWithoutAnswersURL($this->lang) ?>">
                <?= __('page_sandbox.questions_without_answers') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none <?= ($this->list == 'without_categories') ? 'font-weight-bold' : '' ?>" href="<?= \Helper\URL\Sandbox::getWithoutCategoriesURL($this->lang) ?>">
                <?= __('page_sandbox.without_categories') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none <?= ($this->list == 'newest') ? 'font-weight-bold' : '' ?>" href="<?= \Helper\URL\Sandbox::getAllURL($this->lang) ?>">
                <?= __('page_sandbox.all_questions') ?>
            </a>
        </li>
    </ul>
</nav>
<!-- / filter -->