<!-- question item -->
<div class="border rounded bg-white p-3 my-4">

    <div class="mb-1">
        <a class="font-size-140 line-height-13 text-dark mb-2 font-weight-bold text-decoration-none" href="<?= $question->get_URL($this->lang) ?>">
            <?= $question->title ?>
        </a>
    </div>
    <div class="small text-black-50">
        <?= \Humanizer\DateTime::humanize_timestamp($this->lang, $question->answer->updatedAt) ?>
    </div>

    <!-- actions -->
    <div class="mt-2">

        <!-- edit answer -->
        <?php if (strlen($question->answer->text) == 0) : ?>
            <a class="btn btn-sm btn-outline-gray mt-2 mr-2" rel="nofollow" href="<?= $question->get_edit_URL($this->lang) ?>">
                <i class="material-icons md-14">edit</i>
                <?= $this->translator->get('sandbox', 'btn_write_first_answer') ?>
            </a>
        <?php endif; ?>
        <!-- / edit answer -->

        <!-- add categories -->
        <?php if ($question->categoriesCount == 0) : ?>
            <a class="btn btn-sm btn-outline-gray mt-2 mr-2" rel="nofollow" href="<?= $question->get_update_categories_URL($this->lang) ?>">
                <i class="material-icons md-14">bubble_chart</i>
                <?= $this->translator->get('sandbox', 'btn_add_categories') ?>
            </a>
        <?php endif; ?>
        <!-- / add categories -->

    </div>
    <!-- / actions -->
</div>

<!-- / question item -->