
<?php if (count($this->questions)): ?>
    <?php foreach ($this->questions as $question): ?>
        <?php
        if (isset($this->redirects[$question->id])) {
            require __DIR__.'/main/item__redirect.phtml';
            continue;
        } else {
            require __DIR__.'/main/item__question_without_answer.phtml';
            continue;
        }
        ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if (isset($this->nextPageURL)): ?>
    <div class="my-5">
        <a class="btn btn-primary" href="<?= $this->nextPageURL ?>">Еще вопросы</a>
    </div>
<?php endif; ?>
