
<?php require_once TEMPLATE_PATH.'/sandbox/main/nav.phtml' ?>

<?php if (count($this->questions)): ?>
    <?php foreach ($this->questions as $question): ?>
        <?php
        if (isset($this->redirects[$question->id])) {
            require TEMPLATE_PATH.'/sandbox/main/redirect.phtml';
            continue;
        } else {
            require TEMPLATE_PATH.'/_common/item/question_with_answer.phtml';
            continue;
        }
        ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if (isset($this->nextPageURL)): ?>
    <div class="my-5">
        <a class="btn btn-block btn-primary" href="<?= $this->nextPageURL ?>">Еще вопросы</a>
    </div>
<?php endif; ?>
