<!DOCTYPE html>
<html lang="<?= $this->lang ?>" <?= isset($this->htmlAttr) ? $this->htmlAttr : '' ?>>

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body <?= isset($this->bodyAttr) ? ' ' . $this->bodyAttr : '' ?>>

    <?php require_once TEMPLATE_PATH . '/_common/navbar.phtml'; ?>

    <div class="container mt-4">
        <div class="row">
            <div class="d-none d-lg-block col-12 col-lg-2">
                <?php require_once TEMPLATE_PATH . '/_common/left/sections.phtml'; ?>

            </div>

            <!-- main_column -->
            <div class="col-12 col-lg-7">
                <?php require_once TEMPLATE_PATH . '/question/main/redirected.phtml'; ?>

                <div class="border rounded bg-white p-3">
                    <?php require_once __DIR__ . '/main/categories_top.phtml'; ?>
                    <?php require_once __DIR__ . '/main/title.phtml'; ?>
                    <?php require_once __DIR__ . '/actions_top.phtml' ?>
                    <?php require_once __DIR__ . '/main/image.phtml' ?>

                    <?php require_once TEMPLATE_PATH . '/question/main/lure_be_first_contributor.phtml' ?>
                    <?php require_once TEMPLATE_PATH . '/question/main/answer.phtml' ?>
                </div>

                <?php require_once TEMPLATE_PATH . '/question/main/categories.phtml' ?>
                <?php require_once TEMPLATE_PATH . '/question/main/subscribe.phtml'; ?>
                <?php require_once TEMPLATE_PATH . '/question/main/contributors_full.phtml'; ?>
                <?php require_once TEMPLATE_PATH . '/question/main/related_questions.phtml'; ?>
            </div>
            <!-- / main_column -->

            <div class="d-none d-md-block col-lg-3">

                <?php if (!$this->authUser) : ?>
                    <?php require_once TEMPLATE_PATH . '/_common/right/about_answeropedia.phtml'; ?>
                <?php endif; ?>

                <?php require_once __DIR__ . '/right/contributors_top.phtml'; ?>
                <?php require_once __DIR__ . '/right/actions.phtml'; ?>
                <?php require_once __DIR__ . '/right/info_about_question.phtml'; ?>
            </div>
        </div>
    </div>

    <?php require TEMPLATE_PATH . '/_common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH . '/_common/modals.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>

</body>

</html>