<?php if (!$this->authUser) : ?>
	<!-- about_answeropedia -->
	<div class="border rounded bg-white p-3 my-4" id="contributors_full_list">

		<div class="semi-small font-weight-bold text-uppercase text-primary mb-3">
			<?= $this->translator->get('common_blocks', 'about_answeropedia', 'title') ?>
		</div>

		<p class="text-black-50 semi-small">
			<?= $this->translator->get('common_blocks', 'about_answeropedia', 'text') ?>
		</p>

		<button role="button" data-toggle="modal" data-target="#modal_signup" class="btn btn-danger btn-block mt-4">
			<?= $this->translator->get('common_blocks', 'about_answeropedia', 'btn_action') ?>
		</button>
	</div>
	<!-- / about_answeropedia -->
<?php endif; ?>