<!-- actions_top -->
<div class="mt-2 mb-3">

    <!-- edit answer -->
    <?php if ($this->authUser) : ?>
        <a class="btn btn-sm btn-outline-gray my-2 mr-2" href="<?= $this->question->get_edit_URL($this->lang) ?>">
            <i class="material-icons md-18">edit</i>
            <?= __('page_question.actions_top.edit_answer') ?>
        </a>
    <?php else : ?>
        <a class="btn btn-sm btn-outline-gray my-2 mr-2" href="#" data-toggle="modal" data-target="#modal_lure__edit_answer">
            <i class="material-icons md-18">edit</i>
            <?= __('page_question.actions_top.edit_answer') ?>
        </a>
        <?php require_once TEMPLATE_PATH . '/_modal/question/_lure/edit_answer.phtml' ?>
    <?php endif; ?>
    <!-- / edit answer -->

    <!-- follow_btn -->
    <?php if ($this->authUser) : ?>
        <button class="btn btn-sm follow_question_button my-2 mr-2 <?= $this->followed ? 'followed btn-success' : 'btn-outline-gray'; ?>" data-question-id="<?= $this->question->id ?>" data-follow-title="<?= $this->translator->get('btn', 'follow') ?>" data-followed-title="<?= $this->translator->get('btn', 'followed') ?>" data-unfollow-title="<?= $this->translator->get('btn', 'unfollow') ?>" type="button">
            <?= $this->followed ? $this->translator->get('btn', 'followed') : $this->translator->get('btn', 'follow'); ?>
        </button>
    <?php else : ?>
        <button type="button" class="btn btn-sm btn-outline-gray my-2 mr-2" data-toggle="modal" data-target="#modal__follow_question_lure">
            <?= $this->translator->get('btn', 'follow'); ?>
        </button>
        <?php require_once TEMPLATE_PATH . '/_modal/question/_lure/follow_question.phtml' ?>
    <?php endif; ?>
    <!-- / follow_btn -->

    <?php if (mb_strlen($this->question->answer->text) > 0) : ?>
        <!-- btn history -->
        <a class="d-inline-block semi-small text-black-50 my-2 ml-2" href="<?= $this->question->get_history_URL($this->lang) ?>">
            <?= __('page_question.actions_top.history') ?>
        </a>
        <!-- btn history -->
    <?php endif; ?>

    <!-- more dropdown -->
    <div class="dropdown d-inline">
        <a href="#" class="text-black-50 my-2 ml-3 float-lg-right" id="dropdown-menu-more" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons md-18">more_horiz</i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-menu-more">

            <?php if ($this->authUser) : ?>
                <a href="#" class="dropdown-item" data-toggle="modal" data-target="#modal_upload_image">
                    <?= ($this->question->imageBaseName) ? __('page_question.update_picture') : __('page_question.add_picture') ?>
                </a>
            <?php endif; ?>

            <?php if ($this->authUser) : ?>
                <a href="#" class="dropdown-item" data-toggle="modal" data-target="#modal_rename_question">
                    <?= __('page_question.rename_question') ?>
                </a>
            <?php endif; ?>

            <a href="#" class="dropdown-item disabled" rel="nofollow">
                <?= __('page_question.report') ?>
            </a>

            <div class="dropdown-divider"></div>

            <a class="dropdown-item" target="_blank" href="<?= $this->question->get_discussion_URL($this->lang) ?>">
                <?= __('page_question.actions_top.discuss_a_question') ?>
            </a>

            <a rel="nofollow" class="dropdown-item" target="_blank" href="<?= \Helper\URL\DDG::get_search_URL($this->question->title) ?>">
                <?= __('page_question.search_in_ddg') ?>
            </a>

        </div>
    </div>
    <!-- / more dropdown -->

    <!-- share dropdown -->
    <div class="dropdown d-none d-lg-inline">
        <a href="#" class="text-black-50 my-2 float-right" id="dropdown-menu-share" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons md-18">share</i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-menu-share">
            <p class="dropdown-header"><?= __('page_question.actions_top.share__title') ?></p>

            <script src="https://yastatic.net/share2/share.js"></script>


            <div id="my-share" class="ya-share2" style="min-height: 24px;" data-services="facebook,twitter,vkontakte,pinterest,digg,reddit,pocket,delicious"></div>

            <script>
                var share = Ya.share2('my-share', {
                    content: {
                        url: '<?= $this->share_link['url'] ?>',
                        title: '<?= $this->share_link['title'] ?>',
                        description: '<?= $this->share_link['description'] ?>',
                        image: '<?= $this->share_link['image'] ?>'
                    },
                    theme: {
                        lang: 'en',
                        size: 'm',
                        bare: false,
                        copy: 'last',
                        direction: 'vertical'
                    }
                });
            </script>

            <style>
                .ya-share2__link {
                    margin-top: 8px;
                    padding-left: 24px;
                }
            </style>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item semi-small" href="#">
                <?= __('page_question.actions_top.share__copy_link') ?>
            </a>
        </div>
    </div>
    <!-- / share dropdown -->

</div>
<!-- / actions_top -->