<?php if (isset($this->question->answer) && $this->question->answer->text) : ?>
    <div class="mt-4">
        <?= $this->formattedAnswerText ?>
    </div>
<?php endif; ?>

<div class="mt-2 pt-3 border-top text-secondary">

    <!-- edit answer -->
    <?php if ($this->authUser) : ?>
        <a class="btn btn-sm btn-outline-gray mr-2" href="<?= $this->question->get_edit_URL($this->lang) ?>">
            <i class="material-icons md-14">edit</i>
            <?= $this->translator->get('question', 'actions_top', 'edit_answer') ?>
        </a>
    <?php else : ?>
        <a class="btn btn-sm btn-outline-gray mr-2" href="#" data-toggle="modal" data-target="#modal_lure__edit_answer">
            <i class="material-icons md-14">edit</i>
            <?= $this->translator->get('question', 'actions_top', 'edit_answer') ?>
        </a>
        <?php require_once TEMPLATE_PATH . '/_modal/question/_lure/edit_answer.phtml' ?>
    <?php endif; ?>
    <!-- / edit answer -->

    <div class="btn-group btn-group-sm mr-3" role="group" aria-label="goo-bad-answer">
        <button type="button" class="btn btn-outline-gray">
            <i class="material-icons md-14">thumb_up</i>
            <?= $this->translator->get('main', 'item__top_question', 'upvote') ?>
        </button>
        <button type="button" class="btn btn-outline-gray text-black-50">
            <?= $this->translator->get('main', 'item__top_question', 'downvote') ?>
        </button>
    </div>

    <!-- updated_at -->
    <?php if (strlen($this->question->answer->text)) : ?>
        <span class="semi-small text-black-50" title="<?= $this->translator->get('Minutes to read') ?>">
            <?= $this->translator->get('question', 'answer_updated') . ': ' . \Humanizer\DateTime::humanize_timestamp($this->lang, $this->question->answer->updatedAt) ?>
        </span>
    <?php endif; ?>
    <!-- / updated_at -->

</div>