<!-- categories -->
<div class="border rounded bg-white p-3 my-4" id="question_categories_list">
	<div class="semi-small font-weight-bold text-uppercase text-black mb-3">
		<?= $this->translator->get('question', 'block__categories', 'title') ?>
	</div>

	<?php if (count($this->categories)) : ?>

		<?php foreach ($this->categories as $category) : ?>
			<a class="d-inline-block link-dashed text-secondary line-height-12 text-decoration-none mb-2 mr-2" href="<?= $category->get_URL($this->lang) ?>"><?= $category->title ?></a>
		<?php endforeach; ?>

		<?php if ($this->authUser) : ?>
			<div class="mt-2">
				<a class="btn btn-sm btn-outline-gray" href="<?= $this->question->get_update_categories_URL($this->lang) ?>" rel="nofollow">
					<i class="material-icons md-14">edit</i>&nbsp;<?= $this->translator->get('question', 'block__categories', 'categories_change') ?>
				</a>
			</div>
		<?php endif; ?>

	<?php else : ?>

		<p><?= $this->translator->get('question', 'block__categories', 'no_categories') ?></p>

		<?php if ($this->authUser) : ?>
			<a class="btn btn-sm btn-outline-gray" href="<?= $this->question->get_update_categories_URL($this->lang) ?>">
				<i class="material-icons md-18">add</i>
				<?= $this->translator->get('question', 'block__categories', 'categories_add') ?>
			</a>
		<?php else : ?>
			<a class="btn btn-sm btn-outline-gray" href="#">
				<i class="material-icons md-18">add</i>
				<?= $this->translator->get('question', 'block__categories', 'login_to_add_categories') ?>
			</a>
		<?php endif; ?>

	<?php endif; ?>
</div>
<!-- / categories -->