<?php if (count($this->contributors)) : ?>

	<div class="border rounded bg-white p-3 my-4" id="contributors_full_list">
		<div class="semi-small font-weight-bold text-uppercase text-black mb-3">
			<?= __('page_question.answer_contributors') ?>
		</div>

		<?php foreach ($this->contributors as $contributor) : ?>
			<a class="d-inline-block wh-48px mr-2 mb-2" href="<?= $contributor->get_URL($this->lang) ?>">
				<img class="wh-48px rounded-circle" src="<?= $contributor->get_avatar_URL_medium() ?>" alt="<?= $contributor->name ?>">
			</a>
		<?php endforeach; ?>

		<!-- <div class="small text-muted mt-3">
			<?= __('page_question.total_contributors') ?>: <?= count($this->contributors) ?>
		</div> -->

		<div class="mt-3">
			<div class="semi-small text-black-50">
				<?= __('page_question.block__contributors.msg') ?>
			</div>
			<ul class="list-inline semi-small mt-2 mb-0">
				<li class="list-inline-item">
					<a class="text-dark" href="<?= $this->question->get_edit_URL($this->lang) ?>">
						<?= __('page_question.block__contributors.link__edit_answer') ?>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="text-dark" href="<?= $this->question->get_update_categories_URL($this->lang) ?>">
						<?= __('page_question.block__contributors.link__change_categories') ?>
					</a>
				</li>
				<li class="list-inline-item">
					<a href="#" target="_blank">
						<?= __('page_question.block__contributors.link__what_is_a_contribution') ?>
					</a>
				</li>
			</ul>
		</div>

	</div>
<?php endif; ?>