<?php if (count($this->contributors_top)) : ?>
    <!--noindex-->
    <!--googleoff: index-->

    <!-- top contributors @ sidebar -->
    <div class="mb-5">

        <div class="semi-small font-weight-bold text-uppercase text-primary mt-2 mb-3">
            <?= __('page_question.top_contributors') ?>
        </div>

        <?php foreach ($this->contributors_top as $contributor) : ?>
            <div class="media position-relative mb-4">
                <a class="wh-40px mt-1 mr-3 rounded" href="<?= $contributor->get_URL($this->lang) ?>">
                    <img src="<?= $contributor->get_avatar_URL_medium() ?>" class="wh-40px rounded-circle" alt="<?= $contributor->name ?>">
                </a>
                <div class="media-body">
                    <a class="mt-0 mr-2 font-weight-bold text-dark text-decoration-none" href="<?= $contributor->get_URL($this->lang) ?>">
                        <?= $contributor->name ?>
                    </a>

                    <p class="small text-black-50 mb-0">
                        <?= $contributor->signature ? $contributor->get_short_signature() : $contributor->username ?>
                        <?php if ($contributor->site) : ?>
                            <a href="<?= $contributor->site ?>">
                                <?= parse_url($contributor->site, PHP_URL_HOST) ?>
                            </a>
                        <?php endif; ?>
                    </p>
                </div>
            </div>
        <?php endforeach; ?>

    </div>
    <!-- / top contributors @ sidebar -->

    <!-- <a class="float-right text-black-50 text-decoration-none" data-scroll href="#contributors_full_list">
        All
    </a> -->

    <!--googleon: index -->
    <!--/noindex-->
<?php endif; ?>