<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/common/navbar.phtml'; ?>

    <div class="container-fluid">
        <div class="row my-5">

            <div class="col-12 col-md-8 mx-auto">

                <!-- <div class="text-center mt-4">
                    <ul class="list-steps">
                        <li class="active">1</li>
                        <li>2</li>
                        <li>3</li>
                    </ul>
                </div> -->

                <h1 class="mb-4">
                    Новый вопрос
                </h1>

                
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH.'/common/js_bottom.phtml'; ?>
</body>
</html>
