
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-2">
            <!--  -->
        </div>

        <div class="col-sm-12 col-md-9 col-lg-7">

            <h1 class="h3 mt-5 mb-3">Создание вопроса «<?= $this->questionTitle ?>»</h1>

            <p>Вы перешли по ссылке на страницу, которой пока не существует. Чтобы её создать, наберите текст в окне, расположенном ниже (подробнее см. справочную страницу). Если вы оказались здесь по ошибке, просто нажмите кнопку назад своего браузера.</p>

            <form id="form__question_create" class="mt-4" data-question-title="<?= $this->questionTitle ?>">
                <div class="form-group">
                    <textarea id="form__question_create__answer_text" name="answer_text" class="form-control" rows="10"></textarea>
                </div>
                <div class="form-group mt-4">
                    <button type="submit" id="form__question_create__submit_btn" class="btn btn-primary">
                        <?= $this->l->t('Создать вопрос') ?>
                    </button>
                </div>
            </form>

        </div>

        <div class="col-sm-12 col-md-9 offset-md-3 col-lg-3 offset-lg-0">
            <!--  -->
        </div>

    </div>

</div>
