<?php if (isset($this->question->answer) && !$this->question->answer->text) : ?>
    <?php if ($this->authUser) : ?>

        <!-- lure be_first_contributor -->
        <div class="alert alert-primary py-3 my-4" role="alert">
            <h4 class="alert-heading"><?= __('page_question.lure_be_first_contributor.title') ?></h4>
            <p><?= __('page_question.lure_be_first_contributor.message') ?></p>
            <hr>
            <p class="mb-0">
                <a class="btn btn-primary" href="<?= $this->question->getEditURL($this->lang) ?>">
                    <?= __('page_question.lure_be_first_contributor.btn_write') ?>
                </a>
            </p>
        </div>
        <!-- / lure be_first_contributor -->

    <?php else : ?>
        <!--noindex-->
        <!--googleoff: index-->

        <!-- lure be_first_contributor -->
        <div class="d-flex border-top px-2 px-sm-3 py-2 py-sm-3 mt-2 mb-4">
            <div class="mr-3 d-none d-sm-block">
                <p class="h1">
                    <i class="material-icons md-24 color-danger">grade</i>
                </p>
            </div>
            <div class="width-full">
                <div class="text-dark font-weight-bold mb-2">
                    <?= __('Be the first author') ?>!
                </div>
                <div class="small text-muted mb-3">
                    <?= __('Still no one tried to write an answer to this question. Be the first if the category of the question is close to you!') ?>
                </div>
                <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#first_answer__signup">
                    <?= __('Write first answer') ?>
                </button>
            </div>
        </div>
        <!-- / lure be_first_contributor -->

        <?php require_once TEMPLATE_PATH . '/_modal/question/_lure/first_answer_signup.phtml' ?>

        <!--googleon: index -->
        <!--/noindex-->
    <?php endif; ?>
<?php endif; ?>