
<?php require_once TEMPLATE_PATH . '/question/main/redirected.phtml'; ?>
<?php require_once TEMPLATE_PATH . '/question/main/categories_top.phtml'; ?>
<?php require_once TEMPLATE_PATH . '/question/main/title.phtml'; ?>
<?php require_once TEMPLATE_PATH . '/question/main/actions_top.phtml' ?>
<?php require_once TEMPLATE_PATH . '/question/main/lure_be_first_contributor.phtml' ?>
<?php require_once TEMPLATE_PATH . '/question/main/answer.phtml' ?>
<?php require_once TEMPLATE_PATH . '/question/main/categories.phtml' ?>
<?php require_once TEMPLATE_PATH . '/question/main/subscribe.phtml'; ?>
<?php require_once TEMPLATE_PATH . '/question/main/contributors_full.phtml'; ?>
<?php require_once TEMPLATE_PATH . '/question/main/related_questions.phtml'; ?>
<?php require_once TEMPLATE_PATH . '/question/main/share.phtml' ?>
