<?php if (isset($this->related_questions) && count($this->related_questions)) : ?>
	<!-- related questions -->
	<div class="border rounded bg-white p-3 my-4">
		<div class="semi-small font-weight-bold text-uppercase text-black mb-3">
			<?= __('page_question.block__related_questions', 'title') ?>
		</div>

		<?php foreach ($this->related_questions as $question) : ?>
			<div class="my-2">
				<a class="semi-small text-decoration-none" href="<?= $question->get_URL($this->lang) ?>">
					<?= $question->title ?>
				</a>
				<!-- <div class="small text-secondary">
					<?= __('page_question.answer_updated') ?> <?= \Humanizer\DateTime::humanize_timestamp($this->lang, $question->answer->updatedAt) ?>

					<?php if (strlen($question->answer->text) == 0) : ?>
						<span class="mx-1 text-dark font-weight-bold">&middot;</span>
						<a rel="nofollow" href="<?= $question->get_edit_URL($this->lang) ?>">
							<?= $this->translator->get('Write first answer') ?>
						</a>
					<?php endif; ?>
				</div> -->
			</div>
		<?php endforeach; ?>

		<div class="mt-3">
			<!-- change related answers -->
			<a class="btn btn-sm btn-outline-gray mr-2" href="#">
				<i class="material-icons md-14">edit</i>
				<?= __('page_question.btn__change_related_answers') ?>
			</a>
			<!-- / change related answers -->
		</div>

	</div>
	<!-- / related questions -->
<?php endif; ?>