<?php if (!$this->authUser): ?>
    <?php require_once TEMPLATE_PATH.'/_common/right/about_answeropedia.phtml'; ?>
<?php endif; ?>

<?php require_once TEMPLATE_PATH.'/question/right/image.phtml' ?>
<?php require_once TEMPLATE_PATH.'/question/right/contributors_top.phtml'; ?>
<?php require_once TEMPLATE_PATH.'/question/right/actions.phtml'; ?>
<?php require_once TEMPLATE_PATH.'/question/right/info_about_question.phtml'; ?>