<!DOCTYPE html>
<html lang="<?= $this->lang ?>" itemscope itemtype="http://schema.org/QAPage">
<head>
	<?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>
<body itemscope itemtype="http://schema.org/Question">

	<?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

	<div class="container-fluid">
		<div class="row flex-xl-nowrap">
			
			<div class="col-12 col-md-3 col-xl-2 bd-sidebar">
				<?php require_once TEMPLATE_PATH.'/question/block/sidebar/sidebar.phtml'; ?>
			</div>
			
			<!-- right_column -->
			<div class="d-none d-xl-block col-xl-2 bd-toc">
				<?php require_once TEMPLATE_PATH.'/question/block/sidebar/about_octo.phtml'; ?>
				<?php require_once TEMPLATE_PATH.'/question/block/sidebar/contributors_top.phtml'; ?>
				<?php require_once TEMPLATE_PATH.'/question/block/lure/add_image.phtml'; ?>

				<ul class="section-nav">
				<li class="toc-entry toc-h2"><a href="#examples">Examples</a></li>
				<li class="toc-entry toc-h2"><a href="#button-tags">Button tags</a></li>
				<li class="toc-entry toc-h2"><a href="#outline-buttons">Outline buttons</a></li>
				<li class="toc-entry toc-h2"><a href="#sizes">Sizes</a></li>
				<li class="toc-entry toc-h2"><a href="#active-state">                    
					<i class="fas fa-edit mr-1"></i>
					Active state</a></li>
				<li class="toc-entry toc-h2"><a href="#disabled-state">Disabled state</a></li>
				<li class="toc-entry toc-h2"><a href="#button-plugin">Button plugin</a>
				<ul>
				<li class="toc-entry toc-h3"><a href="#toggle-states">Toggle states</a></li>
				<li class="toc-entry toc-h3"><a href="#checkbox-and-radio-buttons">Checkbox and radio buttons</a></li>
				<li class="toc-entry toc-h3"><a href="#methods">Methods</a></li>
				</ul>
				</li>
				</ul>

				<?php require_once TEMPLATE_PATH.'/question/block/col_right/info_about_question.phtml'; ?>

			</div>
			<!-- / right_column -->

			<!-- main_column -->
			<main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 bd-content">
				<?php require_once TEMPLATE_PATH.'/question/block/header/topics.phtml'; ?>
				<?php require_once TEMPLATE_PATH.'/question/block/header/title.phtml'; ?>

				<?php require_once TEMPLATE_PATH.'/question/block/image.phtml' ?>

				<?php require_once TEMPLATE_PATH.'/question/block/actions/top.phtml' ?>

				<?php require_once TEMPLATE_PATH.'/question/block/lure/be_first_contributor.phtml' ?>
				<?php require_once TEMPLATE_PATH.'/question/show/answer_lead.phtml' ?>
				<?php require_once TEMPLATE_PATH.'/question/show/answer.phtml' ?>
				<?php require_once TEMPLATE_PATH.'/question/block/actions/bottom.phtml' ?>

				<?php require_once TEMPLATE_PATH.'/question/block/topics.phtml' ?>

				<?php require_once TEMPLATE_PATH.'/question/block/subscribe.phtml'; ?>

				<?php require_once TEMPLATE_PATH.'/question/block/contributors_full.phtml'; ?>

				<?php require_once TEMPLATE_PATH.'/question/block/related_questions.phtml'; ?>

				<?php require_once TEMPLATE_PATH.'/question/block/share.phtml' ?>

				<?php require_once TEMPLATE_PATH.'/question/block/interesting_questions.phtml' ?>
				<?php require TEMPLATE_PATH.'/_common/footer.phtml'; ?>

			</main>
			<!-- / main_column -->
			
		</div>
	</div>

	<!-- Modal components -->
	<?php if ($this->authUser): ?>
		<?php require_once TEMPLATE_PATH.'/question/modal/rename.phtml' ?>
		<?php require_once TEMPLATE_PATH.'/question/modal/upload_image.phtml' ?>
	<?php else: ?>
		<!--  -->
	<?php endif; ?>

	<?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
