<!DOCTYPE html>
<html lang="<?= $this->lang ?>" itemscope itemtype="http://schema.org/QAPage">
<head>
    <?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>
<body itemscope itemtype="http://schema.org/Question">

    <?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 col-xl-10">
                <?php require_once TEMPLATE_PATH.'/question/block/header/topics.phtml'; ?>
                <?php require_once TEMPLATE_PATH.'/question/block/header/title.phtml'; ?>
                <?php require_once TEMPLATE_PATH.'/question/block/header/info.phtml'; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8 col-xl-8">
                <?php require_once TEMPLATE_PATH.'/question/block/image.phtml' ?>

                <?php require_once TEMPLATE_PATH.'/question/block/actions.phtml' ?>

                <?php require_once TEMPLATE_PATH.'/question/block/lure/be_first_contributor.phtml' ?>
                <?php require_once TEMPLATE_PATH.'/question/show/answer_lead.phtml' ?>
                <?php require_once TEMPLATE_PATH.'/question/show/answer.phtml' ?>
                <?php require_once TEMPLATE_PATH.'/question/block/topics.phtml' ?>

                <?php require_once TEMPLATE_PATH.'/question/block/subscribe.phtml'; ?>

                <?php require_once TEMPLATE_PATH.'/question/block/contributors_full.phtml'; ?>

                <?php require_once TEMPLATE_PATH.'/question/block/related_questions.phtml'; ?>

                <?php require_once TEMPLATE_PATH.'/question/block/share.phtml' ?>
            </div>
            <div class="col-12 col-md-4 col-xl-4">
                <?php require_once TEMPLATE_PATH.'/question/block/sidebar/about_octo.phtml'; ?>
                <?php require_once TEMPLATE_PATH.'/question/block/sidebar/contributors_top.phtml'; ?>
                <?php require_once TEMPLATE_PATH.'/question/block/lure/add_image.phtml'; ?>
            </div>
        </div>
    </div>

    <?php require_once TEMPLATE_PATH.'/question/block/interesting_questions.phtml' ?>
    <?php require TEMPLATE_PATH.'/_common/footer.phtml'; ?>

    <!-- Modal components -->
    <?php if ($this->authUser): ?>
        <?php require_once TEMPLATE_PATH.'/question/modal/rename.phtml' ?>
        <?php require_once TEMPLATE_PATH.'/question/modal/upload_image.phtml' ?>
    <?php else: ?>
        <!--  -->
    <?php endif; ?>

    <?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
