<!-- header title -->
<div class="mb-3">
    <h1 class="font-size-15 line-height-13 text-dark font-weight-bold" itemprop="name">
        <?= $this->question->title ?>
    </h1>
</div>
<!-- / header title -->

<!-- Microdata: question text -->
<div hidden itemprop="text">
    <?= $this->question->title ?>
</div>
<!-- / Microdata: question text -->

<!-- @TODO Microdata: question author -->
<div hidden itemprop="author" itemscope itemtype="https://schema.org/Person">
    <span itemprop="name">Answeropedia</span>
</div>
<!-- / Microdata: question author -->