<!-- avatar -->
<div class="border rounded p-3 pt-2 bg-white">

    <div class="semi-small font-weight-bold text-uppercase text-black mb-3">
        <?= __('page_settings.avatar__title') ?>
    </div>

    <img class="border rounded wh-80px mb-3" id="settings_pg__user_avatar" src="<?= $this->authUser->getAvatarURLMedium() ?>" />

    <form action="/api/v1/avatar.json" id="form__upload_avatar" method="POST" enctype="multipart/form-data">
        <div class="form-group mb-2">
            <div class="input-group my-2">
                <div class="custom-file">
                    <input type="file" name="new_avatar_file" class="custom-file-input" id="upload-avatar-file">
                    <label class="custom-file-label" for="upload-avatar-file" aria-describedby="inputGroupFileAddon02">
                        <?= __('page_settings.choose_file') ?>&hellip;
                    </label>
                </div>
            </div>
            <label class="semi-small text-muted" for="form__update_name__name">
                <?= __('page_settings.avatar__note') ?>
            </label>
        </div>
        <div class="form-group mb-0">
            <button type="submit" id="form__upload_avatar__submit_btn" class="btn btn-primary btn-sm submit_button">
                <?= __('page_settings.avatar__btn_upload') ?>
            </button>
        </div>
    </form>
</div>
<!-- / avatar -->