<!-- site -->
<div class="border rounded p-3 pt-2 bg-white my-4">

    <div class="semi-small font-weight-bold text-uppercase text-black mb-3">
        <?= __('page_settings.site_title') ?>
    </div>

    <form id="frm__update_site" data-user-id="<?= $this->authUser->id ?>">
        <div class="form-group">
            <label class="semi-small text-muted" for="frm__update_site__site">
                <?= __('page_settings.site_note') ?>
            </label>
            <input id="frm__update_site__site" type="text" class="form-control" value="<?= @$this->authUser->site ?>">
        </div>
        <div class="form-group mb-0">
            <button type="submit" id="frm__update_site__submit" class="btn btn-sm btn-primary">
                <?= __('page_settings.save') ?>
            </button>
        </div>
    </form>
</div>
<!-- / site -->