
<!-- Modal -->
<div class="modal fade" id="modal_ask" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <?= $this->l->t('modal_ask', 'modal_title') ?>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form__question_create">
                <div class="modal-body">
                    <div class="form-group">
                        <label>
                            <?= $this->l->t('modal_ask', 'note') ?>
                        </label>
                        <textarea class="form-control" id="question_title" rows="6" placeholder="<?= $this->l->t('modal_ask', 'input_placeholder') ?>"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="form__question_create__submit" class="btn btn-primary">
                        <?= $this->l->t('modal_ask', 'submit_button') ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
