
<ul class="nav_inline_secondary">
    <li>
        <a href="#">
            Помощь <!--Help -->
        </a>
    </li>
    <li>
        <a href="#">
            О сайте
            <!-- About -->
        </a>
    </li>
    <li>
        <a href="https://vk.com/alexandergomzyakov" rel="nofollow">
            Поддержка
            <!-- Support -->
        </a>
    </li>
    <li>
        <a href="#">
            Условия
            <!-- Terms -->
        </a>
    </li>
    <li>
        <a href="#">
            Конфиденциальность
            <!-- Privacy -->
        </a>
    </li>
</ul>
