
<div class="bg_color_white octo_border_bottom">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-10 col-md-8 mx-auto">

                <div class="mt-4 mb-3">
                    <div class="float-right">
                        <img class="size-12 rounded-circle mt-4" src="<?= User_URL_Helper::getAvatarMediumURL($this->user) ?>" alt="<?= $this->user->getName() ?>">
                    </div>

                    <div class="mr-14">
                        <p class="mb-0 color-gray-500 small">
                            +<?= $this->user->getUsername() ?>
                        </p>
                        <h1><?= $this->user->getName() ?></h1>
                        <?php if ($this->user->getSignature()): ?>
                            <p class="lead mb-0">
                                <?= $this->user->getSignature() ?>
                            </p>
                        <?php endif; ?>
                        <?php if ($this->user->getSite()): ?>
                            <div class="mt-2">
                                <a class="font-weight-bold" href="<?= $this->user->getSite() ?>">
                                    <?= parse_url($this->user->getSite(), PHP_URL_HOST) ?>
                                </a>
                            </div>
                        <?php endif; ?>

                        <div class="actions mt-4 mt-sm-5">
                            <?php if ($this->authUser && $this->authUser->getID() != $this->user->getID()): ?>
                                <button
                                    class="btn follow_user_button mr-2 mb-3 <?= $this->followed ? 'followed btn-success' : 'btn-primary'; ?>"
                                    data-user-id="<?= $this->user->getID() ?>"
                                    data-follow-title="<?= $this->l->t('btn', 'follow') ?>"
                                    data-followed-title="<?= $this->l->t('btn', 'followed') ?>"
                                    data-unfollow-title="<?= $this->l->t('btn', 'unfollow') ?>" type="button">
                                    <img class="btn-icon" src="https://png.icons8.com/material/20/ffffff/plus.png">
                                    <span><?= $this->followed ? $this->l->t('btn', 'followed') : $this->l->t('btn', 'follow'); ?></span>
                                </button>
                            <?php endif; ?>
                            <?php if ($this->authUser && ($this->authUser->getID() == $this->user->getID())): ?>
                                <a rel="nofollow" class="btn btn-outline-secondary mr-2 mb-3" href="<?= Settings_URL_Helper::getSettingsURL($this->lang) ?>">
                                    <img class="btn-icon" src="https://png.icons8.com/material/20/616161/settings.png">
                                    <?= $this->l->t('nav__settings') ?>
                                </a>
                                <a rel="nofollow" class="btn btn-outline-secondary mr-2 mb-3" href="#" data-toggle="modal" data-target="#modal__logout">
                                    <img class="btn-icon" src="https://png.icons8.com/material/20/616161/shutdown.png">
                                    <?= $this->l->t('user__logout') ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
