
<!-- share buttons -->
<script src="//yastatic.net/share2/share.js" async="async" charset="utf-8"></script>
<div class="ya-share2" data-services="twitter,vkontakte,facebook,gplus,pinterest,delicious,digg,reddit,pocket,tumblr,collections,telegram" data-size="m" data-limit="4" data-counter="" data-title="<?= $this->openGraph['title'] ?>" data-description="<?= $this->openGraph['description'] ?>" data-url="<?= $this->openGraph['url'] ?>" data-image="<?= $this->openGraph['image'] ?>"></div>
<!-- /share buttons -->
