
<?php if (!$this->authUser): ?>
    
    <!-- sidebar about_octo -->
    <div class="box mt-4 d-none d-md-block">
        <div class="box-header">
            <a class="color-gray-800 font-weight-600 no-underline-hover" data-scroll href="#contributors_full_list">
                Что это за сайт?
            </a>
        </div>
        <div class="box-body color-gray-800 small">
            <p>OctoAnswers — это как Википедия, только для вопросов и ответов. Вы задаете вопрос и получаете один полный, исчерпывающий и компетентный ответ от сообщества.</p>

            <hr>

            <ul class="list-unstyled color-gray-700">
                <li class="mb-2">Смотрите, какие вопросы задают ваши друзья.</li>
                <li class="mb-2">Следите за новыми вопросами на интересующие вас темы.</li>
                <li class="mb-2">И, конечно, делитесь своими знаниями.</li>
            </ul>

            <button role="button" data-toggle="modal" data-target="#modal_signup" class="btn btn-danger btn-block mb-2">
                Стать автором
            </button>
        </div>
    </div>
    <!-- / sidebar about_octo -->

<?php endif; ?>
