
<?php if (count($this->contributors_top)): ?>
    <!--noindex-->
    <!--googleoff: index-->

    <!-- top contributors @ sidebar -->
    <div class="box mt-4 d-none d-md-block">
        <div class="box-header">
            <a class="float-right color-gray-600 no-underline-hover" data-scroll href="#contributors_full_list">
                <?= count($this->contributors) ?>
                <img class="size-16px mt-minus-4px" src="https://png.icons8.com/material/16/616161/user-group-man-man.png">
            </a>
            <a class="color-gray-800 font-weight-600 no-underline-hover" data-scroll href="#contributors_full_list">
                <?= _('Top answer contributors') ?>
            </a>
        </div>
        <div class="box-body color-gray-800">
            <div class="d-flex flex-wrap">

                <?php foreach ($this->contributors_top as $contributor): ?>
                    <div class="border-bottom pb-3 mt-2 mb-1">
                        <span class="float-left">
                            <a href="<?= $contributor->getURL($this->lang) ?>">
                                <img class="size-5 rounded mt-1" src="<?= $contributor->getAvatarMediumURL() ?>" alt="<?= $contributor->getName() ?>">
                            </a>
                        </span>
                        <div class="ml-6">
                            <a class="font-weight-500 color-gray-800 no-underline-hover" href="<?= $contributor->getURL($this->lang) ?>">
                                <?= $contributor->getName() ?>
                            </a>
                            <div class="small color-gray-600 mt-1">
                                <?= $contributor->getSignature() ? $contributor->getSignature() : $contributor->getUsername() ?>
                                <?php if ($contributor->getSite()): ?>
                                    <span class="font-weight-800 mx-1 color-gray-800">&middot;</span>
                                    <a href="<?= $contributor->getSite() ?>">
                                        <?= parse_url($contributor->getSite(), PHP_URL_HOST) ?>
                                    </a>
                                <?php endif; ?>
                            </div>
                            <div class="small color-gray-700 mt-2">
                                <span class="text-nowrap font-weight-600 mr-1">
                                    <img class="size-18px mt-minus-4px" src="https://png.icons8.com/ios-glyphs/18/3498db/pull-request.png">
                                    <?= Contribution_Humanizer::humanizeCount($contributor->getContribution()) ?>
                                </span>
                                <span class="text-nowrap mr-1">
                                    <img class="size-18px mt-minus-4px"  src="https://png.icons8.com/windows/18/27ae60/add.png">
                                    <span class="color-gray-600">
                                        <?= Contribution_Humanizer::humanizeCount($contributor->getInsertionsCount()) ?>
                                    </span>
                                </span>
                                <span class="text-nowrap mr-1">
                                    <img class="size-18px mt-minus-4px"  src="https://png.icons8.com/windows/18/e74c3c/minus.png">
                                    <span class="color-gray-600">
                                        <?= Contribution_Humanizer::humanizeCount($contributor->getDeletionsCount()) ?>
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>

                <?php if (count($this->contributors) > count($this->contributors_top)): ?>
                    <div class="w-100 ml-6 mt-2">
                        <a class="color-gray-600 small" data-scroll href="#contributors_full_list">
                            <?= _('All answer contributors') ?>
                        </a>
                    </div>
                <?php endif; ?>

            </div>
        </div>
    </div>
    <!-- / top contributors @ sidebar -->

    <!--googleon: index -->
    <!--/noindex-->
<?php endif; ?>
