		  
<nav class="collapse bd-links" id="bd-docs-nav">
	<!--<div class="bd-toc-item">
	  <a class="bd-toc-link" href="/docs/4.3/getting-started/introduction/">
		Getting started
	  </a>

	  
	</div><div class="bd-toc-item active">
	  <a class="bd-toc-link" href="/docs/4.3/content/reboot/">
		Content
	  </a>

	  <ul class="nav bd-sidenav"><li>
			<a href="/docs/4.3/content/reboot/">
			  Reboot
			</a>
		  </li><li>
			<a href="/docs/4.3/content/typography/">
			  Typography
			</a>
		  </li><li>
			<a href="/docs/4.3/content/code/">
			  Code
			</a>
		  </li><li>
			<a href="/docs/4.3/content/images/">
			  Images
			</a>
		  </li><li>
			<a href="/docs/4.3/content/tables/">
			  Tables
			</a>
		  </li><li>
			<a href="/docs/4.3/content/figures/">
			  Figures
			</a>
		  </li></ul>
	</div><div class="bd-toc-item active">
	  <a class="bd-toc-link" href="/docs/4.3/components/alerts/">
		Components
	  </a>

	  <ul class="nav bd-sidenav"><li>
			<a href="/docs/4.3/components/alerts/">
			  Alerts
			</a>
		  </li><li>
			<a href="/docs/4.3/components/badge/">
			  Badge
			</a>
		  </li><li>
			<a href="/docs/4.3/components/breadcrumb/">
			  Breadcrumb
			</a>
		  </li><li class="active bd-sidenav-active">
			<a href="/docs/4.3/components/buttons/">
			  Buttons
			</a>
		  </li><li>
			<a href="/docs/4.3/components/button-group/">
			  Button group
			</a>
		  </li><li>
			<a href="/docs/4.3/components/card/">
			  Card
			</a>
		  </li><li>
			<a href="/docs/4.3/components/carousel/">
			  Carousel
			</a>
		  </li><li>
			<a href="/docs/4.3/components/collapse/">
			  Collapse
			</a>
		  </li><li>
			<a href="/docs/4.3/components/dropdowns/">
			  Dropdowns
			</a>
		  </li><li>
			<a href="/docs/4.3/components/forms/">
			  Forms
			</a>
		  </li><li>
			<a href="/docs/4.3/components/input-group/">
			  Input group
			</a>
		  </li><li>
			<a href="/docs/4.3/components/jumbotron/">
			  Jumbotron
			</a>
		  </li><li>
			<a href="/docs/4.3/components/list-group/">
			  List group
			</a>
		  </li><li>
			<a href="/docs/4.3/components/media-object/">
			  Media object
			</a>
		  </li><li>
			<a href="/docs/4.3/components/modal/">
			  Modal
			</a>
		  </li><li>
			<a href="/docs/4.3/components/navs/">
			  Navs
			</a>
		  </li><li>
			<a href="/docs/4.3/components/navbar/">
			  Navbar
			</a>
		  </li><li>
			<a href="/docs/4.3/components/pagination/">
			  Pagination
			</a>
		  </li><li>
			<a href="/docs/4.3/components/popovers/">
			  Popovers
			</a>
		  </li><li>
			<a href="/docs/4.3/components/progress/">
			  Progress
			</a>
		  </li><li>
			<a href="/docs/4.3/components/scrollspy/">
			  Scrollspy
			</a>
		  </li><li>
			<a href="/docs/4.3/components/spinners/">
			  Spinners
			</a>
		  </li><li>
			<a href="/docs/4.3/components/toasts/">
			  Toasts
			</a>
		  </li><li>
			<a href="/docs/4.3/components/tooltips/">
			  Tooltips
			</a>
		  </li></ul>
	</div><div class="bd-toc-item">
	  <a class="bd-toc-link" href="/docs/4.3/utilities/borders/">
		Utilities
	  </a>

	  <ul class="nav bd-sidenav"><li>
			<a href="/docs/4.3/utilities/borders/">
			  Borders
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/clearfix/">
			  Clearfix
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/close-icon/">
			  Close icon
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/colors/">
			  Colors
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/display/">
			  Display
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/embed/">
			  Embed
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/flex/">
			  Flex
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/float/">
			  Float
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/image-replacement/">
			  Image replacement
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/overflow/">
			  Overflow
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/position/">
			  Position
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/screen-readers/">
			  Screen readers
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/shadows/">
			  Shadows
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/sizing/">
			  Sizing
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/spacing/">
			  Spacing
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/stretched-link/">
			  Stretched link
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/text/">
			  Text
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/vertical-align/">
			  Vertical align
			</a>
		  </li><li>
			<a href="/docs/4.3/utilities/visibility/">
			  Visibility
			</a>
		  </li></ul>
	</div><div class="bd-toc-item">
	  <a class="bd-toc-link" href="/docs/4.3/extend/approach/">
		Extend
	  </a>

	  <ul class="nav bd-sidenav"><li>
			<a href="/docs/4.3/extend/approach/">
			  Approach
			</a>
		  </li><li>
			<a href="/docs/4.3/extend/icons/">
			  Icons
			</a>
		  </li></ul>
	</div><div class="bd-toc-item">
	  <a class="bd-toc-link" href="/docs/4.3/migration/">
		Migration
	  </a>

	  <ul class="nav bd-sidenav"></ul>
	</div>-->
	
	<div class="bd-toc-item active">
		<a class="bd-toc-link" href="#">
			<?= _('Tools') ?>
		</a>
		<ul class="nav bd-sidenav">
			<li>
				<a href="<?= $this->question->getHistoryURL($this->lang) ?>">
					<i class="fas fa-history mr-1"></i> <?= _('Change history') ?>
				</a>
			</li>
			<li>
				<a href="#">
					<s><?= _('Rename question') ?></s>
				</a>
			</li>
			<li>
				<a href="#">
					<s>Ссылки сюда</s>
				</a>
			</li>
			<li>
				<a href="#">
					<s>Сведения о странице</s>
				</a>
			</li>
		</ul>
	</div>

</nav>

