<?php if ($this->showFooter): ?>

	<!-- footer -->
	<footer class="ml-2 mt-4 pt-3 border-top">

        <ul class="list-inline small mb-3">
            <li class="list-inline-item">
                <a class="text-black-50 text-decoration-none" href="<?= SITE_URL.'/'.$this->lang.'/1' ?>">
                    <?= $this->translator->get('About') ?>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="text-black-50 text-decoration-none" href="<?= SITE_URL.'/'.$this->lang.'/2' ?>">
                    <?= $this->translator->get('Rules') ?>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="text-black-50 text-decoration-none" rel="nofollow" target="_blank" href="https://vk.com/alexandergomzyakov">
                    <?= $this->translator->get('Support') ?>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="text-black-50 text-decoration-none" href="<?= Questions_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= $this->translator->get('Questions') ?>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="text-black-50 text-decoration-none" href="<?= Users_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= $this->translator->get('Users') ?>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="text-black-50 text-decoration-none" href="<?= Search_URL_Helper::getSearchQuestionsURL($this->lang) ?>">
                    <?= $this->translator->get('Search') ?>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="text-black-50 text-decoration-none" href="https://www.facebook.com/en.answeropedia" target="_blank" rel="noopener">
                    <i class="fab fa-facebook-square"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="text-black-50 text-decoration-none" href="https://vk.com/answeropedia" target="_blank" rel="noopener">
                    <i class="fab fa-vk"></i>
                </a>
            </li>
        </ul>

	</footer>
	<!-- / footer -->

<?php endif; ?>
