<!-- nav_main -->
<nav class="collapse bd-links" id="main-nav">
	<div class="bd-toc-item active">
		<ul class="nav bd-sidenav">
			<li>
				<a href="<?= Page_URL_Helper::getMainURL($this->lang) ?>">
					<?= _('Main page') ?>
				</a>
			</li>
			<li>
				<a href="<?= SITE_URL.'/'.$this->lang.'/1' ?>">
					<?= _('About site') ?>
				</a>
			</li>
			<li>
				<a href="<?= Page_URL_Helper::getFlowURL($this->lang) ?>">
					<?= _('Recent changes') ?>
				</a>
			</li>
			<li>
				<a href="<?= Hashtags_URL_Helper::getNewestURL($this->lang) ?>">
					<?= _('Popular hashtags') ?>
				</a>
			</li>
			<li>
				<a href="#">
					<s><?= _('Random question') ?></s>
				</a>
			</li>

		</ul>
	</div>
</nav>
<!-- / nav_main -->