<!-- nav_main -->
<nav class="collapse bd-links" id="main-nav">
	<div class="bd-toc-item active">
		<ul class="nav bd-sidenav">
			<li>
				<a href="<?= Page_URL_Helper::getMainURL($this->lang) ?>">
					<?= $this->translator->get('Main page') ?>
				</a>
			</li>
			<li>
				<a href="<?= SITE_URL.'/'.$this->lang.'/1' ?>">
					<?= $this->translator->get('About site') ?>
				</a>
			</li>
			<li>
				<a href="<?= Page_URL_Helper::getFlowURL($this->lang) ?>">
					<?= $this->translator->get('Recent changes') ?>
				</a>
			</li>
			<li>
				<a href="<?= Hashtags_URL_Helper::getNewestURL($this->lang) ?>">
					<?= $this->translator->get('Popular hashtags') ?>
				</a>
			</li>
			<li>
				<a href="<?= SITE_URL.'/'.$this->lang.'/random-question' ?>">
					<?= $this->translator->get('Random question') ?>
				</a>
			</li>

		</ul>
	</div>
</nav>
<!-- / nav_main -->