<!-- sidebar other_languages -->

<nav class="collapse bd-links" id="nav-other-languages">
    <div class="bd-toc-item active">
		<a class="bd-toc-link" href="#">
			<?= $this->translator->get('sidebar__other_languages', 'title') ?>
		</a>
		<ul class="nav bd-sidenav">
			<li>
				<a data-lang="ru" href="<?= Page_URL_Helper::getMainURL('en') ?>">
					<?= $this->translator->get('sidebar__other_languages', 'english') ?>
				</a>
			</li>
			<li>
				<a data-lang="ru" href="<?= Page_URL_Helper::getMainURL('ru') ?>">
					<?= $this->translator->get('sidebar__other_languages', 'russian') ?>
				</a>
			</li>
			<li>
				<a data-lang="en" href="<?= SITE_URL ?>">
				<i class="fas fa-globe-americas"></i>&nbsp;<?= $this->translator->get('sidebar__other_languages', 'all_languages') ?>
				</a>
		    </li>
		</ul>
	</div>
</nav>

<!-- / sidebar other_languages -->
