<!-- sidebar other_languages -->

<nav class="ml-2 my-4">
	<div class="h5 color-secondary-dark-2">
		<?= $this->translator->get('sidebar__other_languages', 'title') ?>
	</div>
	<ul class="list-links">
		<li>
			<a data-lang="ru" href="<?= Page_URL_Helper::getMainURL('en') ?>">
				<?= $this->translator->get('sidebar__other_languages', 'english') ?>
			</a>
		</li>
		<li>
			<a data-lang="ru" href="<?= Page_URL_Helper::getMainURL('ru') ?>">
				<?= $this->translator->get('sidebar__other_languages', 'russian') ?>
			</a>
		</li>
		<li>
			<a href="<?= SITE_URL ?>">
				<?= $this->translator->get('sidebar__other_languages', 'all_languages') ?>
			</a>
		</li>
	</ul>
</nav>

<!-- / sidebar other_languages -->
