<div class="semi-small font-weight-bold text-uppercase text-primary mt-2 mb-3">
    <?= $this->translator->get('main', 'sections', 'title') ?>
</div>

<ul class="list-unstyled semi-small mb-0">

    <li class="my-2">
        <a href="<?= \Helper\URL\Questions::get_newest_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'questions') ?>
        </a>
    </li>

    <li class="my-2">
        <a href="<?= \Helper\URL\Categories::get_newest_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'popular_categories') ?>
        </a>
    </li>

    <li class="my-2">
        <a href="<?= \Helper\URL\Sandbox::get_without_answers_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'sandbox') ?>
            <!-- <i class="material-icons md-18">outlined_flag</i> -->
        </a>
    </li>

    <li class="my-2">
        <a href="<?= \Helper\URL\Page::get_flow_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'recent_changes') ?>
        </a>
    </li>

    <li class="my-2">
        <a href="<?= SITE_URL . '/' . $this->lang . '/random-question' ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'random_question') ?>
        </a>
    </li>
</ul>