<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/common/navbar.phtml'; ?>

    <div class="container-fluid max-width-md">
        <?php require_once TEMPLATE_PATH.'/topics/block/row_header.phtml'; ?>
        <?php require_once TEMPLATE_PATH.'/topics/block/row_list.phtml'; ?>
        <?php require_once TEMPLATE_PATH.'/topics/block/row_more_topics.phtml'; ?>
    </div>

    <?php require_once TEMPLATE_PATH.'/common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH.'/common/js_bottom.phtml'; ?>
</body>
</html>
