
<!-- about_answeropedia -->
<div class="bg-light p-0 p-md-3 mb-4 d-none d-lg-block">
	<div class="border-bottom pb-2 mb-2 h6 font-weight-bold">
		<?= $this->translator->get('block__about_answeropedia', 'title') ?>
	</div>

	<p><?= $this->translator->get('block__about_answeropedia', 'text') ?></p>

	<button role="button" data-toggle="modal" data-target="#modal_signup" class="btn btn-danger btn-block mt-4">
		<?= $this->translator->get('block__about_answeropedia', 'btn_action') ?>
	</button>
</div>
<!-- / about_answeropedia -->

