<!DOCTYPE html>
<html lang="<?= $this->lang ?>">

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body>

    <?php require_once TEMPLATE_PATH . '/_common/navbar.phtml'; ?>

    <div class="container mt-4">
        <div class="row">

            <div class="d-none d-lg-block col-12 col-lg-2">
                <?php require_once TEMPLATE_PATH . '/_common/left/sections.phtml'; ?>
            </div>

            <!-- main_column -->
            <div class="col-12 col-lg-7">

                <div class="border rounded bg-white p-3">
                    <?php require_once __DIR__ . '/header.phtml'; ?>

                    <form id="form__update_categories" data-question-id="<?= $this->question->id ?>">
                        <div class="form-group">
                            <input id="new_categories" data-role="tagsinput" type="text" class="typeahead form-control mt-3" value="<?= $this->categories_string ?>">
                        </div>
                        <div class="form-group mt-4 mb-0">
                            <button type="submit" id="form__update_categories__submit" class="btn btn-primary">
                                <?= __('page_question_update_categories.btn_update_categories') ?>
                            </button>
                        </div>
                    </form>

                </div>

            </div>
            <!-- / main_column -->

            <div class="d-none d-md-block col-lg-3">
                <!-- xxx -->
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH . '/_common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH . '/_common/modals.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>

</body>

</html>