
<!-- app-bar -->

<header id="app-bar" class="mdc-top-app-bar app-bar">
	<div class="mdc-top-app-bar__row">
		<section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
			<a href="#" class="demo-menu material-icons mdc-top-app-bar__navigation-icon">menu</a>
			<span class="mdc-top-app-bar__title">
				<?= $this->translator->get('answeropedia') ?>
				<span style="font-weight: 300;">| <?= $this->translator->get('app_bar', 'text') ?></span>
			</span>
		</section>
		<section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end">
			<a class="material-icons mdc-top-app-bar__action-item" aria-label="Search">search</a>
			<!-- <a class="material-icons mdc-top-app-bar__action-item" aria-label="Info">info</a> -->
		</section>
	</div>
</header>

<!-- / app-bar -->

<!--
<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar">
 
	<div class="navbar-nav-scroll">
		<ul class="navbar-nav bd-navbar-nav flex-row">
			
			<li class="nav-item">
				<form class="form-inline" id="navbar_search_form">
      				<input id="navbar_search_form_query" class="form-control" type="search" placeholder="<?= $this->translator->get('navbar', 'saarch_placeholder') ?>" aria-label="Search">
    		    </form>
            </li>

    	</ul>
	</div>

	<ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
	
		<?php if (!$this->authUser): ?>
			<li class="nav-item">
				<button class="btn btn-warning d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3" role="button" data-toggle="modal" data-target="#modal_login">
					<?= $this->translator->get('Login') ?>
				</button>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#" data-toggle="modal" data-target="#modal_signup">
					<?= $this->translator->get('Signup') ?>
				</a>
			</li>
		<?php endif; ?>

        <?php if ($this->authUser): ?>
            <li class="nav-item">
                <a class="user-avatar d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3" href="<?= $this->authUser->getURL($this->lang) ?>">
                    <img src="<?= $this->authUser->getAvatarSmallURL() ?>" alt="<?= $this->authUser->name ?>">
                </a>
            </li>
		<?php endif; ?>

		<li class="nav-item">
			<button class="btn btn-primary d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3" role="button" data-toggle="modal" data-target="#modal_ask">
        		<?= $this->translator->get('navbar', 'btn_ask') ?>
			</button>
		</li>

	</ul>
	
</header>
 -->

<?php //require_once TEMPLATE_PATH.'/_common/modal/ask.phtml'; ?>

<?php if (!$this->authUser): ?>
    <?php //require_once TEMPLATE_PATH.'/_common/modal/login.phtml'; ?>
    <?php //require_once TEMPLATE_PATH.'/_common/modal/signup.phtml'; ?>
<?php endif; ?>
