
<!-- modal-drawer -->

<aside id="mdc-modal-drawer" class="mdc-drawer mdc-drawer--modal">
    <div class="mdc-drawer__content">
        <nav class="mdc-list">

            <?php require TEMPLATE_PATH.'/_common/drawer/main.phtml';?>

            <?php require TEMPLATE_PATH.'/_common/drawer/other_languages.phtml';?>

        </nav>
    </div>
</aside>

<div class="mdc-drawer-scrim"></div>

<!-- / modal-drawer -->