
<!-- permanent-drawer -->

<div id="mdc-permanent-drawer" class="mdc-drawer mdc-top-app-bar--fixed-adjust">
    <div class="mdc-drawer__header">
        <h3 class="mdc-drawer__title">Mail</h3>
        <h6 class="mdc-drawer__subtitle">email@material.io</h6>
    </div>
    <div class="mdc-drawer__content">
        <nav class="mdc-list">
            
            <?php require_once TEMPLATE_PATH.'/_common/drawer/main.phtml';?>

            <?php require_once TEMPLATE_PATH.'/_common/drawer/other_languages.phtml';?>

        </nav>
    </div>
</div>

<!-- / permanent-drawer -->