<?php if ($this->showFooter): ?>

	<!-- footer -->
	<footer class="border-top">
		<div class="mt-4 mb-1">

			<ul class="list-inline small mb-3">
				<li class="list-inline-item">
					<a class="text-black-50 text-decoration-none" href="<?= SITE_URL.'/'.$this->lang.'/1' ?>">
						<?= _('About') ?>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="text-black-50 text-decoration-none" href="<?= SITE_URL.'/'.$this->lang.'/2' ?>">
						<?= _('Rules') ?>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="text-black-50 text-decoration-none" rel="nofollow" target="_blank" href="https://vk.com/alexandergomzyakov">
						<?= _('Support') ?>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="text-black-50 text-decoration-none" href="<?= Questions_URL_Helper::getNewestURL($this->lang) ?>">
						<?= _('Questions') ?>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="text-black-50 text-decoration-none" href="<?= Users_URL_Helper::getNewestURL($this->lang) ?>">
						<?= _('Users') ?>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="text-black-50 text-decoration-none" href="<?= Search_URL_Helper::getSearchQuestionsURL($this->lang) ?>">
						<?= _('Search') ?>
					</a>
				</li>
			</ul>

		</div>
		
		<!-- social_groups -->
		<div class="mb-5">
			<ul class="list-inline">
				<li class="list-inline-item">
					<a href="https://vk.com/answeropedia" target="_blank" rel="noopener">
						<i class="fab fa-vk"></i>
					</a>
				</li>
				<li class="list-inline-item">
					<a href="https://www.facebook.com/en.answeropedia" target="_blank" rel="noopener">
						<i class="fab fa-facebook"></i>
					</a>
				</li>
			</ul>
		</div>
		<!-- / social_groups -->

	</footer>
	<!-- / footer -->

<?php endif; ?>
