<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title><?= $this->pageTitle ?></title>

<?php if ($this->pageDescription) : ?>
<meta name="description" content="<?= $this->pageDescription ?>">
<?php endif; ?>

<?php if (isset($this->canonicalURL)) : ?>
<link rel="canonical" href="<?= $this->canonicalURL ?>" />
<?php endif; ?>

<!-- Favicons -->
<link rel="icon" type="image/png" href="https://answeropedia.org/assets/img/favicon/favicon-16.png" sizes="16x16">
<link rel="icon" type="image/png" href="https://answeropedia.org/assets/img/favicon/favicon-32.png" sizes="32x32">
<link rel="icon" type="image/png" href="https://answeropedia.org/assets/img/favicon/favicon-96.png" sizes="96x96">
<link rel="icon" type="image/png" href="https://answeropedia.org/assets/img/favicon/favicon-160.png" sizes="160x160">
<link rel="icon" type="image/png" href="https://answeropedia.org/assets/img/favicon/favicon-196.png" sizes="196x196">
<link rel="apple-touch-icon" href="https://answeropedia.org/assets/img/favicon/apple-touch-icon-120.png">
<link rel="apple-touch-icon" href="https://answeropedia.org/assets/img/favicon/apple-touch-icon-152.png" sizes="152x152">
<link rel="apple-touch-icon" href="https://answeropedia.org/assets/img/favicon/apple-touch-icon-180.png" sizes="180x180">

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- Stylesheet -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" rel="stylesheet">
<link rel="stylesheet" href="https://answeropedia.org/assets/css/style.css?v=8">

<?php if (count($this->includeCSS)) : ?>
<!-- Additional CSS -->
<?php foreach ($this->includeCSS as $linkToCSS) : ?>
<link rel="stylesheet" href="<?= $linkToCSS ?>">
<?php endforeach; ?>
<!-- / Additional CSS -->
<?php endif; ?>

<!-- Open Graph tags -->
<?php
if (isset($this->open_graph) && count($this->open_graph)) {
    foreach ($this->open_graph as $key => $value) {
        echo '<meta property="og:' . $key . '" content="' . $value . '"' . "\n";
    }
} ?>

<?php require_once __DIR__ . '/counter/google_analytics.html' ?>