
<script src="https://unpkg.com/material-components-web/dist/material-components-web.min.js"></script>

<script>
    // Select DOM elements

    const elementTopAppBar = document.querySelector('.mdc-top-app-bar');
    const elementModalDrawer = document.querySelector('#mdc-modal-drawer');
    const elementModalDrawerList = document.querySelector('#mdc-modal-drawer .mdc-list');
    const elementMainContent = document.querySelector('.main-content');

    // Initialize top app bar
    // using the automatic instantiation method. Dont`t work: const list = new MDCList(elementModalDrawerList);

    const topAppBar = mdc.topAppBar.MDCTopAppBar.attachTo(elementTopAppBar);
    const modalDrawer = mdc.drawer.MDCDrawer.attachTo(elementModalDrawer);

    // Init ModalDrawer`s when page loaded

    const initModalDrawer = () => {

        modalDrawer.open = false;

        topAppBar.listen('MDCTopAppBar:nav', () => {
            modalDrawer.open = !modalDrawer.open;
        });

        // Close ModalDrawer when clicked on menu item
        elementModalDrawerList.addEventListener('click', (event) => {
            modalDrawer.open = false;
        });
    }

    initModalDrawer();

    // Init PermanentDrawer`s and show/hide Sandwitch-button

    if (window.matchMedia("(max-width: 900px)").matches) {
        console.log('max-width <900');


    } else {
        console.log('max-width >900');

        //const list = mdc.list.MDCList.attachTo(elementModalDrawerList);

        //list.wrapFocus = true;
    }

    // Toggle between permanent drawer and modal drawer at breakpoint 900px

    const resizeHandler = () => {
        if (window.matchMedia("(max-width: 900px)").matches) {
            //initModalDrawer();
            console.log('hide permanent mdc-drawer');
        } else {

            //elementModalDrawer.classList.remove("mdc-drawer--modal");
            console.log('show permanent mdc-drawer');

        }
    }
    window.addEventListener('resize', resizeHandler);

</script>

<!-- Instantiate single textfield component rendered in the document -->
<script>
    mdc.textField.MDCTextField.attachTo(document.querySelector('.mdc-text-field'));
</script>

<!-- OLD -->

<!-- JS Helpers -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js" integrity="sha256-1A78rJEdiWTzco6qdn3igTBv9VupN3Q1ozZNTR4WE/Y=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/14.2.0/smooth-scroll.min.js" integrity="sha256-/k5n1rmutzb2PSqvtV77T+xHa9plhfEjb/mpn1RpMzA=" crossorigin="anonymous"></script>

<!-- init smooth-scroll -->
<script>
	var scroll = new SmoothScroll('a[href*="#"]');
</script>

<?php if (isset($this->includeJS) && count($this->includeJS)): ?>
    <?php foreach ($this->includeJS as $filename): ?>
        <script src="<?= JS_URL.'/'.$filename.'.js' ?>" type="text/javascript"></script>
    <?php endforeach; ?>
<?php endif; ?>

<?php require_once __DIR__.'/counter/yandex_metrika.html' ?>
