
<!-- navbar -->
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container-fluid">

        <a class="navbar-brand" href="<?= Page_URL_Helper::getMainURL($this->lang) ?>">
            <img class="rounded d-inline-block align-top opacity-80 hover-opacity-100" src="<?= IMAGE_URL.'/octo-logo-30x30.svg' ?>" width="30" height="30" alt="Octoanswers">
            <span class="ml-2 d-inline d-sm-none">OctoAnswers<span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <?php if (!$this->authUser): ?>
                    <li class="nav-item d-sm-none d-md-inline-block">
                        <a class="nav-link color-primary font-weight-600" href="#">
                            О сайте
                        </a>
                    </li>
                <?php endif; ?>

                <?php if ($this->authUser): ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= Page_URL_Helper::getFeedURL($this->lang) ?>">
                            <?= $this->l->t('navbar', 'feed') ?>
                        </a>
                    </li>
                <?php endif; ?>

                <li class="nav-item">
                    <a class="nav-link" href="<?= Sandbox_URL_Helper::getWithoutAnswersURL($this->lang) ?>">
                        <?= $this->l->t('navbar', 'sandbox') ?>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="<?= Questions_URL_Helper::getNewestURL($this->lang) ?>">
                        <?= $this->l->t('navbar', 'questions') ?>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="<?= Topics_URL_Helper::getNewestURL($this->lang) ?>">
                        <?= $this->l->t('navbar', 'topics') ?>
                    </a>
                </li>

            </ul>
            <ul class="navbar-nav">

                <li class="nav-item d-sm-none d-md-inline-block">
                    <a class="nav-link pb-0 mb-0 my-2 my-sm-0" href="#" style="padding-top:6px;">
                        <!-- https://png.icons8.com/material/24/9E9E9E/search.png -->
                        <img class="mr-1 mr-sm-2"  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE2SURBVEhL7ZRbSgNBFETnX/xT16PuIOJShOCHGJNVDMwDZgM+sg2NrkRNyHf01FADYmi6Z/ABYkHRTfWtut03TLK/ibIs9+GsqqoF61r0fpbn+Z7LhoGQU8JW8C3AV3ji8n5QONwoiPW6ruvDpml2RO2l+WwDR7algZADzN3NzyxvgbOxmyx7jQuDZi7jjaUgqLnzRa4sxUHxk0wahaUgiqI48mUeLcWBoR2P5m0pCBrsqlYeS3EMacAL1pbi0HNl0vMtBdGNCC4sxUHx1LdK/pFZJ5bioFhf79I3G1veAmfnDn+Wx3IaMIxg+6HBW41C8/bMj+HcZ2pwYVs/uMlLF/SZOlP4B+3S1nToC8U4JeiBdcWqP7x7hbG2Y3H48CYx0Gjy3yQZP95Ee8tfCwV/W/gvIcveAZCgcJfq8V46AAAAAElFTkSuQmCC">
                        <span class="d-inline-block d-sm-none">
                            Поиск
                        </span>
                    </a>
                </li>

                <li class="nav-item">
                    <button class="btn btn-outline-success my-2 my-sm-0 mr-sm-3" role="button" data-toggle="modal" data-target="#modal_ask">
                        <?= $this->l->t('navbar', 'ask') ?>
                    </button>
                </li>

                <?php if (!$this->authUser): ?>
                    <li class="nav-item">
                        <button class="btn btn-outline-secondary my-2 my-sm-0" role="button" data-toggle="modal" data-target="#modal_login">
                            <?= $this->l->t('navbar', 'login') ?>
                        </button>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#modal_signup">
                            <?= $this->l->t('navbar', 'signup') ?>
                        </a>
                    </li> -->
                <?php endif; ?>

                <?php if ($this->authUser): ?>
                    <li class="nav-item">
                        <a class="user-avatar my-2 my-sm-0" href="<?= $this->authUser->getURL($this->lang) ?>">
                            <img src="<?= $this->authUser->getAvatarSmallURL() ?>" alt="<?= $this->authUser->getName() ?>">
                        </a>
                    </li>
                <?php endif; ?>

            </ul>
        </div>
    </div>
</nav>
<!-- / navbar -->

<!-- <li class="nav-item dropdown mr-3 ">
    <button class="nav-button btn btn-outline-secondary dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  type="button">
        <?= $this->lang ?>
    </button>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item" data-lang="en" href="<?= Page_URL_Helper::getMainURL('en') ?>">
            <?= _('Lang - English') ?>
        </a>
        <a class="dropdown-item" data-lang="ru" href="<?= Page_URL_Helper::getMainURL('ru') ?>">
            <?= _('Lang - Russian') ?>
        </a>
    </div>
</li> -->

<?php require_once TEMPLATE_PATH.'/_common/modal/ask.phtml'; ?>

<?php if (!$this->authUser): ?>
    <?php require_once TEMPLATE_PATH.'/_common/modal/login.phtml'; ?>
    <?php require_once TEMPLATE_PATH.'/_common/modal/signup.phtml'; ?>
<?php endif; ?>
