<!-- sidebar main -->

<nav class="navbar-subnav sticky-top d-none d-md-block">
    <div class="container">
        <div class="row py-1">

            <!-- main_column -->
            <div class="col-12">

                <ul class="list-inline mb-0 semi-small">

                    <li class="list-inline-item my-1 mr-3">
                        <a href="<?= SITE_URL . '/' . $this->lang . '/' . $this->translator->get('service_id', 'about_answeropedia') ?>" class="text-decoration-none">
                            <?= $this->translator->get('sidebar__main_nav', 'how_it_works') ?>
                        </a>
                    </li>

                    <li class="list-inline-item my-1 mr-3">
                        <a href="<?= Page_URL_Helper::get_flow_URL($this->lang) ?>" class="text-decoration-none">
                            <?= $this->translator->get('sidebar__main_nav', 'recent_changes') ?>
                        </a>
                    </li>

                    <li class="list-inline-item my-1 mr-3">
                        <a href="<?= Sandbox_URL_Helper::get_without_answers_URL($this->lang) ?>" class="text-decoration-none">
                            <?= $this->translator->get('sidebar__main_nav', 'sandbox') ?>
                        </a>
                    </li>

                    <li class="list-inline-item my-1 mr-3">
                        <a href="<?= Categories_URL_Helper::get_newest_URL($this->lang) ?>" class="text-decoration-none">
                            <i class="material-icons md-18 w-20px">bubble_chart</i><?= $this->translator->get('sidebar__main_nav', 'popular_categories') ?>
                        </a>
                    </li>

                    <li class="list-inline-item my-1">
                        <a href="<?= SITE_URL . '/' . $this->lang . '/random-question' ?>" class="text-decoration-none">
                            <?= $this->translator->get('sidebar__main_nav', 'random_question') ?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

<!-- / sidebar main -->