
<!-- navbar -->
<header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar">

    <?php if ($this->authUser): ?>
        <a class="navbar-brand mr-0 mr-md-4 ml-md-2" href="<?= Page_URL_Helper::getFeedURL($this->lang) ?>">
            <?= _('Answeropedia') ?>
        </a>
    <?php else: ?>
        <a class="navbar-brand mr-0 mr-md-2" href="<?= Page_URL_Helper::getMainURL($this->lang) ?>">
            <?= _('Answeropedia') ?>
        </a>
    <?php endif; ?>
  
	<div class="navbar-nav-scroll">
		<ul class="navbar-nav bd-navbar-nav flex-row">
			
			<?php if (!$this->authUser): ?>
                <li class="nav-item d-sm-none d-md-inline-block">
                    <a class="nav-link" href="#">
                        <?= _('Navbar.About_site') ?>
                    </a>
                </li>
            <?php endif; ?>
		
			<li class="nav-item">
				<a class="nav-link " href="<?= Page_URL_Helper::getFlowURL($this->lang) ?>">
					<?= _('Navbar.Recent_changes') ?>
				</a>
			</li>
			
			<li class="nav-item">
                <a class="nav-link " href="<?= Hashtags_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= _('Navbar.Hashtags') ?>
                </a>
            </li>

			<li class="nav-item">
                <a class="nav-link <?= true ? 'active' : '' ?>" href="<?= Sandbox_URL_Helper::getWithoutAnswersURL($this->lang) ?>">
                    <i class="fas fa-dice d-none d-md-inline-block"></i>&nbsp;<?= _('Navbar.Sandbox') ?>
                </a>
            </li>

    	</ul>
	</div>

	<ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
	
		<?php if (!$this->authUser): ?>
			<li class="nav-item">
				<a class="nav-link p-2" href="#" target="_blank" rel="noopener" aria-label="VK">
					<i class="fab fa-vk"></i>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link p-2" href="#" target="_blank" rel="noopener" aria-label="Facebook">
					<i class="fab fa-facebook"></i> 
				</a>
			</li>
		<?php endif; ?>

		<?php if (!$this->authUser): ?>
			<li class="nav-item">
				<button class="btn btn-warning d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3" role="button" data-toggle="modal" data-target="#modal_login">
					<?= _('Login') ?>
				</button>
			</li>
			<!-- <li class="nav-item">
				<a class="nav-link" href="#" data-toggle="modal" data-target="#modal_signup">
					<?= _('Signup') ?>
				</a>
			</li> -->
		<?php endif; ?>

        <?php if ($this->authUser): ?>
            <li class="nav-item">
                <a class="user-avatar d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3" href="<?= $this->authUser->getURL($this->lang) ?>">
                    <img src="<?= $this->authUser->getAvatarSmallURL() ?>" alt="<?= $this->authUser->name ?>">
                </a>
            </li>
		<?php endif; ?>

		<li class="nav-item">
			<button class="btn btn-primary d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3" role="button" data-toggle="modal" data-target="#modal_ask">
        		<?= _('Navbar.Ask_a_question') ?>
			</button>
		</li>

	</ul>
	
</header>
<!-- / navbar -->

<?php require_once TEMPLATE_PATH.'/_common/modal/ask.phtml'; ?>

<?php if (!$this->authUser): ?>
    <?php require_once TEMPLATE_PATH.'/_common/modal/login.phtml'; ?>
    <?php require_once TEMPLATE_PATH.'/_common/modal/signup.phtml'; ?>
<?php endif; ?>
