
<!-- Base SimpleMDE JS -->
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

<!-- Customize SimpleMDE -->
<script>


// set up the URL prefixes that you want to use for the links
// const profilePrefix = 'http://example.com/profile?username=';
// const topicPrefix = 'http://example.com/search?query=%23';
//
// // regexes to detect mentions and/or topics…
// // this might differ in your site, and I'm sure there's more thorough examples available on the web
// // (or you could try find Twitter's implementation)
// const mentionRegex = /(^|\W)@([\w.-]+)($|[^\w.-])/g;
// const topicRegex = /(?=^|[^&])#([\w.-]+)(?=$|[^\w.-;])/g;
//
// // function that takes the text and runs the replaces on it
// function customMarkdownParser(text) {
//     let linkedText = text.replace(mentionRegex, `$1<a class="mention" href="${profilePrefix}$2">@$2</a>$3`);
//     linkedText = linkedText.replace(topicRegex, `<a href="${topicPrefix}$1">#$1</a>`);
//     return linkedText;
// }

    var simplemde = new SimpleMDE({
        element: document.getElementById("form__update_answer__answer_text"),
        spellChecker: false,
        placeholder: "Type here...",
        toolbar: [
            {
                name: "bold",
                action: SimpleMDE.toggleBold,
                className: "fa fa-bold",
                title: "Bold",
            },
            {
                name: "italic",
                action: SimpleMDE.toggleItalic,
                className: "fa fa-italic",
                title: "Italic",
            },
            {
                name: "heading",
                action: SimpleMDE.toggleHeadingSmaller,
                className: "fa fa-header",
                title: "Heading",
            },
            "|",
            {
                name: "unordered-list",
                action: SimpleMDE.toggleUnorderedList,
                className: "fa fa-list-ul",
                title: "Generic List",
            },
            {
                name: "ordered-list",
                action: SimpleMDE.toggleOrderedList,
                className: "fa fa-list-ol",
                title: "Numbered List",
            },
            "|",
            {
                name: "internal-link",
                action: function drawLink(editor){
                    var cm = editor.codemirror;
                    var output = '';
                    var selectedText = cm.getSelection();
                    var text = selectedText || 'placeholder';

                    output = '[' + text + ']()';
                    cm.replaceSelection(output);
                },
                className: "fa fa-link",
                title: "Create Internal Link",
            },
            {
                name: "topic-link",
                action: function drawTopicLink(editor){
                    var cm = editor.codemirror;
                    var output = '';
                    var selectedText = cm.getSelection();
                    var text = selectedText || 'placeholder';

                    output = '#' + text;
                    cm.replaceSelection(output);
                },
                className: "fa fa-topic",
                title: "Create Topic Link",
            },
            {
                name: "link",
                action: SimpleMDE.drawLink,
                className: "fa fa-external-link",
                title: "Create External Link",
            },
            "|",
            {
                name: "quote",
                action: SimpleMDE.toggleBlockquote,
                className: "fa fa-quote-left",
                title: "Quote",
            },
            {
                name: "code",
                action: SimpleMDE.toggleCodeBlock,
                className: "fa fa-code",
                title: "Code",
            },
            {
                name: "table",
                action: SimpleMDE.drawTable,
                className: "fa fa-table",
                title: "Insert Table",
            },
            "|",
            {
                name: "preview",
                action: SimpleMDE.togglePreview,
                className: "fa fa-eye no-disable",
                title: "Toggle Preview",
            },
            {
                name: "fullscreen",
                action: SimpleMDE.toggleFullScreen,
                className: "fa fa-arrows-alt no-disable no-mobile",
                title: "Toggle Fullscreen",
            }
        ]
    });

    // simplemde.codemirror.on("change", function(){
    //     console.log(simplemde.value());
    //     var txt = customMarkdownParser(simplemde.value());
    // });

</script>
