<div class="mb-3 mt-3 ml-1 pl-3">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link <?= $this->list == 'questions' ? 'active' : '' ?>" href="<?= \Helper\URL\Search::getSearchQuestionsURL($this->lang, $this->query) ?>">
                <?= __('page_search.filters.questions'); ?>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $this->list == 'categories' ? 'active' : '' ?>" href="<?= \Helper\URL\Search::getSearchCategoriesURL($this->lang, $this->query) ?>">
                <?= __('page_search.filters.categories'); ?>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $this->list == 'users' ? 'active' : '' ?>" href="<?= \Helper\URL\Search::getSearchUsersURL($this->lang, $this->query) ?>">
                <?= __('page_search.filters.users'); ?>
            </a>
        </li>
    </ul>
</div>