<div class="mb-5">

    <p class="lead text-muted mb-1"><?= __('page_error.category_not_found.title') ?></p>
    <h1 class="mt-0">
        <?= $this->categoryTitle ?>
    </h1>

    <div class="mt-4 mb-5">
        <!-- <a rel="nofollow" class="btn btn-primary" href="#" role="button">
            <?= __('Ask a question') ?>
        </a> -->
        <a class="btn btn-outline-secondary" href="#" role="button" onclick="window.history.go(-1); return false;">
            <?= __('Go back') ?>
        </a>
    </div>

</div>