
<?php if ((count($this->topics) == 0) && ($this->query != '')): ?>
    <div class="alert alert-secondary pb-5 mt-4">
        <div class="text-center">
            <p class="mb-2"><strong><?= $this->l->t('search__alert__topics_not_found__title') ?></strong></p>
            <p class="mb-4">
                <?= str_replace('%query%', $this->query, $this->l->t('search__alert__topics_not_found__text')); ?>
            </p>
            <a class="btn btn-outline-primary" href="#" role="button">
                <?= $this->l->t('search__alert__topics_not_found__button') ?>
            </a>
        </div>
    </div>
<?php endif; ?>
