
<?php if ((count($this->users) == 0) && ($this->query != '')): ?>
    <div class="alert alert-secondary pb-5 mt-4">
        <div class="text-center">
            <p class="mb-2"><strong><?= _('Search - Users not found alert - Title') ?></strong></p>
            <p class="mb-4">
                <?= str_replace('%query%', $this->query, _('Search - Users not found alert - Text')); ?>
            </p>
            <a class="btn btn-outline-primary" href="#" role="button">
                <?= _('Search - Users not found alert - Button') ?>
            </a>
        </div>
    </div>
<?php endif; ?>
