
<div class="mb-5">
    <p class="mb-1">
        Задан новый вопрос с хештегом <a href="<?= $data['topic']['url'] ?>">#<?= $data['topic']['title'] ?></a>
    </p>
    <p class="mb-3">
        <a class="link-inverted no-underline h5" href="<?= $data['question']['url'] ?>"><?= $data['question']['title'] ?></a>
    </p>
    <span class="text-muted">
        <?= $activity['created_at__humanized'] ?>
    </span>
</div>
