
<div class="mb-5">
    <a class="wh-3" href="<?= $data['user']['profile_url'] ?>">
        <img class="wh-3 rounded-circle" src="<?= $data['user']['avatar_xs_url'] ?>">
    </a>
    <p class="mb-1">
        <a href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a> подписался на вопрос <a href="<?= $data['question']['url'] ?>"><?= $data['question']['title'] ?></a>
    </p>
    <span class="text-muted">
        <?= $activity['created_at__humanized'] ?>
    </span>
</div>
