
<div class="mb-5">
    <a class="wh-3" href="<?= $data['user']['profile_url'] ?>">
        <img class="wh-3 rounded-circle" src="<?= $data['user']['avatar_xs_url'] ?>">
    </a>

    <p class="mb-1">
        <a href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a> подписался на пользователя
    </p>
    <p class="mb-1">
        <a class="wh-3 mr-2" href="<?= $data['followed_user']['profile_url'] ?>">
            <img class="wh-3 rounded-circle" src="<?= $data['followed_user']['avatar_xs_url'] ?>">
        </a>
        <a href="<?= $data['followed_user']['profile_url'] ?>"><?= $data['followed_user']['name'] ?></a>
    </p>
    <span class="text-muted">
        <?= $activity['created_at__humanized'] ?>
    </span>
</div>
