
<?php if (count($this->related_hashtags)): ?>

    <!-- related_hashtags -->
    <div class="my-4">
        <div class="">
            <a class="font-weight-bold color-secondary-dark-3" href="#">
                Похожие темы
            </a>
        </div>
        <div class="pt-4 pb-0">
            <?php foreach ($this->related_hashtags as $hashtag): ?>
                <a class="badge badge-secondary mr-2 mb-3" href="<?= $hashtag->getURL($this->lang) ?>">
                    <?= $hashtag->title ?>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
    <!-- / related_hashtags -->
<?php else: ?>
    <!-- <div class="alert alert-super" role="alert">
        <img src="/public/img/Ghost-96.png" alt="Нет вопросов в теме «{{ hashtag.getTitle }}»"/>
        <p><strong>Вопросов нет</strong></p>
        <p>Нет ни одного вопроса относящегося к теме «{{ hashtag.title }}»</p>
        {% if authUser %}
            <p><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal__ask">Задать вопрос</button></p>
        {% else %}
            <p><button class="btn btn-primary" data-toggle="modal" data-target="#modal__ask_not_logged">Задать вопрос</button></p>
        {% endif %}
    </div> -->
<?php endif; ?>
