<!DOCTYPE html>
<html lang="<?= $view_data->lang ?>">

<head>
    <?php require TEMPLATE_PATH . '/_common/head_vd.phtml'; ?>
</head>

<body>

    <?php require TEMPLATE_PATH . '/_common/navbar_vd.phtml'; ?>

    <div class="container mt-4">
        <div class="row">

            <div class="d-none d-lg-block col-12 col-lg-2">
                <?php require TEMPLATE_PATH . '/_common/left/sections_vd.phtml'; ?>
            </div>

            <!-- main_column -->
            <div class="col-12 col-lg-7">
                <?php require __DIR__ . '/search_form.phtml'; ?>
                <?php require __DIR__ . '/users.phtml' ?>
                <?php require __DIR__ . '/more_users.phtml'; ?>
            </div>
            <!-- / main_column -->

            <div class="d-none d-md-block col-lg-3">
                <?php require __DIR__ . '/login_or_signup.phtml'; ?>
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH . '/_common/modals_vd.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js_vd.phtml'; ?>

</body>

</html>