
<div class="alert alert-warning mt-5">
    <div class="text-center">
        <img alt="<?= $this->l->t('Signup on question and answer site OctoAnswers') ?>" src="/public/img/astronaut-helmet-100.png" class="square-100 mx-auto mt-4 mb-4">
    </div>

    <p><strong><?= $this->l->t('Not yet registered?') ?></strong></p>
    <p><?= $this->l->t('Signing up allows you to a earn reputation when you help others with questions, answers and edits.') ?></p>

    <div class="mt-4">
        <a class="btn btn-outline-primary btn-sm" href="#" data-toggle="modal" data-target="#modal_login">
            <?= $this->l->t('Login') ?>
        </a>
        <a class="btn btn-outline-primary btn-sm" href="#" data-toggle="modal" data-target="#modal_signup">
            <?= $this->l->t('Signup') ?>
        </a>
    </div>
</div>
