
<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 mx-auto">

                <?php require_once TEMPLATE_PATH.'/users/block/header.phtml'; ?>
                <?php require_once TEMPLATE_PATH.'/users/block/nav.phtml'; ?>
                <?php require_once TEMPLATE_PATH.'/users/block/users_table.phtml'; ?>
                <?php require_once TEMPLATE_PATH.'/users/block/more_users.phtml'; ?>

            </div>
        </div>
    </div>

    <!-- <?php require TEMPLATE_PATH.'/users/block/container_login_or_signup.phtml'; ?> -->

    <?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
