<!-- header -->
<div class="mb-4">
    <form action="<?= SITE_URL . '/' . $this->lang . '/search' ?>" method="GET">
        <input type="hidden" name="list" value="users">
        <div class="form-group">
            <input name="q" class="form-control" type="text" placeholder="<?= $this->translator->get('users', 'search_placeholder') ?>" aria-label="Search">
        </div>
    </form>
</div>
<!-- / header -->