<!-- categories -->
<?php if (count($view_data->users)) : ?>
	<?php foreach ($view_data->users as $user) : ?>
		<div class="border rounded bg-white p-3 my-4">

			<div class="media position-relative">
				<a class="wh-48px mt-1 mr-3 rounded" href="<?= $user->get_URL($view_data->lang) ?>">
					<img src="<?= $user->get_avatar_URL_small() ?>" class="wh-48px rounded" alt="<?= $user->name ?>">
				</a>
				<div class="media-body">
					<a class="mt-0 mr-2 font-weight-bold text-dark text-decoration-none" href="<?= $user->get_URL($view_data->lang) ?>">
						<?= $user->name ?>
					</a>

					<div class="semi-small text-black-50 mt-1">
						<?php if ($user->signature) : ?>
							<?= $user->signature ?>
						<?php else : ?>
							@<?= $user->username ?>
						<?php endif; ?>

						<?php if ($user->site) : ?>
							<span class="font-weight-bold mx-1 text-dark">&middot;</span>
							<a href="<?= $user->site ?>">
								<?= parse_url($user->site, PHP_URL_HOST) ?>
							</a>
						<?php endif; ?>
					</div>

					<div class="small text-black-50 mt-2">
						<a class="btn btn-sm btn-outline-gray mr-2" rel="nofollow" href="#">
							<?= __('Follow') ?>
						</a>
						<?= \Humanizer\DateTime::humanize_timestamp($view_data->lang, $user->createdAt) ?>
					</div>
				</div>
			</div>

		</div>
	<?php endforeach; ?>
<?php endif; ?>
<!-- / categories -->