
<div class="border-bottom py-4 pb-lg-5">
    <div class="container">
        <div class="row ">
            <div class="col-12 col-sm-11 col-md-10 col-lg-9 mx-auto">
                <p class="lead text-muted mb-1"><?= $this->translator->get("answer_history", "page_title") ?></p>
                <h1 class="h2 mt-0">
                    <a class="link-inverted text-decoration-none" href="<?= $this->question->getURL($this->lang) ?>">
                        <?= $this->question->title ?>
                    </a>
                </h1>
                <a class="btn btn-sm btn-outline-secondary mt-2" role="button" href="<?= $this->question->getURL($this->lang) ?>">
                    <?= $this->translator->get('Back to question') ?>
                </a>
            </div>
        </div>
    </div>
</div>
