
<?php $user = $this->users[$i]; ?>

<div class="my-5">

    <div class="media">
		<a class="d-block wh-3 mr-3 mb-3" href="<?= ($this->users[$i])->getURL($this->lang) ?>">
            <img class="wh-3 mr-3 rounded" src="<?= ($this->users[$i])->getAvatarSmallURL() ?>">
        </a>
  		<div class="media-body">
			<a class="h5 color-secondary-dark-4 text-decoration-none" href="<?= ($this->users[$i])->getURL($this->lang) ?>">
                <?= $this->users[$i]->name ?>
			</a>
            <div class="small color-secondary-dark-1">
                <?= $this->translator->get('Change ID') ?> #<?= $this->revisions[$i]->id ?>
                <span class="color-secondary-dark-4 font_weight_800">&middot;</span>
                <?php if ($this->revisions[$i]->comment): ?>
                    <?= $this->translator->get('Description of changes') ?>: <?= $this->revisions[$i]->comment ?>
                <?php else: ?>
                    <?= $this->translator->get('No description of changes') ?>
                <?php endif; ?>
                <span class="color-secondary-dark-4 font_weight_800">&middot;</span>
                <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $this->revisions[$i]->createdAt) ?>
            </div>

		</div>
    </div>
    
    <pre><?= FineDiff::renderDiffToHTMLFromOpcodes($this->revisions[$i]->baseText, $this->revisions[$i]->opcodes) ?></pre>
</div>
