
<div class="my-5">
    <div class="mb-3">
        <div class="pt-1 float-left">
            <a class="wh-3" href="<?= ($this->users[$i])->getURL($this->lang) ?>">
                <img class="wh-3 rounded-circle" src="<?= ($this->users[$i])->getAvatarSmallURL() ?>">
            </a>
        </div>
        <div class="ml-8">
            <div class="">
                <a class="font_weight_600 small mr-1" href="<?= ($this->users[$i])->getURL($this->lang) ?>">
                    <?= $this->users[$i]->name ?>
                </a>
            </div>
            <span class="small color-gray-600">
                <?= _('Change ID') ?> #<?= $this->revisions[$i]->id ?>
                <span class="color-gray-900 font_weight_800">&middot;</span>
                <?php if ($this->revisions[$i]->comment): ?>
                    <?= _('Description of changes') ?>: <?= $this->revisions[$i]->comment ?>
                <?php else: ?>
                    <?= _('No description of changes') ?>
                <?php endif; ?>
                <span class="color-gray-900 font_weight_800">&middot;</span>
                <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $this->revisions[$i]->createdAt) ?>
            </span>
        </div>
    </div>
    <pre><?= FineDiff::renderDiffToHTMLFromOpcodes($this->revisions[$i]->baseText, $this->revisions[$i]->opcodes) ?></pre>
</div>
