
<!-- social_groups -->
<div class="mt-5 mb-4">
    <div class="small color-gray-600">
        ОктоАнсверс в соцсетях
    </div>
    <ul class="list-inline small mt-2">
        <li class="list-inline-item">
            <a class="mx-1" href="https://vk.com/octoanswers" target="_blank" rel="noopener">
                <i class="fab fa-vk"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a class="mx-1" href="https://www.facebook.com/octoanswers" target="_blank" rel="noopener">
                <i class="fab fa-facebook"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a class="mx-1" href="#" target="_blank" rel="noopener">
                <i class="fab fa-twitter"></i>
            </a>
        </li>
    </ul>
</div>
<!-- / social_groups -->
