
<!-- activity f_u_follow_u -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block size-4 mt-1" href="<?= $data['user']['profile_url'] ?>">
            <img class="size-4 rounded" src="<?= $data['user']['avatar_xs_url'] ?>">
        </a>
    </div>
    <div class="width-full">
        <div class="color-gray-700">
            <a class="color-gray-900 font-weight-600" href="<?= $data['user']['profile_url'] ?>">
                <?= $data['user']['name'] ?>
            </a>
            подписался на пользователя
            <a class="color-gray-900 font-weight-600" href="<?= $data['followed_user']['profile_url'] ?>">
                <?= $data['followed_user']['name'] ?>
            </a>
        </div>
        <div class="mt-2 mb-1">
            <a class="d-block size-10" href="<?= $data['followed_user']['profile_url'] ?>">
                <img class="size-10 rounded" src="<?= $data['followed_user']['avatar_xs_url'] ?>">
            </a>
        </div>
        <span class="small color-gray-500">
            <?= $activity['created_at__humanized'] ?>
        </span>
    </div>
</div>
<!-- / activity f_u_follow_u -->
