
<tr class="mt-4">
    <td style="width: 5rem !important;">
        <a class="wh-3" href="<?= $data['user']['profile_url'] ?>">
            <img class="wh-3 rounded-circle" src="<?= $data['user']['avatar_xs_url'] ?>">
        </a>
    </td>
    <td>
        <p class="mb-1">
            <a href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a> подписался на хештег <a href="<?= $data['topic']['url'] ?>">#<?= $data['topic']['title'] ?></a>
        </p>
        <span class="text-muted">
            <?= $activity['created_at__humanized'] ?>
        </span>
    </td>
</tr>
