
<!-- activity f_h_added_q -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block size-4 mt-1" href="#">
            <img class="size-4 rounded" src="http://octoanswers.com/uploads/avatar/0_100.jpg">
        </a>
    </div>
    <div class="width-full">
        <div class="color-gray-700">
            Undefined activity type
        </div>
        <pre class="mt-2 mb-0 alert alert-warning small"><?= $activity['activity_type']."\n\n".print_r($activity, true) ?></pre>
    </div>
</div>
<!-- / activity f_h_added_q -->
