
<div class="block mt-md-4 mb-md-4">
    <div class="pl-md-4 pt-md-3 pr-md-4 pb-md-2">
        <a class="d-inline-block wh-2 mr-2" href="<?= $data['user']['profile_url'] ?>">
            <img class="wh-2 rounded-circle" src="<?= $data['user']['avatar_xs_url'] ?>">
        </a>
        <a href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a>
    </div>
    <div class="border-top border-bottom pl-md-4 pr-md-4 pt-3 pb-3">
        <p class="mb-1 text-secondary">Переименовал вопрос <strong><?= $data['question']['title_old'] ?></strong> →</p>
        <p class="mb-0">
            <a class="h4 link-inverted no-underline" href="<?= $data['question']['url'] ?>">
                <?= $data['question']['title_new'] ?>
            </a>
        </p>
    </div>
    <div class="pl-md-4 pb-md-2 pr-md-4 pt-md-2">
        <span class="text-muted"><small><?= $activity['created_at__humanized'] ?></small></span>
    </div>
</div>
