<nav class="mt-2 mb-5">
    <div class="semi-small font-weight-bold text-uppercase text-primary mb-3">
        <?= __('page_questions.filters.title') ?>
    </div>

    <ul class="list-unstyled semi-small">
        <li class="my-2">
            <a class="text-dark text-decoration-none <?= ($this->list == 'with-answers') ? 'text-secondary' : '' ?>" href="<?= \Helper\URL\Questions::getNewestURL($this->lang) ?>">
                <?= __('page_questions.filters.newest') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none <?= ($this->list == 'recently_updated') ? 'text-secondary' : '' ?>" href="<?= \Helper\URL\Questions::getRecentlyUpdatedURL($this->lang) ?>">
                <?= __('page_questions.filters.recently_updated') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none <?= ($this->list == 'popular') ? 'text-secondary' : '' ?>" href="#">
                <?= __('page_questions.filters.popular') ?>
            </a>
        </li>
    </ul>
</nav>