<?php require_once TEMPLATE_PATH . '/questions/main/nav.phtml' ?>

<?php if (count($this->questions)) : ?>
<?php foreach ($this->questions as $question) : ?>
<?php require __DIR__ . '/main/item_question.phtml'; ?>
<?php endforeach; ?>
<?php endif; ?>

<?php if (isset($this->nextPageURL)) : ?>
<div class="my-5">
	<a class="btn btn-primary" href="<?= $this->nextPageURL ?>">
		<?= $this->translator->get('questions', 'more_questions') ?>&nbsp;<i class="material-icons md-24">navigate_next</i>
	</a>
</div>
<?php endif; ?>