
<?php require_once TEMPLATE_PATH.'/questions/main/nav.phtml' ?>

<?php if (count($this->questions)): ?>
	<?php foreach ($this->questions as $question): ?>
		<?php require TEMPLATE_PATH.'/_common/item/question_with_answer.phtml'; ?>
	<?php endforeach; ?>
<?php endif; ?>

<?php if (isset($this->nextPageURL)): ?>
	<div class="my-5">
		<a class="btn btn-primary btn-block" href="<?= $this->nextPageURL ?>"><?= $this->translator->get('More questions') ?></a>
	</div>
<?php endif; ?>
