<!-- question item -->
<?php if (count($this->questions)) : ?>
    <?php foreach ($this->questions as $question_item) : ?>

        <?php $question = $question_item['question'] ?>
        <?php $categories = $question_item['categories'] ?>
        <?php $contributors = $question_item['contributors'] ?>

        <!-- question item -->
        <div class="border rounded bg-white p-3 my-4">

            <?php if (count($categories)) : ?>
                <div class="mb-2">
                    <?php foreach ($categories as $category) : ?>
                        <a class="small text-black-50 text-decoration-none" href="<?= $category->get_URL($this->lang) ?>">
                            <?= $category->title ?>
                        </a>
                        <span class="semi-small text-black-50">
                            &middot;
                        </span>
                    <?php endforeach; ?>
                    <a class="small text-black-50 text-decoration-none" href="<?= $question->get_URL($this->lang) ?>">
                        <?= $this->translator->get('main', 'item__top_question', 'more') ?>
                    </a>
                </div>
            <?php endif; ?>

            <div class="mb-3">
                <a class="font-size-140 line-height-13 text-dark font-weight-bold text-decoration-none" href="<?= $question->get_URL($this->lang) ?>">
                    <?= $question->title ?>
                </a>
            </div>

            <!-- question image -->
            <?php if ($question->imageBaseName) : ?>
                <a class="d-block my-3" href="<?= $question->get_URL($this->lang) ?>">
                    <img class="img-fluid" src="<?= $question->get_image_URL_medium($this->lang) ?>" alt="<?= $question->title ?>">
                </a>
            <?php endif; ?>
            <!-- / question image -->

            <!-- answer text -->
            <?php if (mb_strlen($question->answer->text)) : ?>
                <div class="my-3">
                    <?= mb_substr($question->answer->text, 0, 150) ?><?= (mb_strlen($question->answer->text) > 150) ? '&hellip;' : '' ?>
                    <?php if (mb_strlen($question->answer->text) > 150) : ?>
                        <a class="text-secondary semi-small my-3" href="<?= $question->get_URL($this->lang) ?>">
                            (<?= $this->translator->get('main', 'item__top_question', 'read_more') ?>)
                        </a>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <!-- / answer text -->

            <div class="mt-3">

                <?php if (count($contributors)) : ?>
                    <span class="mr-3">
                        <?php foreach ($contributors as $contributor) : ?>
                            <a class="wh-24px rounded-circle" href="<?= $contributor->get_URL($this->lang) ?>"><img src="<?= $contributor->get_avatar_URL_medium() ?>" class="wh-28px rounded-circle" alt="<?= $contributor->name ?>" title="<?= $contributor->name ?>"></a>
                        <?php endforeach; ?>
                        <!-- <a class="semi-small text-black-50" href="#">
                        +2
                    </a> -->
                    </span>
                <?php endif; ?>

                <!-- time to read -->
                <?php if (strlen($question->answer->text)) : ?>
                    <span class="semi-small text-black-50">
                        <i class="material-icons md-14">subject</i>
                        <?= $question->get_minutes_to_read() ?>&nbsp;<?= $this->translator->get('min') ?>
                    </span>
                <?php endif; ?>
                <!-- / time to read -->

                <span class="mx-1">&middot;</span>

                <span class="semi-small text-black-50">
                    <i class="material-icons md-14">edit</i>
                    <?= \Humanizer\DateTime::humanize_timestamp($this->lang, $question->answer->updatedAt) ?>
                </span>

            </div>
        </div>
        <!-- / question item -->

    <?php endforeach; ?>
<?php endif; ?>
<!-- / question item -->