<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-8 col-xl-8">
                <?php require_once TEMPLATE_PATH.'/questions/show_list/nav.phtml' ?>

                <?php if (count($this->questions)): ?>
                    <?php foreach ($this->questions as $question): ?>
                        <?php require TEMPLATE_PATH.'/_common/item/question_with_answer.phtml'; ?>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php if (isset($this->nextPageURL)): ?>
                    <div class="my-5">
                        <a class="btn btn-primary btn-block" href="<?= $this->nextPageURL ?>"><?= _('Questions - Next button') ?></a>
                    </div>
                <?php endif; ?>
            </div>
            <div class="col-12 col-md-4 col-xl-4">
                <?php require_once TEMPLATE_PATH.'/questions/show_list/sandbox_questions.phtml' ?>

                <?php require_once TEMPLATE_PATH.'/_common/sidebar/social_groups.phtml' ?>
                <?php require_once TEMPLATE_PATH.'/_common/sidebar/footer.phtml' ?>
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
