<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/common/navbar.phtml'; ?>

    <div class="container-fluid">
        <div class="row">

            <div class="col-12 max-width-md mx-auto">
                <?php require_once TEMPLATE_PATH.'/questions/show_list/nav.phtml' ?>

                <?php if (count($this->questions)): ?>
                    <?php foreach ($this->questions as $question): ?>
                        <?php require TEMPLATE_PATH.'/common/item/question_with_answer.phtml'; ?>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php if (isset($this->nextPageURL)): ?>
                    <div class="mb-5 mt-5 text-center">
                        <a class="btn btn-primary w-50" href="<?= $this->nextPageURL ?>"><?= $this->l->t('questions', 'next_btn') ?></a>
                    </div>
                <?php endif; ?>
            </div>

        </div>
    </div>

    <?php require_once TEMPLATE_PATH.'/common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH.'/common/js_bottom.phtml'; ?>
</body>
</html>
