
<!-- question item -->

<div class="my-4">
    <a class="lead color-secondary-dark-3 text-decoration-none" href="<?= $question->getURL($this->lang) ?>">
        <?= $question->title ?>
    </a>
    <div class="small color-secondary-light-1">

        <?php if (strlen($question->answer->text) == 0): ?>
            <a rel="nofollow" href="<?= $question->getEditURL($this->lang) ?>">
                <?= $this->translator->get('sandbox', 'btn_write_answer') ?>
            </a>
            <span class="mx-1 color-secondary-dark-4 font-weight-bold">&middot;</span>
        <?php endif; ?>

        <?php if ($question->categoriesCount == 0): ?>
            <a rel="nofollow" href="<?= $question->getUpdateCategoriesURL($this->lang) ?>">
                <?= $this->translator->get('sandbox', 'btn_add_categories') ?> 
            </a>
            <span class="mx-1 color-secondary-dark-4 font-weight-bold">&middot;</span>
        <?php endif; ?>

        <?= $this->translator->get('sandbox', 'answer_updated') ?> <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->answer->updatedAt) ?>

    </div>
</div>

<!-- / question item -->
