
<ul class="nav nav-tabs my-4">
    <li class="nav-item">
        <a class="nav-link <?= ($this->list == 'without-answers') ? 'active' : '' ?>" href="<?= Sandbox_URL_Helper::getWithoutAnswersURL($this->lang) ?>">
            <?= _('Questions without answer') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?= ($this->list == 'without_hashtags') ? 'active' : '' ?>" href="<?= Sandbox_URL_Helper::getWithoutHashtagsURL($this->lang) ?>">
            <?= _('Without hashtags') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?= ($this->list == 'newest') ? 'active' : '' ?>" href="<?= Sandbox_URL_Helper::getAllURL($this->lang) ?>">
            <?= _('All') ?>
        </a>
    </li>
</ul>
