
<?php if (count($this->related_topics)): ?>

    <!-- related_topics -->
    <div class="box my-4">
        <div class="box-header">
            <a class="font-weight-bold color-gray-800" href="#">
                Похожие темы
            </a>
        </div>
        <div class="box-body pt-4 pb-0">
            <?php foreach ($this->related_topics as $topic): ?>
                <a class="badge badge-secondary mr-2 mb-3" href="<?= $topic->getURL($this->lang) ?>">
                    <?= $topic->getTitle() ?>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
    <!-- / related_topics -->
<?php else: ?>
    <!-- <div class="alert alert-super" role="alert">
        <img src="/public/img/Ghost-96.png" alt="Нет вопросов в теме «{{ topic.getTitle }}»"/>
        <p><strong>Вопросов нет</strong></p>
        <p>Нет ни одного вопроса относящегося к теме «{{ topic.getTitle }}»</p>
        {% if authUser %}
            <p><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal__ask">Задать вопрос</button></p>
        {% else %}
            <p><button class="btn btn-primary" data-toggle="modal" data-target="#modal__ask_not_logged">Задать вопрос</button></p>
        {% endif %}
    </div> -->
<?php endif; ?>
