<!-- actions_top -->
<div class="mt-2">

    <!-- follow_btn -->
    <?php if ($this->authUser) : ?>
        <button class="btn btn-sm follow_category_button mt-2 mr-2 <?= $this->followed ? 'followed btn-success' : 'btn-outline-primary'; ?>" data-category-id="<?= $this->category->id ?>" data-follow-title="<?= __('common.btn.follow') ?>" data-followed-title="<?= __('common.btn.followed') ?>" data-unfollow-title="<?= __('common.btn.unfollow') ?>" type="button">
            <?= $this->followed ? __('common.btn.followed') : __('common.btn.follow'); ?>
        </button>
    <?php else : ?>
        <button type="button" class="btn btn-sm btn-outline-gray mt-2 mr-2" data-container="body" data-toggle="popover" data-placement="top" data-content="<?= __('category.actions.follow_lure') ?>" data-trigger="focus">
            <?= __('common.btn.follow'); ?>
        </button>
    <?php endif; ?>
    <!-- / follow_btn -->

    <!-- more dropdown -->
    <div class="dropdown d-inline">
        <a href="#" class="text-black-50 my-2 ml-3 float-lg-right" id="dropdown-menu-more" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons md-18">more_horiz</i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-menu-more">

            <?php if ($this->authUser) : ?>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#modal_rename_category">
                    <?= __('page_category.actions.rename_category') ?>
                </a>
            <?php endif; ?>

            <a href="#" class="dropdown-item disabled" rel="nofollow">
                <?= __('page_category.actions.report') ?>
            </a>

            <div class="dropdown-divider"></div>

            <a class="dropdown-item disabled" target="_blank" href="#">
                <?= __('page_category.actions.discuss_a_category') ?>
            </a>

        </div>
    </div>
    <!-- / more dropdown -->

    <!-- share dropdown -->
    <div class="dropdown d-none d-lg-inline">
        <a href="#" class="text-black-50 my-2 float-right" id="dropdown-menu-share" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="material-icons md-18">share</i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-menu-share">
            <p class="dropdown-header"><?= __('page_question.actions_top.share__title') ?></p>

            <script src="https://yastatic.net/share2/share.js"></script>


            <div id="my-share" class="ya-share2" style="min-height: 24px;" data-services="facebook,twitter,vkontakte,pinterest,digg,reddit,pocket,delicious"></div>

            <script>
                var share = Ya.share2('my-share', {
                    content: {
                        url: '<?= $this->share_link['url'] ?>',
                        title: '<?= $this->share_link['title'] ?>',
                        description: '<?= $this->share_link['description'] ?>',
                        image: '<?= $this->share_link['image'] ?>'
                    },
                    theme: {
                        lang: 'en',
                        size: 'm',
                        bare: false,
                        copy: 'last',
                        direction: 'vertical'
                    }
                });
            </script>

            <style>
                .ya-share2__link {
                    margin-top: 8px;
                    padding-left: 24px;
                }
            </style>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item semi-small" href="#">
                <?= __('page_question.actions_top.share__copy_link') ?>
            </a>
        </div>
    </div>
    <!-- / share dropdown -->

</div>
<!-- / actions_top -->