<!-- improve_feed -->

<nav class="mt-2 mb-4">
    <div class="semi-small font-weight-bold text-uppercase text-primary mb-3">
        <?= __('page_feed.improve_your_feed.title') ?>
    </div>

    <ul class="list-unstyled semi-small">

        <li class="my-3">
            <i class="material-icons md-18 mr-1 text-success">check</i>
            <span class="text-black-50">
                <?= __('page_feed.improve_your_feed.visit_your_feed') ?>
            </span>
        </li>

        <li class="my-3">
            <?php if ($this->authUser->username == $this->authUser->name) : ?>
                <i class="material-icons md-18 mr-1 text-warning">play_arrow</i>
                <a class="text-secondary text-decoration-none" href="<?= \Helper\URL\Settings::getRealNameURL($this->lang) ?>">
                    <?= __('page_feed.improve_your_feed.set_real_name') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 mr-1 text-success">check</i>
                <span class="text-black-50">
                    <?= __('page_feed.improve_your_feed.set_real_name') ?>
                </span>
            <?php endif; ?>
        </li>

        <li class="my-3">
            <?php if (strlen($this->authUser->signature) == 0) : ?>
                <i class="material-icons md-18 mr-1 text-warning">play_arrow</i>
                <a class="text-secondary text-decoration-none" href="<?= \Helper\URL\Settings::getSignatureURL($this->lang) ?>">
                    <?= __('page_feed.improve_your_feed.set_signature') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 mr-1 text-success">check</i>
                <span class="text-black-50">
                    <?= __('page_feed.improve_your_feed.set_signature') ?>
                </span>
            <?php endif; ?>
        </li>

        <li class="my-3">
            <?php if ($this->isShowCategoriesFollowLure) : ?>
                <i class="material-icons md-18 mr-1 text-warning">play_arrow</i>
                <a class="text-secondary text-decoration-none" href="<?= \Helper\URL\Categories::getNewestURL($this->lang) ?>">
                    <?= __('page_feed.improve_your_feed.follow_3_more_categories') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 mr-1 text-success">check</i>
                <span class="text-black-50">
                    <?= __('page_feed.improve_your_feed.follow_3_more_categories') ?>
                </span>
            <?php endif; ?>
        </li>

        <li class="my-3">
            <?php if ($this->isShowQuestionsFollowLure) : ?>
                <i class="material-icons md-18 mr-1 text-warning">play_arrow</i>
                <a class="text-secondary text-decoration-none" href="<?= \Helper\URL\Questions::getNewestURL($this->lang) ?>">
                    <?= __('page_feed.improve_your_feed.follow_your_first_question') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 mr-1 text-success">check</i>
                <span class="text-black-50">
                    <?= __('page_feed.improve_your_feed.follow_your_first_question') ?>
                </span>
            <?php endif; ?>
        </li>

        <li class="my-3">
            <?php if ($this->isShowUsersFollowLure) : ?>
                <i class="material-icons md-18 mr-1 text-warning">play_arrow</i>
                <a class="text-secondary text-decoration-none" href="<?= \Helper\URL\Users::getNewestURL($this->lang) ?>">
                    <?= __('page_feed.improve_your_feed.find_your_friends') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 mr-1 text-success">check</i>
                <span class="text-black-50">
                    <?= __('page_feed.improve_your_feed.find_your_friends') ?>
                </span>
            <?php endif; ?>
        </li>

        <!-- <?= __('page_feed.ask_your_first_question') ?> -->
        <!-- <?= __('page_feed.answer_a_question') ?> -->

    </ul>
</nav>
<!-- / flow_filter -->