<?php if (isset($this->question->answer) && !$this->question->answer->text) : ?>

    <!-- lure be_first_contributor -->
    <div class="border-top py-2 py-sm-3 mt-2 mb-4">
        <div class="text-dark font-weight-bold mb-2">
            <?= __('page_question.lure_be_first_contributor.title') ?>
        </div>
        <div class="semi-small text-muted mb-3">
            <?= __('page_question.lure_be_first_contributor.message') ?>
        </div>
        <a class="btn btn-sm btn-outline-primary" href="<?= $this->question->getEditURL($this->lang) ?>">
            <?= __('page_question.lure_be_first_contributor.btn_write') ?>
        </a>
    </div>
    <!-- / lure be_first_contributor -->

<?php endif; ?>