
<div class="border-bottom py-4 pb-lg-5">
    <div class="container-fluid">
        <div class="row ">
            <div class="col-12 col-sm-11 col-md-10 col-lg-9 mx-auto">
                <p class="lead text-muted mb-1"><?= $this->l->t('answer_history__subtitle') ?></p>
                <h1 class="h2 mt-0">
                    <a class="link-inverted no-underline" href="<?= $this->question->getURL($this->lang) ?>">
                        <?= $this->question->getTitle() ?>
                    </a>
                </h1>
                <a class="btn btn-sm btn-outline-secondary mt-2" role="button" href="<?= $this->question->getURL($this->lang) ?>">
                    <?= $this->l->t('answer_history__back_to_question') ?>
                </a>
            </div>
        </div>
    </div>
</div>
