
<div class="my-5">
    <div class="mb-3">
        <div class="pt-1 float-left">
            <a class="size-6" href="<?= ($this->users[$i])->getURL($this->lang) ?>">
                <img class="size-6 rounded-circle" src="<?= ($this->users[$i])->getAvatarSmallURL() ?>">
            </a>
        </div>
        <div class="ml-8">
            <div class="">
                <a class="font_weight_600 small mr-1" href="<?= ($this->users[$i])->getURL($this->lang) ?>">
                    <?= $this->users[$i]->getName() ?>
                </a>
            </div>
            <span class="small color-gray-600">
                <?= _('Answer history page - Change ID') ?> #<?= $this->revisions[$i]->getID() ?>
                <span class="color-gray-900 font_weight_800">&middot;</span>
                <?php if ($this->revisions[$i]->getComment()): ?>
                    <?= _('Answer history page - Description of changes') ?>: <?= $this->revisions[$i]->getComment() ?>
                <?php else: ?>
                    <?= _('Answer history page - No description of changes') ?>
                <?php endif; ?>
                <span class="color-gray-900 font_weight_800">&middot;</span>
                <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $this->revisions[$i]->getCreatedAt()) ?>
            </span>
        </div>
    </div>
    <pre><?= FineDiff::renderDiffToHTMLFromOpcodes($this->revisions[$i]->getBaseText(), $this->revisions[$i]->getOpcodes()) ?></pre>
</div>
