<!-- improve_feed -->

<nav class="mt-2 mb-4">
    <div class="semi-small font-weight-bold text-uppercase text-primary mb-3">
        <?= $this->translator->get('feed', 'improve_your_feed', 'title') ?>
    </div>

    <ul class="list-unstyled semi-small">
        <li class="my-2">
            <i class="material-icons md-18 mr-1 text-success">check</i>
            <span class="text-black-50">
                <?= $this->translator->get('feed', 'improve_your_feed', 'visit_your_feed') ?>
            </span>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none" href="#">
                <?= $this->translator->get('flow', 'new_questions') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none" href="#">
                <?= $this->translator->get('flow', 'editing_answers') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none" href="#">
                <?= $this->translator->get('flow', 'add_to_friends') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none" href="#">
                <?= $this->translator->get('flow', 'new_categories') ?>
            </a>
        </li>
    </ul>
</nav>
<!-- / flow_filter -->


<div class="d-none d-md-block">
    <div class="font-weight-bold text-dark">
    </div>
    <div class="pt-0 pb-0 small">


        <div class="my-3">
            <?php if ($this->authUser->username == $this->authUser->name) : ?>
                <a class="text-dark text-decoration-none" href="<?= \Helper\URL\Settings::get_real_name_URL($this->lang) ?>">
                    <?= $this->translator->get('feed', 'improve_your_feed', 'set_real_name') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 w-28px color-success">check</i>
                <span class="text-secondary">
                    <s>
                        <?= $this->translator->get('feed', 'improve_your_feed', 'set_real_name') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if (strlen($this->authUser->signature) == 0) : ?>
                <a class="text-dark text-decoration-none" href="<?= \Helper\URL\Settings::get_signature_URL($this->lang) ?>">
                    <?= $this->translator->get('feed', 'improve_your_feed', 'set_signature') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 w-28px color-success">check</i>
                <span class="text-secondary">
                    <s>
                        <?= $this->translator->get('feed', 'improve_your_feed', 'set_signature') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if ($this->isShowCategoriesFollowLure) : ?>
                <a class="text-dark text-decoration-none" href="<?= \Helper\URL\Categories::get_newest_URL($this->lang) ?>">
                    <?= $this->translator->get('feed', 'improve_your_feed', 'follow_3_more_categories') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 w-28px color-success">check</i>
                <span class="text-secondary">
                    <s>
                        <?= $this->translator->get('feed', 'improve_your_feed', 'follow_3_more_categories') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if ($this->isShowQuestionsFollowLure) : ?>
                <a class="text-dark text-decoration-none" href="<?= \Helper\URL\Questions::get_newest_URL($this->lang) ?>">
                    <?= $this->translator->get('feed', 'improve_your_feed', 'follow_your_first_question') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 w-28px color-success">check</i>
                <span class="text-secondary">
                    <s>
                        <?= $this->translator->get('feed', 'improve_your_feed', 'follow_your_first_question') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if ($this->isShowUsersFollowLure) : ?>
                <a class="text-dark text-decoration-none" href="<?= \Helper\URL\Users::get_newest_URL($this->lang) ?>">
                    <?= $this->translator->get('feed', 'improve_your_feed', 'find_your_friends') ?>
                </a>
            <?php else : ?>
                <i class="material-icons md-18 w-28px color-success">check</i>
                <span class="text-secondary">
                    <s>
                        <?= $this->translator->get('feed', 'improve_your_feed', 'find_your_friends') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <!-- <div class="my-3">
            <i class="material-icons md-18 w-28px color-success">check</i>
            <span class="text-secondary">
                <s>
                    <?= $this->translator->get('feed', 'ask_your_first_question') ?>
                </s>
            </span>
        </div>

        <div class="my-3">
            <i class="material-icons md-18 w-28px color-success">check</i>
            <span class="text-secondary">
                <s>
                    <?= $this->translator->get('feed', 'answer_a_question') ?>
                </s>
            </span>
        </div> -->

    </div>
</div>
<!-- / improve_feed -->