
<?php include_once TEMPLATE_PATH.'/feed/main/ask_question.phtml'; ?>

<?php include_once TEMPLATE_PATH.'/feed/main/lure/set_real_name.phtml'; ?>
<?php include_once TEMPLATE_PATH.'/feed/main/lure/set_signature.phtml'; ?>
<?php include_once TEMPLATE_PATH.'/feed/main/lure/follow_3_categories.phtml'; ?>
<?php include_once TEMPLATE_PATH.'/feed/main/lure/follow_3_questions.phtml'; ?>
<?php include_once TEMPLATE_PATH.'/feed/main/lure/follow_3_users.phtml'; ?>
<?php // include_once TEMPLATE_PATH.'/feed/main/lure/write_answer.phtml';?>

<?php if (isset($this->activities)): ?>
    <?php foreach ($this->activities as $activity):
        switch ($activity['activity_type']) {
            case 'Q_RENAMED_BY_U':
            case 'U_RENAME_Q':
            case 'USER_RENAME_CATEGORY':
            case 'USER_FOLLOW_CATEGORY':
            case 'CATEGORY_ADDED_QUESTION':
            case 'F_U_UPDATE_A':
            case 'F_U_FOLLOW_Q':
            case 'F_U_FOLLOW_U':
            case 'U_UPDATE_SIGNATURE':
            case 'followed_U_asked_Q':
            case 'followed_U_repost_Q':
            case 'followed_H_got_achievement':
            case 'CATEGORY_RENAMED_BY_USER':
                $data = $activity['data'];
                require TEMPLATE_PATH.'/feed/div/'.strtolower($activity['activity_type']).'.phtml';
                break;
            case 'Q_RENAMED_BY_U':
            case 'F_Q_UPDATE_A':
                echo "<!-- Not show: ".$activity['activity_type']." -->";
                break;
            default:
                require TEMPLATE_PATH.'/feed/div/activity_not_found.phtml';
                break;
        };
    endforeach; ?>
<?php endif; ?>

