
<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">

                <?php include_once TEMPLATE_PATH.'/feed/block/ask_question.phtml'; ?>

                <?php include_once TEMPLATE_PATH.'/feed/block/lure/set_real_name.phtml'; ?>
                <?php include_once TEMPLATE_PATH.'/feed/block/lure/set_signature.phtml'; ?>
                <?php include_once TEMPLATE_PATH.'/feed/block/lure/follow_3_topics.phtml'; ?>
                <?php include_once TEMPLATE_PATH.'/feed/block/lure/follow_3_questions.phtml'; ?>
                <?php include_once TEMPLATE_PATH.'/feed/block/lure/follow_3_users.phtml'; ?>
                <?php // include_once TEMPLATE_PATH.'/feed/block/lure/write_answer.phtml'; ?>

                <?php if (isset($this->activities)): ?>
                    <?php foreach ($this->activities as $activity):
                        switch ($activity['activity_type']) {
                            // @TODO Bad
                            case 'Q_RENAMED_BY_U':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/_common/activity/f_q_renamed_by_u.phtml';
                                break;
                            // @TODO Bad
                            case 'U_RENAME_Q':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/_common/activity/f_u_rename_q.phtml';
                                break;
                            // @TODO Bad
                            case 'F_U_FOLLOW_H':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/_common/activity/f_u_follow_t.phtml';
                                break;
                            // @TODO Bad
                            case 'F_H_ADDED_Q':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/_common/activity/f_t_added_q.phtml';
                                break;
                            case 'F_U_UPDATE_A':
                            case 'F_U_FOLLOW_Q':
                            case 'F_U_FOLLOW_U':
                            case 'U_RENAME_Q':
                            case 'U_UPDATE_SIGNATURE':
                            case 'followed_U_asked_Q':
                            case 'followed_U_repost_Q':
                            case 'followed_H_got_achievement':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/feed/div/'.strtolower($activity['activity_type']).'.phtml';
                                break;
                            case 'Q_RENAMED_BY_U':
                            case 'F_Q_UPDATE_A':
                                echo "<!-- Not show: ".$activity['activity_type']." -->";
                                break;
                            default:
                                require TEMPLATE_PATH.'/feed/div/activity_not_found.phtml';
                                break;
                        };
                    endforeach; ?>
                <?php endif; ?>

            </div>
            <div class="col-12 col-md-4">
                <?php include_once TEMPLATE_PATH.'/feed/block/improve_feed.phtml'; ?>
                <?php require_once TEMPLATE_PATH.'/_common/sidebar/footer.phtml' ?>
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
