<div class="border align-middle rounded bg-white p-3">
    <?php if ($this->authUser) : ?>
        <a class="d-inline-block wh-20px rounded mr-1" href="<?= $this->authUser->get_URL($this->lang) ?>">
            <img class="d-inline-block wh-20px rounded" style="margin-top: -2px;" src="<?= $this->authUser->get_avatar_URL_small() ?>">
        </a>

        <a class="text-black-50 line-height-10" href="<?= \Helper\URL\Page::get_ask_URL($this->lang) ?>">
            <?= __('page_feed.what_is_your_question') . ', ' . $this->authUser->name . '?' ?>
        </a>
    <?php else : ?>
        <a class="text-black-50 line-height-10" href="<?= \Helper\URL\Page::get_ask_URL($this->lang) ?>">
            <?= __('page_feed.what_is_your_question') . '?' ?>
        </a>
    <?php endif; ?>
</div>