<!-- USER RESET PASSWORD POPUP -->
<div class="modal fade" id="userResetPasswordModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="form_user_reset_password">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Сброс пароля</h4>
                </div>
                <div class="modal-body">
                    <div id="form_user_reset_password-email-group" class="form-group">
                        <input name="form_user_reset_password-email" type="email" class="form-control" placeholder="Email вашего аккаунта">
                        <!-- errors will go here -->
                    </div>
                </div>
                <div class="modal-footer">
                    <p>
                        <button type="submit" id="form_user_reset_password-submit_button" class="btn btn-default ladda-button" data-style="zoom-out" data-spinner-size="30"><span class="ladda-label">Отправить пароль на email</span></button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Отмена</button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- / USER RESET PASSWORD POPUP -->
