<!DOCTYPE html>
<html lang="<?= $this->lang ?>" <?= isset($this->htmlAttr) ? $this->htmlAttr : '' ?>>

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body <?= isset($this->bodyAttr) ? ' ' . $this->bodyAttr : '' ?>>

    <?php require_once TEMPLATE_PATH . '/_common/navbar.phtml'; ?>

    <?php require_once __DIR__ . '/jumbotron.phtml' ?>

    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-2">
                <?php require_once __DIR__ . '/sections.phtml' ?>
                <?php require_once __DIR__ . '/other_languages.phtml'; ?>
            </div>
            <div class="col-12 col-lg-7">

                <div class="border p-3 bg-white">
                    <?= $this->translator->get('main', 'top_content', 'title') ?>
                    <a class="float-right text-black-50 text-decoration-none" href="#">
                        <?= $this->translator->get('main', 'top_content', 'view_all') ?>
                    </a>
                </div>

                <?php require_once __DIR__ . '/recent_questions.phtml' ?>
            </div>
            <div class="d-none d-md-block col-lg-3">
                <div class="border p-3 bg-white">
                    Top content on Answeropedia
                </div>

                <?php require_once __DIR__ . '/how_it_works.phtml' ?>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-9 mx-auto">
                <?php require_once __DIR__ . '/share.phtml' ?>
            </div>
        </div>
    </div>



    <?php require TEMPLATE_PATH . '/_common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH . '/_common/modals.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>

</body>

</html>