<!DOCTYPE html>
<html lang="<?= $this->lang ?>" <?= isset($this->htmlAttr) ? $this->htmlAttr : '' ?>>

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body <?= isset($this->bodyAttr) ? ' ' . $this->bodyAttr : '' ?>>

    <?php require_once TEMPLATE_PATH . '/_common/navbar.phtml'; ?>

    <?php require_once __DIR__ . '/jumbotron.phtml' ?>

    <div class="container">
        <div class="row">
            <div class="d-none d-lg-block col-12 col-lg-2">
                <?php require_once TEMPLATE_PATH . '/_common/left/sections.phtml'; ?>
                <?php require_once __DIR__ . '/other_languages.phtml'; ?>
            </div>
            <div class="col-12 col-lg-7">
                <?php require_once __DIR__ . '/recent_questions.phtml' ?>
            </div>
            <div class="d-none d-md-block col-lg-3">
                <?php require_once __DIR__ . '/how_it_works.phtml' ?>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-2">
                <!-- x -->
            </div>
            <div class="col-12 col-lg-7">
                <?php require_once __DIR__ . '/share.phtml' ?>
            </div>
            <div class="d-none d-md-block col-lg-3">
                <!-- x -->
            </div>
        </div>
    </div>

    <?php require TEMPLATE_PATH . '/_common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH . '/_common/modals.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>

</body>

</html>