<!DOCTYPE html>
<html lang="<?= $this->lang ?>" <?= isset($this->htmlAttr) ? $this->htmlAttr : '' ?>>

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body <?= isset($this->bodyAttr) ? ' ' . $this->bodyAttr : '' ?>>

    <?php require_once TEMPLATE_PATH . '/_common/navbar.phtml'; ?>
    <?php require_once TEMPLATE_PATH . '/_common/navbar_subnav.phtml'; ?>

    <?php require_once __DIR__ . '/jumbotron.phtml' ?>
    <?php require_once __DIR__ . '/how_it_works.phtml' ?>

    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-7 py-3 py-md-4 ml-auto">
                <?php require_once __DIR__ . '/recent_questions.phtml' ?>
            </div>
            <div class="d-none d-md-block col-lg-2 py-md-3 mr-auto">
                <?php require __DIR__ . '/other_languages.phtml'; ?>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-9 mx-auto">
                <?php require_once __DIR__ . '/share.phtml' ?>
            </div>
        </div>
    </div>

    <?php require TEMPLATE_PATH . '/_common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH . '/_common/modals.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>

</body>

</html>