<!-- how_it_works -->
<div class="border rounded p-3 pt-2 bg-white">

	<div class="semi-small font-weight-bold text-uppercase text-black mb-3">
		<?= $this->translator->get('main', 'how_it_works', 'title') ?>
	</div>

	<p class="text-muted semi-small mb-3">
		<span class="text-dark font-weight-bold">1.</span>
		<?= $this->translator->get('main', 'how_it_works', 'step_1_msg') ?>
	</p>

	<p class="text-muted semi-small mb-3">
		<span class="text-dark font-weight-bold">2.</span>
		<?= $this->translator->get('main', 'how_it_works', 'step_2_msg') ?>
	</p>

	<p class="text-muted semi-small mb-3">
		<span class="text-dark font-weight-bold">3.</span>
		<?= $this->translator->get('main', 'how_it_works', 'step_3_msg') ?>
	</p>

	<!-- 
	<?php if ($this->question_about_answeropedia) : ?>
		<a href="<?= $this->question_about_answeropedia->get_URL($this->lang) ?>" class="text-dark text-decoration-none">
			<?= $this->translator->get('navbar_subnav', 'how_it_works') ?>
		</a>
	<?php endif; ?>
	 -->

	<a class="btn btn-secondary btn-block mt-4" href="#" data-toggle="modal" data-target="#modal_signup">
		<i class="material-icons md-18 mr-1">input</i>
		<?= $this->translator->get('question', 'lure_first_answer', 'signup') ?>
	</a>

</div>
<!-- / how_it_works -->