<!-- jumbotron -->

<div class="container bg-white my-4">
    <div class="row main-page-jumbotron border rounded">
        <div class="col-12 py-3 py-md-5">

            <h1 class="jumbotron-title text-md-center my-4">
                <?= $this->translator->get('main', 'jumbotron', 'header_1') ?><br>
                <span class="font-weight-light"><?= $this->translator->get('main', 'jumbotron', 'header_2') ?></span>
            </h1>

            <div class="lead d-none d-md-block text-md-center text-black-50 my-3 py-md-2">
                <?= $this->translator->get('main', 'jumbotron', 'text') ?>
            </div>

            <div class="text-md-center mr-5">
                <a class="btn btn-lg btn-primary mr-4" href="#" data-toggle="modal" data-target="#modal_signup">
                    <?= $this->translator->get('main', 'jumbotron', 'btn_get_started') ?>
                </a>
                <a class="text-dark" href="#">
                    <?= $this->translator->get('main', 'jumbotron', 'btn_learn_more') ?>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- / jumbotron -->