<!-- jumbotron -->
<div class="container my-4">
    <div class="row">
        <div class="col-12">
            <div class="bg-white border rounded p-3 py-lg-5 pr-lg-5">

                <!-- H1 for desktop -->
                <h1 class="font-ubuntu text-primary jumbotron-title text-md-center">
                    <?= __('common.answeropedia') ?><br />
                </h1>
                <!-- / H1 for desktop -->

                <div class="lead text-md-center text-black-50 mt-1 mb-4">
                    <?= __('page_main.jumbotron.text') ?>
                </div>

                <div class="text-md-center mr-lg-5">

                    <!-- Button "get started" for mobile -->
                    <button class="btn btn-lg btn-block btn-primary d-inline-block d-md-none" role="button" href="<?= \Helper\URL\Page::getAskURL($this->lang) ?>">
                        <i class="material-icons md-18 font-weight-bold">add</i>
                        <?= __('page_main.jumbotron.btn_ask') ?>
                    </button>
                    <!-- / Button "get started" for mobile -->

                    <!-- Button "get started" for desktop -->
                    <a class="btn btn-lg btn-lg-block btn-primary d-none d-md-inline-block mr-3 mr-lg-4" role="button" href="<?= \Helper\URL\Page::getAskURL($this->lang) ?>">
                        <i class="material-icons md-18 font-weight-bold">add</i>
                        <?= __('page_main.jumbotron.btn_ask') ?>
                    </a>
                    <!-- / Button "get started" for desktop -->

                    <?php if ($this->question_about_answeropedia) : ?>
                        <a class="d-none d-md-inline text-dark" href="<?= $this->question_about_answeropedia->getURL($this->lang) ?>">
                            <?= __('page_main.jumbotron.btn_learn_more') ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- / jumbotron -->