<!-- sidebar other_languages -->

<nav class="mb-4">
	<div class="text-uppercase text-secondary mb-3">
		<?= $this->translator->get('other_languages', 'title') ?>
	</div>
	<ul class="list-links">
		<li>
			<a data-lang="ru" href="<?= Page_URL_Helper::get_main_URL('en') ?>">
				<?= $this->translator->get('other_languages', 'english') ?>
			</a>
		</li>
		<li>
			<a data-lang="ru" href="<?= Page_URL_Helper::get_main_URL('ru') ?>">
				<?= $this->translator->get('other_languages', 'russian') ?>
			</a>
		</li>
		<li class="font-weight-bold">
			<a href="<?= SITE_URL ?>">
				<?= $this->translator->get('other_languages', 'all_languages') ?>
			</a>
		</li>
	</ul>
</nav>

<!-- / sidebar other_languages -->