<!-- sidebar other_languages -->
<nav class="my-5">
	<div class="semi-small font-weight-bold text-uppercase text-primary mb-3">
		<?= __('common.other_languages.title') ?>
	</div>

	<ul class="list-unstyled semi-small">
		<li class="my-2">
			<a class="text-dark text-decoration-none" data-lang="ru" href="<?= \Helper\URL\Page::getMainURL('en') ?>">
				<?= __('common.other_languages.english') ?>
			</a>
		</li>
		<li class="my-2">
			<a class="text-dark text-decoration-none" data-lang="ru" href="<?= \Helper\URL\Page::getMainURL('ru') ?>">
				<?= __('common.other_languages.russian') ?>
			</a>
		</li>
		<li class="my-2">
			<a class="text-secondary text-decoration-none" href="<?= SITE_URL ?>">
				<?= __('common.other_languages.all_languages') ?>
			</a>
		</li>
	</ul>
</nav>
<!-- / sidebar other_languages -->