<?php if (isset($this->top_questions) && count($this->top_questions)) : ?>

    <!-- Title for mobile -->
    <div class="d-block d-md-none semi-small font-weight-bold text-uppercase text-black-50 pl-2 mt-4">
        <?= __('page_main.top_content.title_mobile') ?>
    </div>
    <!-- / Title for mobile -->

    <!-- Title for desktop -->
    <div class="d-none d-md-block  border rounded p-3 bg-white">
        <?= __('page_main.top_content.title') ?>

        <a class="float-right text-black-50 text-decoration-none" href="#">
            <?= __('page_main.top_content.view_all') ?>
        </a>
    </div>
    <!-- / Title for desktop -->

    <?php foreach ($this->top_questions as $topQuestion) : ?>

        <?php $question = $topQuestion['question'] ?>
        <?php $categories = $topQuestion['categories'] ?>
        <?php $contributors = $topQuestion['contributors'] ?>
        <?php $last_contributor = $topQuestion['last_contributor'] ?>

        <!-- question item -->
        <div class="border rounded bg-white p-3 my-4">

            <?php if (count($categories)) : ?>
                <div class="mb-2">
                    <?php foreach ($categories as $category) : ?>
                        <a class="small text-black-50 text-decoration-none" href="<?= $category->getURL($this->lang) ?>">
                            <?= $category->title ?>
                        </a>
                        <span class="semi-small text-black-50">
                            &middot;
                        </span>
                    <?php endforeach; ?>
                    <a class="small text-black-50 text-decoration-none" href="<?= $question->getURL($this->lang) ?>">
                        <?= __('page_main.item__top_question.more') ?>
                    </a>
                </div>
            <?php endif; ?>

            <div class="mb-3">
                <a class="font-size-140 line-height-13 text-dark font-weight-bold text-decoration-none" href="<?= $question->getURL($this->lang) ?>">
                    <?= $question->title ?>
                </a>
            </div>

            <!-- last_contributor -->
            <?php if (isset($last_contributor)) : ?>

                <div class="media position-relative">
                    <a class="wh-40px mt-1 mr-3 rounded-circle" href="<?= $last_contributor->getURL($this->lang) ?>">
                        <img src="<?= $last_contributor->getAvatarURLMedium() ?>" class="wh-40px rounded-circle" alt="<?= $last_contributor->name ?>">
                    </a>
                    <div class="media-body line-height-12">
                        <a class="semi-small text-secondary text-decoration-none" href="<?= $last_contributor->getURL($this->lang) ?>"><?= $last_contributor->name ?></a>

                        <span class="semi-small text-black-50">
                            &middot;
                        </span>

                        <?php if ($last_contributor->signature) : ?>
                            <span class="semi-small">
                                <?= $last_contributor->signature ?>
                            </span>
                        <?php else : ?>
                            <span class="semi-small text-black-50">
                                @<?= $last_contributor->username ?>
                            </span>
                        <?php endif; ?>


                        <div class="small text-black-50 mt-2">
                            <?= __('page_main.item__top_question.updated_answer') ?>: <?= \Humanizer\DateTime::humanizeTimestamp($this->lang, $question->answer->updatedAt) ?>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($question->imageBaseName) : ?>
                <a class="d-block my-3" href="<?= $question->getURL($this->lang) ?>">
                    <img class="img-fluid" src="<?= $question->getImageURLMedium($this->lang) ?>" alt="<?= $question->title ?>">
                </a>
            <?php endif; ?>

            <!-- answer text -->
            <?php if (mb_strlen($question->answer->text)) : ?>
                <div class="my-3">
                    <?= mb_substr($question->answer->text, 0, 150) ?><?= (mb_strlen($question->answer->text) > 150) ? '&hellip;' : '' ?>
                    <?php if (mb_strlen($question->answer->text) > 150) : ?>
                        <a class="text-secondary semi-small my-3" href="<?= $question->getURL($this->lang) ?>">
                            (<?= __('page_main.item__top_question.read_more') ?>)
                        </a>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <!-- / answer text -->

            <div class="mt-2 text-secondary">

                <button type="button" class="btn btn-sm btn-outline-gray mr-3">
                    <i class="material-icons md-14">thumb_up</i>
                    <?= __('page_main.item__top_question.upvote') ?>
                </button>

                <?php if (count($contributors) > 1) : ?>
                    <span class="mr-3">
                        <?php foreach ($contributors as $contributor) : ?>
                            <a class="wh-24px rounded-circle" href="<?= $contributor->getURL($this->lang) ?>"><img src="<?= $contributor->getAvatarURLMedium() ?>" class="wh-28px rounded-circle" alt="<?= $contributor->name ?>" title="<?= $contributor->name ?>"></a>
                        <?php endforeach; ?>
                        <!-- <a class="semi-small text-black-50" href="#">
                        +2
                    </a> -->
                    </span>
                <?php endif; ?>

                <!-- time to read -->
                <?php if (strlen($question->answer->text)) : ?>
                    <span class="semi-small text-black-50">
                        <i class="material-icons md-14">access_time</i>
                        <?= $question->getMinutesToRead() ?>&nbsp;<?= trans_choice('common.choice_minutes', $question->getMinutesToRead()); ?>

                    </span>
                <?php endif; ?>
                <!-- / time to read -->

            </div>
        </div>
        <!-- / question item -->

    <?php endforeach; ?>

<?php endif; ?>