<?php if (isset($this->recent_questions) && count($this->recent_questions)) : ?>
    <div class="mb-5">

        <div class="text-uppercase text-secondary mb-4">
            <?= $this->translator->get('main', 'recent_questions', 'title') ?>
        </div>

        <?php foreach ($this->recent_questions as $question) : ?>
            <div class="my-3">
                <a class="h4 text-dark text-decoration-none" href="<?= $question->get_URL($this->lang) ?>">
                    <?= $question->title ?>
                </a>
                <div class="small text-secondary">
                    <?= $this->translator->get('question', 'answer_updated') ?> <?= \Humanizer\DateTime::humanize_timestamp($this->lang, $question->answer->updatedAt) ?>

                    <?php if (strlen($question->answer->text) == 0) : ?>
                        <span class="mx-1 text-dark font-weight-bold">&middot;</span>
                        <a rel="nofollow" href="<?= $question->get_edit_URL($this->lang) ?>">
                            <?= $this->translator->get('Write first answer') ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>

    </div>
<?php endif; ?>