<div class="semi-small font-weight-bold text-uppercase text-primary mt-2 mb-3">
    <?= $this->translator->get('main', 'sections', 'title') ?>
</div>

<ul class="list-unstyled semi-small mb-0">

    <?php if ($this->question_about_answeropedia) : ?>
        <li class="my-2">
            <a href="<?= $this->question_about_answeropedia->get_URL($this->lang) ?>" class="text-dark text-decoration-none">
                <?= $this->translator->get('navbar_subnav', 'how_it_works') ?>
            </a>
        </li>
    <?php endif; ?>

    <li class="my-2">
        <a href="<?= \Helper\URL\Page::get_flow_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'recent_changes') ?>
        </a>
    </li>

    <li class="my-2">
        <a href="<?= \Helper\URL\Categories::get_newest_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'popular_categories') ?>
        </a>
    </li>

    <li class="my-2">
        <a href="<?= \Helper\URL\Sandbox::get_without_answers_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'sandbox') ?>
        </a>
    </li>

    <li class="my-2">
        <a href="<?= SITE_URL . '/' . $this->lang . '/random-question' ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'random_question') ?>
        </a>
    </li>
</ul>