<div class="semi-small font-weight-bold text-uppercase text-primary mt-2 mb-4">
    <?= $this->translator->get('main', 'sections', 'title') ?>
</div>

<ul class="list-unstyled mb-0 semi-small">

    <li class="my-3">
        <a href="<?= SITE_URL . '/' . $this->lang . '/' . $this->translator->get('service_id', 'about_answeropedia') ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'how_it_works') ?>
        </a>
    </li>

    <li class="my-3">
        <a href="<?= \Helper\URL\Page::get_flow_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'recent_changes') ?>
        </a>
    </li>

    <li class="my-3">
        <a href="<?= \Helper\URL\Categories::get_newest_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'popular_categories') ?>
        </a>
    </li>

    <li class="my-3">
        <a href="<?= \Helper\URL\Sandbox::get_without_answers_URL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'sandbox') ?>
        </a>
    </li>

    <li class="my-3">
        <a href="<?= SITE_URL . '/' . $this->lang . '/random-question' ?>" class="text-dark text-decoration-none">
            <?= $this->translator->get('navbar_subnav', 'random_question') ?>
        </a>
    </li>
</ul>