<div class="mb-5">
    <div class="text-uppercase text-secondary mb-3">
        <?= $this->translator->get('main', 'share_link', 'title') ?>
    </div>
    <p class=""><?= $this->translator->get('main', 'share_link', 'note') ?></p>

    <script src="//yastatic.net/share2/share.js" async="async" charset="utf-8"></script>
    <div class="ya-share2" data-services="twitter,vkontakte,facebook,gplus,pinterest,delicious,digg,reddit,pocket,tumblr,collections,telegram" data-size="m" data-counter="" data-title="<?= $this->share_link['title'] ?>" data-description="<?= $this->share_link['description'] ?>" data-url="<?= $this->share_link['url'] ?>" data-image="<?= $this->share_link['image'] ?>">
    </div>
</div>