<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

    <?php require_once TEMPLATE_PATH.'/main/_block/jumbotron.phtml' ?>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-8 col-xl-8">
                <?php require_once TEMPLATE_PATH.'/main/_block/nav.phtml' ?>

                <!-- interesting questions -->
                <?php if (isset($this->recent_questions)): ?>
                    <?php foreach ($this->recent_questions as $question): ?>
                        <?php require TEMPLATE_PATH.'/_common/item/question_with_answer.phtml'; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <!-- /interesting questions -->

                <?php require_once TEMPLATE_PATH.'/main/_block/share.phtml' ?>

            </div>
            <div class="col-12 col-md-4 col-xl-4">
                <?php require_once TEMPLATE_PATH.'/_common/lure/about_octo.phtml' ?>
            </div>
        </div>
    </div>

    <?php require_once TEMPLATE_PATH.'/_common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
