
<?php if (count($this->contributors_tail)): ?>
    <div class="container-fluid max-width-md">
        <div class="row">
            <div class="col-12 mt-5 mb-2 text-center mr-auto">
                <div class="h2 mb-1" id="contributors_full_list">
                    Авторы ответа <!-- Answer contributor -->
                </div>
                <span class="small color-gray-400">
                    <?= (new Contributors_Humanizer($this->l))->humanize(count($this->contributors)) ?>
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mx-auto">

                <?php foreach ($this->contributors_tail as $contributor): ?>

                    <div class="flex-container box p-3 my-3">
                        <div class="width-6">
                            <a class="size-6" href="<?= $contributor->getURL($this->lang) ?>">
                                <img class="size-6 rounded-circle" src="<?= $contributor->getAvatarMediumURL() ?>">
                            </a>
                        </div>
                        <div class="flex-grow-4 ml-3">
                            <div class="font_weight_700">
                                <a class="link_gray_900 no_underline" href="<?= $contributor->getURL($this->lang) ?>">
                                    <?= $contributor->getName() ?>
                                </a>
                            </div>
                            <div class="small color-gray-600">
                                <?= $contributor->getSignature() ? $contributor->getSignature() : '+'.$contributor->getUsername() ?>

                                <?php if ($contributor->getSite()): ?>
                                    <span class="color-gray-800 mx-1 font-weight-800">&middot;</span>
                                    <a href="<?= $contributor->getSite() ?>">
                                        <?= parse_url($contributor->getSite(), PHP_URL_HOST) ?>
                                    </a>
                                <?php endif; ?>

                                <?php if ($contributor->getID() == $this->lastContributorID): ?>
                                    <span class="color-gray-800 mx-1 font-weight-800">&middot;</span>
                                    <span class="badge badge-success badge-sm">
                                        Последняя правка
                                    </span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="width-11 d-none d-sm-block color-gray-700">
                            <img class="size-18px mt-minus-4px" src="https://png.icons8.com/ios-glyphs/18/78909C/pull-request.png">
                            <?= Contribution_Humanizer::humanizeCount($contributor->getContribution()) ?>

                            <?php $percentage = $contributor->getContribution() * (1 / $this->maxContribution); ?>
                            <?php $contributionColor = ColorMixer_Helper::colorBetween('1E88E5', '388E3C', $percentage); ?>
                            <span class="status ml-1" style="background-color: #<?= $contributionColor ?>;"></span>
                        </div>
                    </div>

                <?php endforeach; ?>

            </div>
        </div>
    </div>

<?php endif; ?>
