
<?php if (count($this->contributors_top)): ?>
    <div class="mt-4">
        <div class="title border-bottom pb-3">
            <?= $this->l->t('question', 'top_contributors', 'top_title') ?>
        </div>

        <?php foreach ($this->contributors_top as $contributor): ?>
            <div class="flex-container overflow-x-hidden my-4">
                <div class="width-6 align-self-top pt-2">
                    <a class="size-6" href="<?= $contributor->getURL($this->lang) ?>">
                        <img class="size-6 rounded-circle" src="<?= $contributor->getAvatarMediumURL() ?>">
                    </a>
                </div>
                <div class="flex-grow-4 ml-3">
                    <div class="font-weight-700">
                        <a class="color-gray-900 no_underline" href="<?= $contributor->getURL($this->lang) ?>">
                            <?= $contributor->getName() ?>
                        </a>
                    </div>
                    <div class="small color-gray-600">
                        <?= $contributor->getSignature() ? $contributor->getSignature() : '' ?>
                        <?php if ($contributor->getSignature() && $contributor->getSite()): ?>
                            <span class="color-gray-900 mx-1 font-weight-800">&middot;</span>
                        <?php endif; ?>
                        <?php if ($contributor->getSite()): ?>
                            <a href="<?= $contributor->getSite() ?>">
                                <?= parse_url($contributor->getSite(), PHP_URL_HOST) ?>
                            </a>
                        <?php endif; ?>
                    </div>
                    <div class="color-gray-700 mt-2">
                        <span class="text-nowrap font-weight-600 mr-1">
                            <img class="size-18px mt-minus-4px" src="https://png.icons8.com/ios-glyphs/18/3498db/pull-request.png">
                            <?= Contribution_Humanizer::humanizeCount($contributor->getContribution()) ?>
                        </span>
                        <span class="text-nowrap mr-1">
                            <img class="size-18px mt-minus-4px"  src="https://png.icons8.com/windows/18/27ae60/add.png">
                            <span class="color-gray-600">
                                <?= Contribution_Humanizer::humanizeCount($contributor->getInsertionsCount()) ?>
                            </span>
                        </span>
                        <span class="text-nowrap mr-1">
                            <img class="size-18px mt-minus-4px"  src="https://png.icons8.com/windows/18/e74c3c/minus.png">
                            <span class="color-gray-600">
                                <?= Contribution_Humanizer::humanizeCount($contributor->getDeletionsCount()) ?>
                            </span>
                        </span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

    </div>
<?php endif; ?>
