
<?php if (count($this->contributors_tail)): ?>
    <div class="avatar-group mt-4 mb-2">
        <?php foreach ($this->contributors_tail as $contributor): ?>
            <a href="<?= $contributor->getURL($this->lang) ?>" class="avatar-item">
                <img src="<?= $contributor->getAvatarSmallURL() ?>">
            </a>
        <?php endforeach; ?>
    </div>
    <p class="pl-1 small color-gray-500 mb-4">
        + <a class="link_gray_700 no_underline" href="#"><?= count($this->contributors) ?> авторов</a>
    </p>

<?php endif; ?>
