
<?php if (!$this->answer->getText()): ?>
    <?php if ($this->authUser): ?>
        <div class="block__first_answer my-5">
            <div class="icon">
                <img src="https://png.icons8.com/wired/64/1976D2/trophy.png" alt="<?= $this->l->t('block', 'first_answer', 'title') ?>">
            </div>
            <div class="info">
                <p class="title"><?= $this->l->t('block', 'first_answer', 'title') ?></p>
                <p class="message"><?= $this->l->t('block', 'first_answer', 'lead') ?></p>
                <a class="btn btn-primary" href="<?= $this->question->getEditURL($this->lang) ?>">
                    <?= $this->l->t('block', 'first_answer', 'answer_btn') ?>
                </a>
            </div>
        </div>
    <?php else: ?>
        <div class="alert alert-secondary pb-4 pl-5 pr-5 mb-5 text-center">
            <div class="mt-3">
                <img class="img-size-96" alt="<?= $this->l->t('block', 'first_answer', 'title') ?>" src="<?= IMAGE_URL.'/icons8/medal-first-place-96-color.png' ?>">
            </div>
            <p class="h5 mt-4"><?= $this->l->t('block', 'first_answer', 'title') ?></p>
            <p class="lead"><?= $this->l->t('block', 'first_answer', 'lead') ?></p>
            <button type="button" class="btn btn-success mt-3" data-toggle="modal" data-target="#first_answer__signup">
                <img src="<?= IMAGE_URL.'/icons8/edit-16-white-v2.png' ?>" class="mr-2" style="margin-top: -3px;">
                <?= $this->l->t('block', 'first_answer', 'answer_btn') ?>
            </button>
        </div>
        <?php require_once TEMPLATE_PATH.'/question/modal/first_answer__signup.phtml' ?>
    <?php endif; ?>
<?php endif; ?>
