
<div class="mt-4">
    <?php if (count($this->question->getTopics())): ?>

        <?php foreach ($this->question->getTopics() as $topic): ?>
            <a class="badge badge-secondary mb-3 mr-2" href="<?= Topic_URL_Helper::getURLFromTitle($this->lang, $topic) ?>">
                <?= $topic ?>
            </a>
        <?php endforeach; ?>

        <?php if ($this->authUser): ?>
            <a class="badge badge-primary mb-3 mr-2" href="<?= Question_URL_Helper::getUpdateTopicsURL($this->lang, $this->question) ?>">
                <img class="badge-icon" src="https://png.icons8.com/material/14/2196F3/edit.png">
                <?= $this->l->t('question', 'update_topics', 'btn') ?>
            </a>
        <?php endif; ?>

    <?php else: ?>
        <?php if ($this->authUser): ?>
            <a class="badge badge-primary mb-3 mr-2" href="<?= Question_URL_Helper::getUpdateTopicsURL($this->lang, $this->question) ?>">
                <img class="badge-icon" src="https://png.icons8.com/material/14/2196F3/edit.png">
                Задать темы вопроса
            </a>
        <?php endif; ?>
    <?php endif; ?>
</div>
