
<?php if (count($this->contributors_top) >= 1): ?>
    <div class="block__improve_answer my-6">
        <div class="improve_message">
            <?= $this->l->t('improve_answer', 'title') ?>
        </div>
        <div class="btn_improve float-lg-right mt-2 mt-lg-0">
            <?php if ($this->authUser): ?>
                <a class="btn btn-success" href="<?= Answer_URL_Helper::getEditURL($this->lang, $this->question) ?>">
                    <?= $this->l->t('improve_answer', 'btn_yes') ?>
                </a>
            <?php else: ?>
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal_lure__edit_answer">
                    <?= $this->l->t('improve_answer__btn_yes') ?>
                </button>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
