
<?php if (isset($this->questions_with_image) && count($this->questions_with_image)): ?>
    <div class="mt-5 pt-5 bg-color-gray-100 border-bottom">
        <div class="container-fluid max-width-lg mx-auto">
            <div class="row">

                <?php $i = 1; ?>
                <?php foreach ($this->questions_with_image as $question_with_image): ?>
                    <div class="col-11 mx-auto col-sm-6 col-md-4 <?= $i == 3 ? 'd-sm-none d-md-block' : '' ?>">
                        <div class="card mb-5">
                            <a href="<?= Question_URL_Helper::getURL($this->lang, $question_with_image) ?>">
                                <img class="card-img-top cover-h8" src="<?= Question_URL_Helper::getImageURLMedium($this->lang, $question_with_image) ?>">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a class="h3 color-gray-800 no-underline-hover" href="<?= Question_URL_Helper::getURL($this->lang, $question_with_image) ?>">
                                        <?= $question_with_image->getTitle(); ?>
                                    </a>
                                </h5>
                                <p class="card-text small color-gray-500 mt-4">
                                    Ответ обновлен <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->getAnswer()->getUpdatedAt()) ?>
                                </p>
                            </div>
                        </div>
                    </div>

                    <?php $i++; ?>

                <?php endforeach; ?>

            </div>
        </div>
    </div>
<?php endif; ?>
