
<?php if (isset($this->related_questions)): ?>
    <div class="my-5">
        <div class="border-bottom pb-3 mb-4">
            <span class="title">Похожие вопросы</span>
        </div>

        <?php foreach ($this->related_questions as $question): ?>
            <div class="my-4">
                <a class="font-size-18px color-gray-900 no-underline-hover" href="<?= $question->getURL($this->lang) ?>">
                    <?= $question->getTitle() ?>
                </a>
                <div class="small color-gray-500 mt-1">
                    <?php if (strlen($question->getAnswer()->getText())): ?>
                        <?= $this->minutesToRead_humanizer->humanizeCharactersCount(mb_strlen($question->getAnswer()->getText())) ?>
                        <span class="mx-1 color-gray-900 font-weight-800">&middot;</span>
                    <?php endif; ?>

                    <?= $this->l->t('q__last_updated') ?> <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->getAnswer()->getUpdatedAt()) ?>

                    <?php if (strlen($question->getAnswer()->getText()) == 0): ?>
                        <a class="btn btn-sm btn-outline-primary ml-2" rel="nofollow" href="<?= $question->getEditURL($this->lang) ?>">
                            <?= $this->l->t('related_questions__write_first_answer') ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>

    </div>
<?php endif; ?>
