
<?php if (!$this->authUser): ?>
    <div class="bg-color-gray-light p-4 my-4">
        <a href="#" data-toggle="modal" data-target="#modal_signup" class="btn btn-danger btn-block mb-4">
            <?= $this->l->t('nav__signup') ?>
        </a>
        <p class="color-text-light mb-3"><?= $this->l->t('q__signup_lure__text_1') ?></p>
        <p class="color-text-light mb-3"><?= $this->l->t('q__signup_lure__text_2') ?></p>
        <p class="color-text-light mb-3"><?= $this->l->t('q__signup_lure__text_3') ?></p>
    </div>
<?php endif; ?>
