
<?php if (!$this->authUser): ?>
    <div class="bg-color-gray-light p-4 my-4">
        <a href="#" data-toggle="modal" data-target="#modal_signup" class="btn btn-danger btn-block mb-4">
            <?= _('Register on Answeropedia and you will be able to') ?>
        </a>
        <p class="color-text-light mb-3"><?= _('See what questions your friends are asking today') ?></p>
        <p class="color-text-light mb-3"><?= _('Watch for new questions with topics interesting for you') ?></p>
        <p class="color-text-light mb-3"><?= _('And share your knowledge with others') ?></p>
    </div>
<?php endif; ?>
