
<?php if (!$this->authUser): ?>
    <div class="bg-color-gray-light p-4 my-4">
        <a href="#" data-toggle="modal" data-target="#modal_signup" class="btn btn-danger btn-block mb-4">
            <?= _('Question - Signup lure - Title') ?>
        </a>
        <p class="color-text-light mb-3"><?= _('Question - Signup lure - Text 1') ?></p>
        <p class="color-text-light mb-3"><?= _('Question - Signup lure - Text 2') ?></p>
        <p class="color-text-light mb-3"><?= _('Question - Signup lure - Text 3') ?></p>
    </div>
<?php endif; ?>
