
<!-- improve_feed -->
<div class="box d-none d-md-block">
    <div class="box-header font-weight-bold color-gray-800">
        <?= _('Improve your feed') ?>
    </div>
    <div class="box-body pt-0 pb-0 small">

        <div class="my-3">
            <i class="fas fa-check color-success"></i>
            <span class="color-gray-600">
                <s>
                    <?= _('Visit your feed') ?>
                </s>
            </span>
        </div>

        <div class="my-3">
            <?php if ($this->authUser->getUsername() == $this->authUser->getName()): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Settings_URL_Helper::getRealNameURL($this->lang) ?>">
                    <?= _('Set real name') ?>
                </a>
            <?php else: ?>
                <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= _('Set real name') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if (strlen($this->authUser->getSignature()) == 0): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Settings_URL_Helper::getSignatureURL($this->lang) ?>">
                    <?= _('Set signature') ?>
                </a>
            <?php else: ?>
                <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= _('Set signature') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if ($this->isShowTopicsFollowLure): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Topics_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= _('Follow 3 more topics') ?>
                </a>
            <?php else: ?>
                <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= _('Follow 3 more topics') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if ($this->isShowQuestionsFollowLure): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Questions_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= _('Follow your first question') ?>
                </a>
            <?php else: ?>
            <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= _('Follow your first question') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if ($this->isShowUsersFollowLure): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Users_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= _('Find your friends') ?>
                </a>
            <?php else: ?>
                <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= _('Find your friends') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <!-- <div class="my-3">
            <i class="fas fa-check color-success"></i>
            <span class="color-gray-600">
                <s>
                    <?= _('Ask your first question') ?>
                </s>
            </span>
        </div>

        <div class="my-3">
            <i class="fas fa-check color-success"></i>
            <span class="color-gray-600">
                <s>
                    <?= _('Answer a question') ?>
                </s>
            </span>
        </div> -->

    </div>
</div>
<!-- / improve_feed -->
