
<!-- improve_feed -->
<div class="d-none d-md-block">
    <div class="font-weight-bold color-gray-800">
        <?= $this->translator->get('Improve your feed') ?>
    </div>
    <div class="pt-0 pb-0 small">

        <div class="my-3">
            <i class="fas fa-check color-success"></i>
            <span class="color-gray-600">
                <s>
                    <?= $this->translator->get('Visit your feed') ?>
                </s>
            </span>
        </div>

        <div class="my-3">
            <?php if ($this->authUser->username == $this->authUser->name): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Settings_URL_Helper::getRealNameURL($this->lang) ?>">
                    <?= $this->translator->get('Set real name') ?>
                </a>
            <?php else: ?>
                <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= $this->translator->get('Set real name') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if (strlen($this->authUser->signature) == 0): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Settings_URL_Helper::getSignatureURL($this->lang) ?>">
                    <?= $this->translator->get('Set signature') ?>
                </a>
            <?php else: ?>
                <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= $this->translator->get('Set signature') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if ($this->isShowHashtagsFollowLure): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Hashtags_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= $this->translator->get('Follow 3 more hashtags') ?>
                </a>
            <?php else: ?>
                <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= $this->translator->get('Follow 3 more hashtags') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if ($this->isShowQuestionsFollowLure): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Questions_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= $this->translator->get('Follow your first question') ?>
                </a>
            <?php else: ?>
            <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= $this->translator->get('Follow your first question') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <div class="my-3">
            <?php if ($this->isShowUsersFollowLure): ?>
                <a class="color-gray-800 text-decoration-none" href="<?= Users_URL_Helper::getNewestURL($this->lang) ?>">
                    <?= $this->translator->get('Find your friends') ?>
                </a>
            <?php else: ?>
                <i class="fas fa-check color-success"></i>
                <span class="color-gray-600">
                    <s>
                        <?= $this->translator->get('Find your friends') ?>
                    </s>
                </span>
            <?php endif; ?>
        </div>

        <!-- <div class="my-3">
            <i class="fas fa-check color-success"></i>
            <span class="color-gray-600">
                <s>
                    <?= $this->translator->get('Ask your first question') ?>
                </s>
            </span>
        </div>

        <div class="my-3">
            <i class="fas fa-check color-success"></i>
            <span class="color-gray-600">
                <s>
                    <?= $this->translator->get('Answer a question') ?>
                </s>
            </span>
        </div> -->

    </div>
</div>
<!-- / improve_feed -->
