<!-- DEPREC -->

<?php if (count($this->sandbox_questions)): ?>
    <noindex>
        <!--noindex-->
            <p class="title my-4">
                <a href="<?= Sandbox_URL_Helper::getWithoutAnswersURL($this->lang) ?>">
                    Вопросы из песочницы
                </a>
            </p>

            <div class="mt-4 mb-5">
                <?php foreach ($this->sandbox_questions as $sandbox_question): ?>
                    <div class="my-4">
                        <a class="link_gray_700 font_weight_600" href="<?= Question_URL_Helper::getURL($this->lang, $sandbox_question) ?>">
                            <?= $sandbox_question->getTitle() ?>
                        </a>
                        <div class="small mt-2">
                            <?php if ((strtotime("now") - strtotime($sandbox_question->getAnswer()->getUpdatedAt())) < (60*60*24)): ?>
                                <span class="badge badge-sm badge-success mr-2">Новый</span>
                            <?php endif; ?>
                            <span class="color-gray-500">
                                <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $sandbox_question->getAnswer()->getUpdatedAt()) ?>
                            </span>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>

        <!--/noindex-->
    </noindex>
<?php endif; ?>
