<!--noindex-->
<!--googleoff: index-->

<div id="modal_lure__edit_answer" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal_lure__edit_answer" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <p class="h1 text-center mx-auto">
					<i class="material-icons md-18 w-18px" style="color: #546e7a;">edit</i>
                </p>
            </div>
            <div class="modal-body">
                <p><?= $this->translator->get('Register or log in and you can edit or supplement this question.') ?></p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal_signup">
                    <?= $this->translator->get('Signup') ?>
                </a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <?= $this->translator->get('Close') ?>
                </button>
            </div>
        </div>
    </div>
</div>

<!--googleon: index -->
<!--/noindex-->