<!--noindex-->
<!--googleoff: index-->

<div id="modal__feedback_thanks" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal__feedback_thanks" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <p class="h1 text-center mx-auto">
					<i class="material-icons md-18 w-18px">check</i>
                </p>
            </div>
            <div class="modal-body">
                <p><?= $this->translator->get('Thanks for the feedback!') ?>!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">
                    <?= $this->translator->get('Close') ?>
                </button>
            </div>
        </div>
    </div>
</div>

<!--googleon: index -->
<!--/noindex-->