
<div id="modal__feedback_thanks" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal__feedback_thanks" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <p class="h1 text-center mx-auto">
                    <i class="fas fa-ok"></i>
                </p>
            </div>
            <div class="modal-body">
                <p><?= _('Thanks for the feedback!') ?>!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">
                    <?= _('Close') ?>
                </button>
            </div>
        </div>
    </div>
</div>
