<!--noindex-->
<!--googleoff: index-->

<div id="first_answer__signup" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <p class="h1 text-center mx-auto">
                    <i class="fas fa-sign-in-alt"></i>
                </p>
            </div>
            <div class="modal-body">
                <p><?= $this->translator->get('Register or log in and you will be the first to write the answer to this question.') ?></p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal_signup">
                    <?= $this->translator->get('Signup') ?>
                </a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <?= $this->translator->get('Close') ?>
                </button>
            </div>
        </div>
    </div>
</div>

<!--googleon: index -->
<!--/noindex-->