
<div id="modal__follow_question_lure" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal__follow_question_lure" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <p class="h1 text-center mx-auto">
                    <i class="fas fa-mail" style="color: #2BB462;"></i>
                </p>
            </div>
            <div class="modal-body">
                <p><?= _('Register or sign in and you can subscribe to this question.') ?></p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal_signup">
                    <?= _('Signup') ?>
                </a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <?= _('Close') ?>
                </button>
            </div>
        </div>
    </div>
</div>
