<!--noindex-->
<!--googleoff: index-->

<div id="modal__follow_question_lure" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal__follow_question_lure" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <p class="h1 text-center mx-auto">
                    <i class="material-icons md-24">email</i>
                </p>
            </div>
            <div class="modal-body">
                <p><?= __('page_question.lure_follow_question.msg') ?></p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal_signup">
                    <?= __('page_question.lure_follow_question.signup') ?>
                </a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <?= $this->translator->get('btn', 'close') ?>
                </button>
            </div>
        </div>
    </div>
</div>

<!--googleon: index -->
<!--/noindex-->