
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-sm-12 col-md-6 col-lg-6 ml-auto mr-auto">

            <p>Redirect from <strong><?= $this->question->title ?></strong> to:</p>
            <p>
                <a href="<?= Redirect_URL_Helper::getURL($this->lang, $this->questionRedirect) ?>" style="font-size: 2rem;">
                    <?= $this->questionRedirect->title ?>
                </a>
            </p>

        </div>
    </div>
</div>
