<footer class="pt-4 pb-4 border-top" style="background-color: #EEEEEE;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-9 col-lg-9">
                <span class="text-muted">2018 &copy; <?= $this->l->t('octoanswers') ?></span>
            </div>
            <div class="col-sm-12 col-md-3 col-lg-3 text-right">
                <div class="btn-group dropup">
                    <button class="btn btn-outline-success btn-sm btn-block dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?= $this->l->t('lang', 'english') ?>
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item change_lang_item" data-lang="en" href="">
                            <?= $this->l->t('lang', 'english') ?>
                        </a>
                        <a class="dropdown-item change_lang_item" data-lang="ru" href="">
                            <?= $this->l->t('lang', 'russian') ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
