<style>
    .bookshelf-container {
        display: block;
        overflow: visible;
        height: 1px;
        width: 100%;
        margin: 56px 0 40px;
        font-size: 1.3rem;
        font-weight: 700;
        line-height: 2rem;
    }
    .bookshelf {
        display: block;
        border-top: 1px solid #E5E5E5;
        box-shadow: 0 -1px 0 #fff;
        text-align: center;
        white-space: nowrap;
    }
    .bookshelf-container .text {
        padding: 0 .992rem;
    }
    .bookshelf span {
        background-color: #FFF;
        position: relative;
        top: -1.12rem;
        font-weight: 300;
    }
    .langlist {
        margin-bottom: 4rem;
    }
    .langlist>ul {
        column-width: 11.2rem;
    }
    .langlist>ul>li {
        display: block;
        line-height: 1.7;
        -webkit-column-break-inside: avoid;
        page-break-inside: avoid;
        break-inside: avoid;
    }
</style>

<!-- 1,000,000+ content pages -->
<h2 class="bookshelf-container">
    <span class="bookshelf">
        <span class="text" dir="ltr">1&nbsp;000&nbsp;000+</span>
    </span>
</h2>
<div class="langlist langlist-large hlist" data-el-section="secondary links">
    <ul>
        <li><a href="#de" lang="de">Deutsch</a></li>
        <li><a href="https://octoanswers.com/en" lang="en" title="English">English</a></li>
        <li><a href="#es" lang="es">Español</a></li>
        <li><a href="#fr" lang="fr">Français</a></li>
        <li><a href="#it" lang="it">Italiano</a></li>
        <li><a href="#nl" lang="nl">Nederlands</a></li>
        <li><a href="#ja" lang="ja" title="Nihongo">日本語</a></li>
        <li><a href="#pl" lang="pl">Polski</a></li>
        <li><a href="https://octoanswers.com/ru" lang="ru" title="Russkiy">Русский</a></li>
        <li><a href="#ceb" lang="ceb">Sinugboanong Binisaya</a></li>
        <li><a href="#sv" lang="sv">Svenska</a></li>
        <li><a href="#vi" lang="vi">Tiếng Việt</a></li>
        <li><a href="#war" lang="war">Winaray</a></li>
    </ul>
</div>

<!-- 100,000+ content pages -->
<h2 class="bookshelf-container">
    <span class="bookshelf">
        <span class="text" dir="ltr">100&nbsp;000+</span>
    </span>
</h2>
<div class="langlist langlist-large hlist" data-el-section="secondary links">
    <ul>
        <li><a href="#ar" lang="ar" title="Al-ʿArabīyah"><bdi dir="rtl">العربية</bdi></a></li>
        <li><a href="#az" lang="az">Azərbaycanca</a></li>
        <li><a href="#bg" lang="bg" title="Bǎlgarski">Български</a></li>
        <li><a href="#zh-min-nan" lang="nan">Bân-lâm-gú / Hō-ló-oē</a></li>
        <li><a href="#be" lang="be" title="Belaruskaya (Akademichnaya)">Беларуская (Акадэмічная)</a></li>
        <li><a href="#ca" lang="ca">Català</a></li>
        <li><a href="#cs" lang="cs">Čeština</a></li>
        <li><a href="#da" lang="da">Dansk</a></li>
        <li><a href="#et" lang="et">Eesti</a></li>
        <li><a href="#el" lang="el" title="Ellīniká">Ελληνικά</a></li>
        <li><a href="#eo" lang="eo">Esperanto</a></li>
        <li><a href="#eu" lang="eu">Euskara</a></li>
        <li><a href="#fa" lang="fa" title="Fārsi"><bdi dir="rtl">فارسی</bdi></a></li>
        <li><a href="#gl" lang="gl">Galego</a></li>
        <li><a href="#ko" lang="ko" title="Hangugeo">한국어</a></li>
        <li><a href="#hy" lang="hy" title="Hayeren">Հայերեն</a></li>
        <li><a href="#hi" lang="hi" title="Hindī">हिन्दी</a></li>
        <li><a href="#hr" lang="hr">Hrvatski</a></li>
        <li><a href="#id" lang="id">Bahasa Indonesia</a></li>
        <li><a href="#he" lang="he" title="ʿIvrit"><bdi dir="rtl">עברית</bdi></a></li>
        <li><a href="#ka" lang="ka" title="Kartuli">ქართული</a></li>
        <li><a href="#la" lang="la">Latina</a></li>
        <li><a href="#lt" lang="lt">Lietuvių</a></li>
        <li><a href="#hu" lang="hu">Magyar</a></li>
        <li><a href="#ms" lang="ms">Bahasa Melayu</a></li>
        <li><a href="#min" lang="min">Bahaso Minangkabau</a></li>
        <li><a href="#no" lang="nb">Norsk (Bokmål)</a></li>
        <li><a href="#nn" lang="nn">Norsk (Nynorsk)</a></li>
        <li><a href="#ce" lang="ce" title="Noxçiyn">Нохчийн</a></li>
        <li><a href="#uz" lang="uz">Oʻzbekcha / Ўзбекча</a></li>
        <li><a href="#pt" lang="pt">Português</a></li>
        <li><a href="#kk" lang="kk"><span lang="kk-Cyrl">Қазақша</span> / <span lang="kk-Latn">Qazaqşa</span> / <bdi lang="kk-Arab" dir="rtl">قازاقشا</bdi></a></li>
        <li><a href="#ro" lang="ro">Română</a></li>
        <li><a href="#simple" lang="en">Simple English</a></li>
        <li><a href="#sk" lang="sk">Slovenčina</a></li>
        <li><a href="#sl" lang="sl">Slovenščina</a></li>
        <li><a href="#sr" lang="sr">Српски / Srpski</a></li>
        <li><a href="#sh" lang="sh">Srpskohrvatski / Српскохрватски</a></li>
        <li><a href="#fi" lang="fi">Suomi</a></li>
        <li><a href="#ta" lang="ta" title="Tamiḻ">தமிழ்</a></li>
        <li><a href="#th" lang="th" title="Phasa Thai">ภาษาไทย</a></li>
        <li><a href="#tr" lang="tr" title="Turkce">Türkçe</a></li>
        <li><a href="#uk" lang="uk" title="Ukrayins’ka">Українська</a></li>
        <li><a href="#ur" lang="ur" title="Urdu"><bdi dir="rtl">اردو</bdi></a></li>
        <li><a href="#vo" lang="vo">Volapük</a></li>
        <li><a href="#zh" lang="zh" title="Zhōngwén">中文</a></li>
    </ul>
</div>
