
<nav class="navbar navbar-light fixed-top navbar-expand-md" id="navbar">

    <a class="navbar-brand" href="<?= SITE_URL ?>">
        <img src="/assets/img/octo-logo-30x30.png" width="30" height="30" class="d-inline-block align-top" alt="Answeropedia">
        <?= _('Answeropedia') ?>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        Menu
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="navbar-text text-secondary">
            <?= _('It\'s like wikipedia, only for questions and answers.') ?>
            </li>
        </ul>
        <ul class="nav navbar-nav float-xs-right">
            <li class="nav-item">
                <a class="nav-link" href="#"><?= _('About Answeropedia') ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://www.facebook.com/en.answeropedia" rel="nofollow">
                    Facebook
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://vk.com/answeropedia" rel="nofollow">
                    VK
                </a>
            </li>

        </ul>
    </div>
</nav>
