<?php if ($this->showFooter): ?>
    <footer class="bg-color-gray-200 small">
        <div class="container-fluid">
            <div class="row pt-4 pb-2">

                <div class="col-12 col-md-3">
                    <div class="dropup">
                        <button class="btn btn-sm btn-outline-secondary dropdown-toggle mb-3" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  type="button">
                            <?= $this->l->t('lang', $this->lang) ?>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" data-lang="en" href="<?= Page_URL_Helper::getMainURL('en') ?>">
                                <?= $this->l->t('lang', 'english') ?>
                            </a>
                            <a class="dropdown-item" data-lang="ru" href="<?= Page_URL_Helper::getMainURL('ru') ?>">
                                <?= $this->l->t('lang', 'russian') ?>
                            </a>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </footer>
<?php endif; ?>
