
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title><?= $this->pageTitle ?></title>

<?php if ($this->pageDescription): ?>
<meta name="description" content="<?= $this->pageDescription ?>">
<?php endif; ?>

<?php if (isset($this->canonicalURL)): ?>
<link rel="canonical" href="<?= $this->canonicalURL ?>" />
<?php endif; ?>

<!-- Favicons -->
<link rel="icon" type="image/png" href="https://octoanswers.com/assets/img/favicon/favicon-16.png" sizes="16x16">
<link rel="icon" type="image/png" href="https://octoanswers.com/assets/img/favicon/favicon-32.png" sizes="32x32">
<link rel="icon" type="image/png" href="https://octoanswers.com/assets/img/favicon/favicon-96.png" sizes="96x96">
<link rel="icon" type="image/png" href="https://octoanswers.com/assets/img/favicon/favicon-160.png" sizes="160x160">
<link rel="icon" type="image/png" href="https://octoanswers.com/assets/img/favicon/favicon-196.png" sizes="196x196">
<link rel="apple-touch-icon" href="https://octoanswers.com/assets/img/favicon/apple-touch-icon-120.png">
<link rel="apple-touch-icon" href="https://octoanswers.com/assets/img/favicon/apple-touch-icon-152.png" sizes="152x152">
<link rel="apple-touch-icon" href="https://octoanswers.com/assets/img/favicon/apple-touch-icon-180.png" sizes="180x180">
<link rel="mask-icon" href="https://octoanswers.com/assets/img/favicon/mask-icon.svg" color="#0288D1">
<meta name="msapplication-TileColor" content="#0288D1">
<meta name="msapplication-TileImage" content="https://octoanswers.com/assets/img/favicon/msapplication-144x144.png">

<!-- stylesheet -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<link rel="stylesheet" href="https://octoanswers.com/assets/css/global.css?v=5">

<!-- Open Graph tags -->
<?php if (isset($this->openGraph['url'])): ?>
    <meta property="og:url" content="<?= $this->openGraph['url'] ?>" />
<?php endif; ?>
<?php if (isset($this->openGraph['type'])): ?>
    <meta property="og:type" content="<?= $this->openGraph['type'] ?>" />
<?php endif; ?>
<?php if (isset($this->openGraph['title'])): ?>
    <meta property="og:title" content="<?= $this->openGraph['title'] ?>" />
<?php endif; ?>
<?php if (isset($this->openGraph['description'])): ?>
    <meta property="og:description" content="<?= $this->openGraph['description'] ?>" />
<?php endif; ?>
<?php if (isset($this->openGraph['image'])): ?>
    <meta property="og:image" content="<?= $this->openGraph['image'] ?>" />
<?php endif; ?>
<?php if (isset($this->openGraph['locale'])): ?>
    <meta property="og:locale" content="<?= $this->openGraph['locale'] ?>" />
<?php endif; ?>
