<!DOCTYPE html>
<html lang="<?= $this->lang ?>">

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body>

    <?php require TEMPLATE_PATH . '/_common/navbar.phtml'; ?>

    <div class="container mt-4">
        <div class="row">

            <div class="d-none d-lg-block col-12 col-lg-2">
                <?php require TEMPLATE_PATH . '/_common/left/sections.phtml'; ?>
            </div>

            <!-- main_column -->
            <div class="col-12 col-lg-7">
                <div class="border rounded bg-white p-3">
                    <?php require __DIR__ . '/header.phtml' ?>
                    <?php require __DIR__ . '/actions.phtml' ?>
                </div>
                <?php require __DIR__ . '/nav.phtml' ?>

                <?php require TEMPLATE_PATH . '/user/main/header.phtml'; ?>
                <?php require TEMPLATE_PATH . '/user/main/actions.phtml'; ?>
                <?php require TEMPLATE_PATH . '/user/main/nav.phtml'; ?>
                <?php require TEMPLATE_PATH . '/user/main/revisions.phtml'; ?>
            </div>
            <!-- / main_column -->

            <div class="d-none d-md-block col-lg-3">
                <?php require __DIR__ . '/related_categories.phtml'; ?>
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH . '/_common/modals.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>

</body>

</html>