<!-- set username -->
<?php if ($this->authUser && ($this->authUser->id == $this->user->id) && ($this->user->name == $this->user->username)) : ?>
    <div class="alert alert-warning mb-3" role="alert">
        <p class="mb-2 semi-small"><?= $this->translator->get('user', 'alert__name', 'msg') ?></p>
        <a class="btn btn-sm btn-warning" href="<?= \Helper\URL\Settings::get_settings_URL($this->lang) ?>" role="button">
            <?= $this->translator->get('user', 'alert__name', 'action') ?>
        </a>
    </div>
<?php endif; ?>
<!-- / set username -->

<!-- set signature -->
<?php if ($this->authUser && ($this->authUser->id == $this->user->id) && !$this->user->signature) : ?>
    <div class="alert alert-warning mb-3" role="alert">
        <p class="mb-2 small"><?= $this->translator->get('user', 'alert__signature', 'msg') ?></p>
        <a class="btn btn-sm btn-block btn-warning" href="<?= \Helper\URL\Settings::get_settings_URL($this->lang) ?>" role="button">
            <?= $this->translator->get('user', 'alert__signature', 'action') ?>
        </a>
    </div>
<?php endif; ?>
<!-- /set signature -->