
<ul class="nav nav-tabs my-3">
    <li class="nav-item">
        <a class="nav-link active" href="#">
            Правки
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">
            Вопросы
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">
            Подписки
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">
            Подписчики
        </a>
    </li>
</ul>
