<ul class="nav nav-tabs pl-3 my-3">
    <li class="nav-item">
        <a class="nav-link active" href="#">
            <?= $this->translator->get('user', 'nav', 'revisions') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">
            <?= $this->translator->get('user', 'nav', 'questions') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">
            <?= $this->translator->get('user', 'nav', 'followed') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">
            <?= $this->translator->get('user', 'nav', 'followers') ?>
        </a>
    </li>
</ul>