<?php if (count($this->revisions)) : ?>
    <?php for ($i = 0; $i < count($this->revisions); $i++) : ?>
        <div class="border rounded bg-white p-2 my-4">
            <div class="mb-3 p-2">
                <a class="h5 text-dark text-decoration-none" href="<?= ($this->questions[$i])->getURL($this->lang) ?>">
                    <?= $this->questions[$i]->title ?>
                </a>
                <div class="small text-black-50">
                    <?= __('page_user.revision') ?> #<?= $this->revisions[$i]->id ?>

                    <span class="mx-1 text-dark font-weight-bold">&middot;</span>

                    <?php if ($this->revisions[$i]->comment) : ?>
                        <strong><?= $this->revisions[$i]->comment ?></strong>
                    <?php else : ?>
                        <?= __('page_user.no_description_of_changes') ?>
                    <?php endif; ?>

                    <span class="mx-1 text-dark font-weight-bold">&middot;</span>

                    <?= \Humanizer\DateTime::humanizeTimestamp($this->lang, $this->revisions[$i]->createdAt) ?>
                </div>
            </div>

            <?php $fineDiffRender = new \cogpowered\FineDiff\Render\Html; ?>

            <pre class="bg-color-body-background p-2 mb-0"><?= $fineDiffRender->process($this->revisions[$i]->baseText, $this->revisions[$i]->opcodes) ?></pre>
        </div>
    <?php endfor; ?>
<?php else : ?>
    <div class="alert alert-secondary mt-4 mb-5" role="alert">
        <?= __('page_user.no_answers.msg') ?>
    </div>
<?php endif; ?>