<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3">
                <?php require TEMPLATE_PATH.'/user/block/header.phtml'; ?>
            </div>
            <div class="col-12 col-md-9">
                <?php require TEMPLATE_PATH.'/user/block/nav.phtml'; ?>
                <?php require TEMPLATE_PATH.'/user/block/revisions.phtml'; ?>
            </div>

        </div>
    </div>

    <?php if ($this->authUser && ($this->authUser->getID() == $this->user->getID())) { require_once 'block/modal__logout.phtml'; }; ?>

    <?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
