
<!-- nav -->
<div class="list-group my-4">
    <a href="#" class="list-group-item list-group-item-action active">
        Все события
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        Новые вопросы
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        Новые темы
    </a>
    <a href="#" class="list-group-item list-group-item-action">
        Правки ответов
    </a>
    <a href="#" class="list-group-item list-group-item-action disabled">
        Добавление в друзья
    </a>
</div>
<!-- / nav -->
