<!-- flow_filter -->
<div class="bg-light p-0 p-md-3 mb-4 d-none d-lg-block">
	<div class="border-bottom pb-2 mb-3 h6 font-weight-bold">
		<?= _('Filters') ?>
	</div>

    <ul class="list-unstyled">
        <li class="my-1">
            <a href="#" class="text-secondary text-decoration-none">
                Все события
            </a>
        </li>
        <li class="my-1">
            <a href="#" class="text-secondary text-decoration-none">
                Новые вопросы
            </a>
        </li>
        <li class="my-1">
            <a href="#" class="text-secondary text-decoration-none">
                Новые темы
            </a>
        </li>
        <li class="my-1">
            <a href="#" class="text-secondary text-decoration-none">
                Правки ответов
            </a>
        </li>
        <li class="my-1">
            <a href="#" class="text-secondary text-decoration-none">
                Добавление в друзья
            </a>
        </li>
    </ul>

</div>
<!-- / flow_filter -->