<!-- flow_filter -->
<nav class="mb-4">
    <ul class="list-unstyled">
        <!-- <li>
            <a href="#">
                <?= $this->translator->get('flow', 'new_categories') ?>
                Все события
            </a>
        </li>
        <li>
            <a href="#">
                <?= $this->translator->get('flow', 'new_categories') ?>Новые вопросы
            </a>
        </li> -->
        <li>
            <a href="#">
                <?= $this->translator->get('flow', 'new_categories') ?>
            </a>
        </li>
        <!-- <li>
            <a href="#">
                <?= $this->translator->get('flow', 'new_categories') ?>
                Правки ответов
            </a>
        </li>
        <li>
            <a href="#">
                <?= $this->translator->get('flow', 'new_categories') ?>
                Добавление в друзья
            </a>
        </li> -->
    </ul>
</nav>
<!-- / flow_filter -->