<!-- flow_filter -->
<nav class="mb-4">
    <div class="h5 text-muted">
        <?= $this->translator->get('Filters') ?>
    </div>
    <ul class="list-links">
        <li>
            <a href="#">
                Все события
            </a>
        </li>
        <li>
            <a href="#">
                Новые вопросы
            </a>
        </li>
        <li>
            <a href="#">
                <?= $this->translator->get('flow', 'new_categories') ?>
            </a>
        </li>
        <li>
            <a href="#">
                Правки ответов
            </a>
        </li>
        <li>
            <a href="#">
                Добавление в друзья
            </a>
        </li>
    </ul>
</nav>
<!-- / flow_filter -->