<!-- drawer other_languages -->

<hr class="mdc-list-divider">
<h6 class="mdc-list-group__subheader"><?= $this->translator->get('drawer__other_languages', 'title') ?></h6>

<a class="mdc-list-item" href="<?= Page_URL_Helper::getMainURL('en') ?>">
	<i class="material-icons mdc-list-item__graphic" aria-hidden="true">language</i>
	<span class="mdc-list-item__text"><?= $this->translator->get('drawer__other_languages', 'english') ?></span>
</a>
<a class="mdc-list-item" href="<?= Page_URL_Helper::getMainURL('ru') ?>">
	<i class="material-icons mdc-list-item__graphic" aria-hidden="true">language</i>
	<span class="mdc-list-item__text"><?= $this->translator->get('drawer__other_languages', 'russian') ?></span>
</a>
<a class="mdc-list-item" href="<?= SITE_URL ?>">
	<i class="material-icons mdc-list-item__graphic" aria-hidden="true">g_translate</i>
	<span class="mdc-list-item__text"><?= $this->translator->get('drawer__other_languages', 'all_languages') ?></span>
</a>

<!-- / drawer  other_languages -->
