<!-- nav_other_languages -->
<nav class="collapse bd-links" id="nav-other-languages">
<div class="bd-toc-item active">
		<a class="bd-toc-link" href="#">
			<?= $this->translator->get('In other languages') ?>
		</a>
		<ul class="nav bd-sidenav">
			<li>
				<a data-lang="ru" href="<?= Page_URL_Helper::getMainURL('en') ?>">
					<?= $this->translator->get('English') ?>
				</a>
			</li>
			<li>
				<a data-lang="ru" href="<?= Page_URL_Helper::getMainURL('ru') ?>">
					<?= $this->translator->get('Russian') ?>
				</a>
			</li>
			<li>
				<a data-lang="en" href="<?= SITE_URL ?>">
				<i class="fas fa-globe-americas"></i>&nbsp;<?= $this->translator->get('All languages') ?>
				</a>
			</li>
		</ul>
	</div>
</nav>
<!-- / nav_other_languages -->
