<div class="semi-small font-weight-bold text-uppercase text-primary mt-2 mb-3">
    <?= __('common.sections.title') ?>
</div>

<ul class="list-unstyled semi-small mb-0">

    <li class="my-2">
        <a href="<?= \Helper\URL\Questions::getNewestURL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= __('common.sections.questions') ?>
        </a>
    </li>

    <li class="my-2">
        <a href="<?= \Helper\URL\Categories::getNewestURL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= __('common.sections.popular_categories') ?>
        </a>
    </li>

    <li class="my-2">
        <a href="<?= \Helper\URL\Sandbox::getWithoutAnswersURL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= __('common.sections.sandbox') ?>
            <!-- <i class="material-icons md-18">outlined_flag</i> -->
        </a>
    </li>

    <li class="my-2">
        <a href="<?= \Helper\URL\Page::getFlowURL($this->lang) ?>" class="text-dark text-decoration-none">
            <?= __('common.sections.recent_changes') ?>
        </a>
    </li>

    <li class="my-2">
        <a href="<?= SITE_URL . '/' . $this->lang . '/random-question' ?>" class="text-dark text-decoration-none">
            <?= __('common.sections.random_question') ?>
        </a>
    </li>
</ul>