
<div class="mb-4">
		
	<?php if ($this->authUser): ?>
		<button
			class="btn follow_question_button mb-2 mr-2 <?= $this->followed ? 'followed btn-success' : 'btn-outline-secondary'; ?>"
			data-question-id="<?= $this->question->id ?>"
			data-follow-title="<?= _('Follow') ?>"
			data-followed-title="<?= _('Followed') ?>"
			data-unfollow-title="<?= _('Unfollow') ?>"
			type="button">
			<?= $this->followed ? _('Followed') : _('Follow'); ?>
		</button>
	<?php else: ?>
		<button type="button" class="btn btn-outline-secondary mb-2 mr-2" data-toggle="modal" data-target="#modal__follow_question_lure">
			<?= _('Follow'); ?>
		</button>
		<?php require_once TEMPLATE_PATH.'/_modal/question/_lure/follow_question.phtml' ?>
	<?php endif; ?>

	

</div>
