
<button class="mdc-button mdc-button--outlined">
	<i class="material-icons mdc-button__icon" aria-hidden="true">favorite</i>
	<span class="mdc-button__label">Button</span>
</button>
<button class="mdc-button">
	<span class="mdc-button__label">Button</span>
</button>

<button class="mdc-button mdc-button--outlined">
	<span class="mdc-button__label">Подписаться</span>
</button>

<button class="mdc-button mdc-button--raised mdc-theme--background mdc-ripple-upgraded">
	Raised
</button>
<!-- actions_top -->
<div class="mt-3 mb-3">
	<ul class="nav nav-tabs">
		<li class="nav-item">
			<a class="nav-link active" href="<?= $this->question->getURL($this->lang) ?>">
				<?= $this->translator->get('Question') ?>
			</a>
		</li>

		<!-- edit answer -->
		<?php if ($this->authUser): ?>
			<li class="nav-item">
				<a class="nav-link" href="<?= $this->question->getEditURL($this->lang) ?>">
					<?= $this->translator->get("question", "actions_top", "edit_answer") ?>
				</a>
			</li>
		<?php else: ?>
			<li class="nav-item">
				<a class="nav-link" href="#" data-toggle="modal" data-target="#modal_lure__edit_answer">
					<?= $this->translator->get('Edit') ?>
				</a>
				<?php require_once TEMPLATE_PATH.'/_modal/question/_lure/edit_answer.phtml' ?>
			</li>
		<?php endif; ?>
		<!-- / edit answer -->

		<!-- tab_history -->
		<?php if (mb_strlen($this->question->answer->text) > 0): ?>
			<li class="nav-item">
				<a class="nav-link" href="<?= $this->question->getHistoryURL($this->lang) ?>">
					<?= $this->translator->get('History') ?>
				</a>
			</li>		
		<?php else: ?>
			<li class="nav-item">
				<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><?= $this->translator->get('History') ?></a>
			</li>
		<?php endif; ?>
		<!-- tab_history -->

		<li class="nav-item">
			<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Обсуждение</a>
		</li>

	</ul>
</div>
<!-- / actions_top -->