<?php if (isset($this->question->answer) && $this->question->answer->text) : ?>
    <?= $this->formattedAnswerText ?>
<?php endif; ?>

<div class="mt-2 text-secondary">

    <button type="button" class="btn btn-sm btn-outline-gray mr-3">
        <i class="material-icons md-14">thumb_up</i>
        <?= $this->translator->get('main', 'item__top_question', 'upvote') ?>
    </button>

    <!-- updated_at -->
    <?php if (strlen($this->question->answer->text)) : ?>
        <span class="semi-small text-black-50" title="<?= $this->translator->get('Minutes to read') ?>">
            <?= $this->translator->get('question', 'answer_updated') . ': ' . \Humanizer\DateTime::humanize_timestamp($this->lang, $this->question->answer->updatedAt) ?>
        </span>
    <?php endif; ?>
    <!-- / updated_at -->

</div>