
<!-- categories_top -->
<div>
	<?php if (count($this->firstTwoCategories)): ?>

		<?php foreach ($this->firstTwoCategories as $category): ?>
			<a class="text-decoration-none mb-2 mr-2" href="<?= $category->getURL($this->lang) ?>">
				#<?= $category->title ?>
			</a>
		<?php endforeach; ?>

        <?php if (count($this->categories) > count($this->firstTwoCategories)): ?>
            <a class="btn btn-outline-secondary btn-sm" data-scroll href="#question_categories_list">
                more
            </a>
		<?php endif; ?>

	<?php endif; ?>
</div>
<!-- / categories_top -->
