
<?php if (count($this->contributors)): ?>
	<!-- contributors_full -->
	<div class="my-5">
		<div class="mb-3">
			<span class="float-right text-black-50">
				<span class="font-weight-bold"><?= count($this->contributors) ?></span>&nbsp;<i class="far fa-user"></i>
			</span>
			<div class="h6 font-weight-bold border-bottom pb-2 mb-3">
				<?= $this->translator->get('Answer contributors') ?>
			</div>
		</div>

		<?php foreach ($this->contributors as $contributor): ?>
			<a class="wh-2 mr-2 mb-2" href="<?= $contributor->getURL($this->lang) ?>">
				<img class="wh-2 rounded mt-1" src="<?= $contributor->getAvatarMediumURL() ?>" alt="<?= $contributor->name ?>">
			</a>
		<?php endforeach; ?>
	</div>
	<!-- / contributors tail -->
<?php endif; ?>
