
<?php if (count($this->question->getHashtags())): ?>
	<!-- hashtags -->
	<div class="my-5" id="question_hashtags_list">
		<div class="font-weight-bold border-bottom pb-1 mb-3">
			<?= $this->translator->get('question__hashtags_block', 'title') ?>
		</div>

        <?php foreach ($this->question->getHashtags() as $hashtag): ?>
            <a class="btn btn-outline-primary mb-2 mr-2" href="<?= $hashtag->getURL($this->lang) ?>">
				#<?= $hashtag->title ?>
			</a>
		<?php endforeach; ?>

		<?php if ($this->authUser): ?>
			<a class="btn btn-outline-secondary btn-sm ml-2" href="<?= $this->question->getUpdateHashtagsURL($this->lang) ?>" rel="nofollow">
				<?= $this->translator->get('question__hashtags_block', 'hashtags_change') ?>
			</a>
		<?php endif; ?>

	</div>

    <!-- / hashtags -->

<?php else: ?>

	<?php if ($this->authUser): ?>
        <div class="my-5" id="question_hashtags_list">
            <div class="font-weight-bold border-bottom pb-1 mb-3">
                <?= $this->translator->get('question__hashtags_block', 'title') ?>
            </div>
		
			<a class="btn btn-outline-primary mb-2 mr-2" href="<?= $this->question->getUpdateHashtagsURL($this->lang) ?>">
                <i class="fas fa-plus mr-1"></i>
                <?= $this->translator->get('question__hashtags_block', 'hashtags_add') ?>
			</a>
		</div>
	<?php endif; ?>

<?php endif; ?>
