
<!-- hashtags_top -->
<div>
	<?php if (count($this->question->getHashtags())): ?>

		<?php foreach ($this->question->getFirstTwoHashtags() as $hashtag): ?>
			<a class="font-weight-bold text-decoration-none mb-2 mr-2" href="<?= Hashtag_URL_Helper::getURLFromTitle($this->lang, $hashtag) ?>">
				#<?= $hashtag ?>
			</a>
		<?php endforeach; ?>

		<?php if (count($this->question->getHashtags()) > count($this->question->getFirstTwoHashtags())): ?>
			<a class="text-secondary text-decoration-none mb-2 mr-2" data-scroll href="#question_hashtags_list">
				+<?= $this->question->getHumanizedMoreHashtags() ?>
			</a>
		<?php endif; ?>

	<?php endif; ?>
</div>
<!-- / hashtags_top -->
