
<!-- hashtags_top -->
<div>
	<?php if (count($this->question->getHashtags())): ?>

		<?php foreach ($this->question->getFirstTwoHashtags() as $hashtag): ?>
			<a class="text-decoration-none mb-2 mr-2" href="<?= $hashtag->getURL($this->lang) ?>">
				#<?= $hashtag->title ?>
			</a>
		<?php endforeach; ?>

        <?php if ($this->question->getMoreHashtagsCount()): ?>
            <a class="btn btn-outline-secondary btn-sm" data-scroll href="#question_hashtags_list">
                +<?= $this->question->getMoreHashtagsCount() ?> #
            </a>
		<?php endif; ?>

	<?php endif; ?>
</div>
<!-- / hashtags_top -->
