
<?php if (isset($this->question->answer) && !$this->question->answer->text): ?>
    <?php if ($this->authUser): ?>

        <!-- lure be_first_contributor -->
        <div class="alert alert-primary py-3 my-4" role="alert">
            <h4 class="alert-heading"><?= $this->translator->get('question', 'lure_be_first_contributor', 'title') ?></h4>
            <p><?= $this->translator->get('question', 'lure_be_first_contributor', 'message') ?></p>
            <hr>
            <p class="mb-0">
                <a class="btn btn-primary" href="<?= $this->question->getEditURL($this->lang) ?>">
                    <?= $this->translator->get('question', 'lure_be_first_contributor', 'btn_write') ?>
                </a>
            </p>
        </div>
        <!-- / lure be_first_contributor -->

    <?php else: ?>
        <!--noindex-->
        <!--googleoff: index-->

        <!-- lure be_first_contributor -->
        <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-4">
            <div class="mr-3 d-none d-sm-block">
                <p class="h1">
                    <i class="fas fa-trophy color-danger"></i>
                </p>
            </div>
            <div class="width-full">
                <div class="color-secondary-dark-4 font-weight-bold mb-2">
                    <?= $this->translator->get('Be the first author') ?>!
                </div>
                <div class="small color-secondary-dark-2 mb-3">
                    <?= $this->translator->get('Still no one tried to write an answer to this question. Be the first if the category of the question is close to you!') ?>
                </div>
                <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#first_answer__signup">
                    <?= $this->translator->get('Write first answer') ?>
                </a>
            </div>
        </div>
        <!-- / lure be_first_contributor -->

        <?php require_once TEMPLATE_PATH.'/_modal/question/_lure/first_answer_signup.phtml' ?>

        <!--googleon: index -->
        <!--/noindex-->
    <?php endif; ?>
<?php endif; ?>
