
<?php if (isset($this->question->answer) && !$this->question->answer->text): ?>
    <?php if ($this->authUser): ?>

        <!-- lure be_first_contributor -->
        <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-4">
            <div class="mr-3 d-none d-sm-block">
                <p class="h1">
                    <i class="fas fa-trophy" style="color: #e51e24;"></i>
                </p>
            </div>
            <div class="width-full">
                <div class="color-gray-900 font-weight-bold mb-2">
                    <?= _('Be the first author') ?>!
                </div>
                <div class="small color-gray-700 mb-3">
                    <?= _('Still no one tried to write an answer to this question. Be the first if the hashtag of the question is close to you!') ?>
                </div>
                <a  class="btn btn-sm btn-outline-primary" href="<?= $this->question->getEditURL($this->lang) ?>">
                    <?= _('Write first answer') ?>
                </a>
            </div>
        </div>
        <!-- / lure be_first_contributor -->

    <?php else: ?>
        <!--noindex-->
        <!--googleoff: index-->

        <!-- lure be_first_contributor -->
        <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-4">
            <div class="mr-3 d-none d-sm-block">
                <p class="h1">
                    <i class="fas fa-trophy color-danger"></i>
                </p>
            </div>
            <div class="width-full">
                <div class="color-gray-900 font-weight-bold mb-2">
                    <?= _('Be the first author') ?>!
                </div>
                <div class="small color-gray-700 mb-3">
                    <?= _('Still no one tried to write an answer to this question. Be the first if the hashtag of the question is close to you!') ?>
                </div>
                <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#first_answer__signup">
                    <?= _('Write first answer') ?>
                </a>
            </div>
        </div>
        <!-- / lure be_first_contributor -->

        <?php require_once TEMPLATE_PATH.'/_modal/question/_lure/first_answer_signup.phtml' ?>

        <!--googleon: index -->
        <!--/noindex-->
    <?php endif; ?>
<?php endif; ?>
