<?php if (isset($this->related_questions) && count($this->related_questions)) : ?>
	<div class="my-5">
		<!-- related questions -->
		<div class="subtitle-1 mb-2 text-secondary">
			<?= $this->translator->get('question', 'block__related_questions', 'title') ?>
		</div>

		<?php foreach ($this->related_questions as $question) : ?>
			<div class="my-2">
				<a class="h4 text-dark text-decoration-none" href="<?= $question->getURL($this->lang) ?>">
					<?= $question->title ?>
				</a>
				<div class="small text-secondary">
					<?= $this->translator->get('Answer updated') ?> <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->answer->updatedAt) ?>

					<?php if (strlen($question->answer->text) == 0) : ?>
						<span class="mx-1 text-dark font-weight-bold">&middot;</span>
						<a rel="nofollow" href="<?= $question->getEditURL($this->lang) ?>">
							<?= $this->translator->get('Write first answer') ?>
						</a>
					<?php endif; ?>
				</div>
			</div>
		<?php endforeach; ?>
		<!-- / related questions -->
	</div>
<?php endif; ?>