
<?php if (isset($this->related_questions)): ?>
<div class="my-5">
	<!-- related questions -->
	<div class="h4 mb-3">
		<?= $this->translator->get('question', 'block__related_questions', 'title') ?>
	</div>

	<?php foreach ($this->related_questions as $question): ?>
		<div class="my-2">
			<a class="lead color-secondary-dark-3 text-decoration-none" href="<?= $question->getURL($this->lang) ?>">
				<?= $question->title ?>
			</a>
			<div class="small color-secondary-light-1">
				<?= $this->translator->get('Answer updated') ?> <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->answer->updatedAt) ?>

				<?php if (strlen($question->answer->text) == 0): ?>
					<span class="mx-1 color-secondary-dark-4 font-weight-bold">&middot;</span>
					<a rel="nofollow" href="<?= $question->getEditURL($this->lang) ?>">
						<?= $this->translator->get('Write first answer') ?>
					</a>
				<?php endif; ?>
			</div>
		</div>
	<?php endforeach; ?>
	<!-- / related questions -->
</div>
<?php endif; ?>
