<div class="my-5">
    <div class="text-uppercase text-secondary mb-3">
        <?= $this->translator->get('Share link') ?>
    </div>

    <script src="//yastatic.net/share2/share.js" async="async" charset="utf-8"></script>
    <div class="ya-share2" style="min-height: 24px;" data-services="twitter,vkontakte,facebook,gplus,pinterest,delicious,digg,reddit,pocket,tumblr,collections,telegram" data-size="m" data-counter="" data-title="<?= $this->share_link['title'] ?>" data-description="<?= $this->share_link['description'] ?>" data-url="<?= $this->share_link['url'] ?>" data-image="<?= $this->share_link['image'] ?>"></div>

</div>