<div class="my-5">
    <div class="subtitle-1 mb-3 text-secondary">
        <?= $this->translator->get('Share link') ?>
    </div>

    <script src="//yastatic.net/share2/share.js" async="async" charset="utf-8"></script>
    <div class="ya-share2" style="min-height: 24px;" data-services="twitter,vkontakte,facebook,gplus,pinterest,delicious,digg,reddit,pocket,tumblr,collections,telegram" data-size="m" data-counter="" data-title="<?= $this->shareLink['title'] ?>" data-description="<?= $this->shareLink['description'] ?>" data-url="<?= $this->shareLink['url'] ?>" data-image="<?= $this->shareLink['image'] ?>"></div>

</div>