
<?php if (isset($this->question->answer) && !$this->question->answer->text && !$this->authUser): ?>

    <!-- lure subscribe -->
    <div class="d-flex box px-2 bg-color-gray-50 px-sm-3 py-2 py-sm-3 my-4">
        <div class="mr-3 d-none d-sm-block">
            <p class="h1 text-center mx-auto">
                <i class="fas fa-mail" style="color: #2BB462;"></i>
            </p>
        </div>
        <div class="width-full">
            <div class="color-gray-900 font-weight-bold mb-2">
                <?= _('Subscription to the question') ?>
            </div>
            <div class="small color-gray-700 mb-3">
                <?= _('Enter your email address to get notified about the answer as soon as it appears') ?>
            </div>

            <form id="form__question_subscribe">
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">@</span>
                    </div>
                    <input type="hidden" id="question_id" value="<?= $this->question->getID(); ?>">
                    <input type="email" id="email" class="form-control" placeholder="<?= _('Your email') ?>">
                </div>
            </form>

        </div>
    </div>
    <!-- / lure subscribe -->

<?php endif; ?>
