
<?php if (count($this->questions) == 0 && strlen($this->query) == 0): ?>
    <div class="alert alert-secondary pb-5 mt-4">
        <div class="text-center">
            <p class="mb-2"><strong><?= _('No questions found') ?></strong></p>
            <p class="mb-4">
                <?= str_replace('%query%', $this->query, _('On request "%query%" could not find any questions')); ?>
            </p>
            <a class="btn btn-outline-primary" href="#" role="button">
                <?= _('View all questions') ?>
            </a>
        </div>
    </div>
<?php endif; ?>
