
<?php if ($this->list == 'questions' && count($this->questions) == 0 && strlen($this->query) > 0): ?>
    <div class="alert alert-secondary my-4">

        <p class="font-weight-bold"><?= $this->translator->get('No questions found') ?></p>
        <p><?= str_replace('%query%', $this->query, $this->translator->get('On request "%query%" could not find any questions')); ?></p>

        <a class="btn btn-primary mb-2" href="<?= Questions_URL_Helper::getNewestURL($this->lang) ?>" role="button">
            <?= $this->translator->get('View all questions') ?>
        </a>
    </div>
<?php endif; ?>
