
<!-- modal_ask -->
<div class="modal fade" id="modal_ask" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <?= _('New question') ?>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form__question_create">
                <div class="modal-body">
                    <div class="form-group">
                        <label>
                            <?= _('Ask questions in a form understandable to real people - they will answer, not search robots.') ?>.
                        </label>
                        <textarea class="form-control" id="question_title" rows="6" placeholder="<?= _('What is your question?') ?>?"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="form__question_create__submit" class="btn btn-block btn-primary">
                        <?= _('Ask a question') ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- / modal_ask -->
