
<?php if (!$this->authUser): ?>
	
	<!-- about_answeropedia -->
	<div class="bg-light p-0 p-md-3 mb-4 d-none d-lg-block">
		<div class="border-bottom pb-2 mb-2 h6 font-weight-bold">
			<?= _('About Answeropedia') ?>
		</div>

		<p><?= _('Answeropedia is like Wikipedia, only for questions and answers. You ask a question and get one complete, comprehensive and competent answer from the community.') ?></p>

		<button role="button" data-toggle="modal" data-target="#modal_signup" class="btn btn-danger btn-block mt-4">
			<?= _('Join the community') ?>
		</button>
	</div>
	<!-- / about_answeropedia -->

<?php endif; ?>
