
<!-- right_actions -->
<div class="my-5">

	<div class="mb-3">
		<div class="font-weight-bold border-bottom pb-2 mb-2">
			<?= $this->translator->get('Actions') ?>
		</div>
	</div>
	<ul class="list-unstyled">
		
		<!-- add or update image -->
		<?php if ($this->authUser): ?>
			<li class="my-1">
				<a class="text-muted text-decoration-none" href="#" data-toggle="modal" data-target="#modal_upload_image">
					<i class="fas fa-camera mr-1"></i>
					<?php if ($this->question->imageBaseName): ?>
						<?= $this->translator->get('Update picture') ?>
					<?php else: ?>
						<?= $this->translator->get('Add picture') ?>
					<?php endif; ?>
				</a>
			</li>
		<?php endif; ?>
		<!-- add or update image -->

		<?php if ($this->authUser): ?>
			<!-- rename question -->
			<li class="my-1">
				<a class="text-muted text-decoration-none" href="#" data-toggle="modal" data-target="#modal_rename">
					<i class="fas fa-edit mr-1"></i>&nbsp;<?= $this->translator->get('Rename question') ?>	
				</a>
			</li>
			<!-- / rename question -->
		<?php endif; ?>
			
		<li class="my-1">
			<a class="small text-muted text-decoration-none" href="#" rel="nofollow">
				<s><?= $this->translator->get('Report') ?></s>
			</a>
		</li>
		
	</ul>
</div>
<!-- / right_actions -->

