<!-- right_actions -->

<nav class="my-4">
	<div class="text-uppercase semi-small mb-2 text-secondary">
		<?= $this->translator->get('question', 'actions') ?>
	</div>
	<ul class="list-links">

		<!-- add or update image -->
		<?php if ($this->authUser) : ?>
			<li>
				<a href="#" data-toggle="modal" data-target="#modal_upload_image">
					<i class="material-icons md-18 w-32px">image</i><?= ($this->question->imageBaseName) ? $this->translator->get('question', 'update_picture') : $this->translator->get('question', 'add_picture') ?>
				</a>
			</li>
		<?php endif; ?>
		<!-- add or update image -->

		<?php if ($this->authUser) : ?>
			<!-- rename question -->
			<li>
				<a href="#" data-toggle="modal" data-target="#modal_rename_question">
					<i class="material-icons md-18 w-32px">edit</i><?= $this->translator->get('question', 'rename_question') ?>
				</a>
			</li>
			<!-- / rename question -->
		<?php endif; ?>

		<li>
			<a href="#" rel="nofollow">
				<i class="material-icons md-18 w-32px">report</i><s><?= $this->translator->get('question', 'report') ?></s>
			</a>
		</li>

		<li>
			<a rel="nofollow" target="_blank" href="<?= \Helper\URL\DDG::get_search_URL($this->question->title) ?>">
				<i class="material-icons md-18 w-32px">link</i><?= $this->translator->get('question', 'search_in_ddg') ?>
			</a>
		</li>

	</ul>
</nav>

<!-- / right_actions -->