
<?php if (count($this->contributors_top)): ?>
	<!--noindex-->
	<!--googleoff: index-->

	<!-- top contributors @ sidebar -->
	<div class="mb-4">
		<a class="float-right text-black-50 text-decoration-none" data-scroll href="#contributors_full_list">
			<?= count($this->contributors).'&nbsp;'.mb_strtolower(ngettext("Contributor", "Contributors", count($this->contributors))) ?>
		</a>
		<div class="h6 font-weight-bold border-bottom pb-2 mb-3">
			<?= _('Top contributors') ?>
		</div>
	</div>
		
	<?php foreach ($this->contributors_top as $contributor): ?>

	<div class="media position-relative mb-3">
        <a class="wh-3 mr-3" href="<?= $contributor->getURL($this->lang) ?>">
    		<img src="<?= $contributor->getAvatarMediumURL() ?>" class="wh-3" alt="<?= $contributor->getName() ?>">
        </a>
		<div class="media-body">
			<a class="h6 mt-0 mr-2 font-weight-bold text-dark text-decoration-none" href="<?= $contributor->getURL($this->lang) ?>">
				<?= $contributor->getName() ?>
			</a>

			<span class="small text-muted font-weight-normal">
                <i class="fas fa-battery-three-quarters"></i>&nbsp;<?= Contribution_Humanizer::humanizeCount($contributor->contribution) ?>
			</span>

			<p class="text-secondary mb-0">
				<?= $contributor->getSignature() ? $contributor->getSignature() : $contributor->getUsername() ?>
				<?php if ($contributor->getSite()): ?>
					<a href="<?= $contributor->getSite() ?>">
						<?= parse_url($contributor->getSite(), PHP_URL_HOST) ?>
					</a>
				<?php endif; ?>
			</p>
		</div>
	</div>
	<?php endforeach; ?>

	<!--
	<?php if (count($this->contributors) > count($this->contributors_top)): ?>
		<div class="box-footer">
			<a class="ml-5 small" data-scroll href="#contributors_full_list">
				<?= _('All answer contributors') ?>
			</a>
		</div>
	<?php endif; ?>
	-->

	<!-- / top contributors @ sidebar -->

	<!--googleon: index -->
	<!--/noindex-->
<?php endif; ?>
