
<?php if ($this->question->imageBaseName): ?>
	<div class="mb-3">

		<img id="question_image" class="w-100 border" src="<?= $this->question->getImageURLMedium($this->lang) ?>" alt="<?= $this->question->title ?>">

		<?php if ($this->authUser): ?>
			<div class="text-right mt-1">
				<a class="small text-decoration-none text-secondary" rel="nofollow" href="#" data-toggle="modal" data-target="#modal_upload_image">
					<i class="material-icons md-18 mr-1">image</i>
					<?= $this->translator->get('Update picture') ?>
				</a>
			</div>
		<?php endif; ?>

	</div>
<?php endif; ?>
