
<!-- info_about_question -->
<div class="my-5">
    <div class="mb-3">
		<div class="font-weight-bold border-bottom pb-2 mb-2">
            <!-- <?= $this->translator->get('Actions') ?> -->
            Информация
		</div>
	</div>
	<ul class="list-unstyled">
		<li>
			<span class="semi-small text-muted">
				<?= $this->translator->get('Answer updated').': '.DateTime_Humanizer::humanizeTimestamp($this->lang, $this->question->answer->updatedAt) ?>
			</span>
		</li>
	</ul>
</div>
<!-- / info_about_question -->
