<!-- info_about_question -->

<nav class="my-4">
	<div class="subtitle-1 mb-1 text-secondary">
		<?= $this->translator->get('question', 'block_info', 'title') ?>
	</div>
	<ul class="list-links">
		<li>
			<?= $this->translator->get('Answer updated') . ': ' . DateTime_Humanizer::humanizeTimestamp($this->lang, $this->question->answer->updatedAt) ?>
		</li>
		<!-- <li>
			<a data-lang="ru" href="<?= Page_URL_Helper::getMainURL('ru') ?>">
				<?= $this->translator->get('sidebar__other_languages', 'russian') ?>
			</a>
		</li>
		<li>
			<a href="<?= SITE_URL ?>">
				<?= $this->translator->get('sidebar__other_languages', 'all_languages') ?>
			</a>
		</li> -->
	</ul>
</nav>

<!-- / info_about_question -->