<!-- info_about_question -->

<nav class="my-4">
	<div class="semi-small text-uppercase text-secondary mb-1">
		<?= $this->translator->get('question', 'block_info', 'title') ?>
	</div>
	<ul class="list-links">
		<li>
			<?= $this->translator->get('Answer updated') . ': ' . DateTime_Humanizer::humanizeTimestamp($this->lang, $this->question->answer->updatedAt) ?>
		</li>
	</ul>
</nav>

<!-- / info_about_question -->