
<h1 class="mb-4">
    Темы вопроса
</h1>
<p><?= $this->question->title ?></p>

<form id="form__update_hashtags" data-question-id="<?= $this->question->id ?>">
    <div class="form-group">
        <input id="new_hashtags" type="text" class="form-control mt-3" value="<?= $this->hashtags_string ?>">
    </div>
    <div class="form-group mt-5">
        <button type="submit" id="form__update_hashtags__submit" class="btn btn-primary">
            Обновить темы
        </button>
        <a href="<?= $this->question->getURL($this->lang) ?>" class="btn color-secondary-dark-4">
            Вернуться к вопросу
        </a>
    </div>
</form>
