
<?php if (strlen($this->authUser->getSignature()) == 0): ?>
    <!-- lure set_signature -->
    <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-3">
        <div class="mr-3 d-none d-sm-block">
            <img class="size-4 rounded mt-1" src="https://png.icons8.com/small/32/DBC234/signature.png">
        </div>
        <div class="width-full">
            <div class="color-gray-900 font-weight-600 mb-2">
                Придумайте подпись
            </div>
            <div class="small color-gray-700 mb-3">
                Подпись описывает ваши профессиональные навыки и знания. Она показываться рядом с правками ответов, которые вы делаете.
            </div>
            <a  class="btn btn-sm btn-outline-primary" href="<?= Settings_URL_Helper::getSignatureURL($this->lang) ?>">
                Задать подпись
            </a>
        </div>
    </div>
    <!-- / lure set_signature -->
<?php endif; ?>
