<!DOCTYPE html>
<html lang="<?= $this->lang ?>">

<head>
    <?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body>

    <?php require_once TEMPLATE_PATH . '/_common/navbar.phtml'; ?>

    <div class="container mt-4">
        <div class="row">

            <div class="d-none d-lg-block col-12 col-lg-2">
                <?php require_once TEMPLATE_PATH . '/_common/left/sections.phtml'; ?>
            </div>

            <!-- main_column -->
            <div class="col-12 col-lg-7">

                <?php require_once __DIR__ . '/header.phtml'; ?>

                <form id="form__update_answer" data-answer-id="<?= $this->answer->id ?>">
                    <div class="form-group">
                        <textarea id="form__update_answer__answer_text" name="answer_text" class="form-control" rows="10"><?= $this->answer->text ?></textarea>
                        <label class="mt-0 small text-muted"><?= __('page_answer_edit.description_of_changes') ?></label>
                        <input id="form__update_answer__changes_comment" type="text" class="form-control">
                    </div>
                    <div class="form-group mt-4">
                        <button type="submit" id="form__update_answer__submit" class="btn btn-success btn-lg btn-block">
                            <?= __('common.btn.save') ?>
                        </button>
                    </div>
                </form>

                <?php require_once __DIR__ . '/simplemde.phtml'; ?>

            </div>
            <!-- / main_column -->

            <div class="d-none d-md-block col-lg-3">
                <?php if ($this->question_how_to_edit) : ?>
                    <!-- <p class="card-text small text-secondary">
                        <a class="text-secondary" href="<?= $this->question_how_to_edit->get_URL($this->lang) ?>">
                            <?= $this->question_how_to_edit->title ?>
                        </a>
                    </p> -->
                <?php endif; ?>
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH . '/_common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH . '/_common/modals.phtml'; ?>
    <?php require TEMPLATE_PATH . '/_common/js.phtml'; ?>

</body>

</html>