
<?php require_once TEMPLATE_PATH.'/answer_edit/main/header.phtml'; ?>

<form id="form__update_answer" data-answer-id="<?= $this->answer->id ?>">
    <div class="form-group">
        <textarea id="form__update_answer__answer_text" name="answer_text" class="form-control" rows="10"><?= $this->answer->text ?></textarea>
        <label class="mt-0 small text-muted"><?= $this->translator->get('Description of changes') ?></label>
        <input id="form__update_answer__changes_comment" type="text" class="form-control">
    </div>
    <div class="form-group mt-4">
        <button type="submit" id="form__update_answer__submit" class="btn btn-success btn-lg btn-block">
            <?= $this->translator->get('Save') ?>
        </button>
    </div>
</form>

<?php require_once TEMPLATE_PATH.'/answer_edit/main/simplemde.phtml'; ?>
