
<?php require_once __DIR__.'/main/header.phtml'; ?>


<form id="form__update_hashtags" data-question-id="<?= $this->question->id ?>">
    <div class="form-group">
        <input id="new_hashtags" data-role="tagsinput" type="text" class="form-control mt-3" value="<?= $this->hashtags_string ?>">
    </div>
    <div class="form-group mt-5">
        <button type="submit" id="form__update_hashtags__submit" class="btn btn-primary">
            Обновить темы
        </button>
    </div>
</form>

