
<?php require_once __DIR__.'/main/header.phtml'; ?>

<form id="form__update_categories" data-question-id="<?= $this->question->id ?>">
    <div class="form-group">
        <input id="new_categories" data-role="tagsinput" type="text" class="typeahead form-control mt-3" value="<?= $this->categories_string ?>">
    </div>
    <div class="form-group mt-5">
        <button type="submit" id="form__update_categories__submit" class="btn btn-primary">
            <?= $this->translator->get('question_update_categories', 'btn_update_categories') ?> 
        </button>
    </div>
</form>
