
<?php require_once __DIR__.'/main/header.phtml'; ?>


<form id="form__update_categories" data-question-id="<?= $this->question->id ?>">
    <div class="form-group">
        <input id="new_categories" data-role="tagsinput" type="text" class="typeahead form-control mt-3" value="<?= $this->categories_string ?>">
    </div>
    <div class="form-group mt-5">
        <button type="submit" id="form__update_categories__submit" class="btn btn-primary">
            <?= $this->translator->get('question_update_categories', 'btn_update_categories') ?> 
        </button>
    </div>
</form>


<style>

.accordion {
    margin-bottom:-3px;
}

.accordion-group {
    border: none;
}

.twitter-typeahead .tt-query,
.twitter-typeahead .tt-hint {
    margin-bottom: 0;
}

.twitter-typeahead .tt-hint
{
    display: none;
}

.tt-menu {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 160px;
    padding: 5px 0;
    margin: 2px 0 0;
    list-style: none;
    font-size: 14px;
    background-color: #ffffff;
    border: 1px solid #cccccc;
    border: 1px solid rgba(0, 0, 0, 0.15);
    border-radius: 4px;
    -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    background-clip: padding-box;
    cursor: pointer;
}

.tt-suggestion {
    display: block;
    padding: 3px 20px;
    clear: both;
    font-weight: normal;
    line-height: 1.428571429;
    color: #333333;
    white-space: nowrap;
}

.tt-suggestion:hover,
.tt-suggestion:focus {
  color: #ffffff;
  text-decoration: none;
  outline: 0;
  background-color: #428bca;
}
</style>