<?php if ($this->list == 'categories' && count($this->categories) == 0 && strlen($this->query) > 0) : ?>
    <div class="alert alert-secondary my-4">

        <p class="font-weight-bold"><?= __('page_search.no_categories_found') ?></p>
        <p>
            <?= str_replace('%query%', $this->query, __('page_search.no_category_found_for_query')); ?>
        </p>

        <a class="btn btn-primary mb-2" href="<?= \Helper\URL\Categories::getNewestURL($this->lang) ?>" role="button">
            <?= __('page_search.view_all_categories') ?>
        </a>
    </div>
<?php endif; ?>