<?php require __DIR__.'/main/nav.phtml'; ?>

<form class="form-inline" id="navbar_search_form">
	<input id="navbar_search_form_query" class="form-control" type="search"
		placeholder="<?= $this->translator->get('navbar', 'saarch_placeholder') ?>"
		aria-label="Search">
</form>

<?php require __DIR__.'/main/search_form.phtml'; ?>

<?php require_once __DIR__.'/main/questions.phtml' ?>
<?php require_once __DIR__.'/main/questions_not_found.phtml' ?>

<?php require_once __DIR__.'/main/hashtags.phtml' ?>
<?php require_once __DIR__.'/main/hashtags_not_found.phtml' ?>

<?php require_once __DIR__.'/main/users.phtml' ?>
<?php require_once __DIR__.'/main/users_not_found.phtml' ?>