
<?php require __DIR__.'/main/nav.phtml'; ?>
<?php require __DIR__.'/main/search_form.phtml'; ?>

<?php require_once __DIR__.'/main/questions.phtml' ?>
<?php require_once __DIR__.'/main/questions_not_found.phtml' ?>

<?php require_once __DIR__.'/main/hashtags.phtml' ?>
<?php require_once __DIR__.'/main/hashtags_not_found.phtml' ?>



<?php if ($this->list == 'users'): ?>

    <?php require_once __DIR__.'/main/no_users.phtml' ?>

    <?php if (count($this->users)): ?>
        <div class="card-columns">
        <?php foreach ($this->users as $user): ?>
            <div class="card">
                <a href="<?= $user->getURL($this->lang) ?>">
                    <img class="card-img-top" src="<?= $user->getAvatarLargeURL() ?>" alt="Card image cap">
                </a>
                <div class="card-body">
                    <a href="<?= $user->getURL($this->lang) ?>" class="link-inverted text-decoration-none">
                        <h4 class="h5 card-title"><?= $user->name ?></h4>
                    </a>
                    <h5 class="h6 card-subtitle mb-2 text-muted">
                        <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $user->createdAt) ?>
                    </h5>
                    <p class="card-text">Нет подписи</p>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    <?php endif; ?>

<?php endif; ?>
