
<?php require __DIR__.'/main/nav.phtml'; ?>
<?php require __DIR__.'/main/search_form.phtml'; ?>

<?php require_once __DIR__.'/main/questions.phtml' ?>
<?php require_once __DIR__.'/main/questions_not_found.phtml' ?>

<?php if ($this->list == 'hashtags'): ?>

    <?php require_once __DIR__.'/main/no_hashtags.phtml' ?>

    <?php if (isset($this->hashtags)): ?>
        <?php foreach ($this->hashtags as $hashtag): ?>
            <div class="mt-5">
                <div class="" style="display: inline-block; max-width: 78%; flex: 1;">
                    <a class="link-inverted text-decoration-none lead" href="<?= $hashtag->getURL($this->lang) ?>"><?= $hashtag->title ?></a>
                    <div>
                        <span class="text-muted">
                            X вопросов
                        </span>
                    </div>
                </div>
                <span class="text-muted float-right">
                        22 декабря 2016 <!-- $hashtag->answer->getHumanizedUpdatedAt() -->
                </span>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

<?php endif; ?>

<?php if ($this->list == 'users'): ?>

    <?php require_once __DIR__.'/main/no_users.phtml' ?>

    <?php if (count($this->users)): ?>
        <div class="card-columns">
        <?php foreach ($this->users as $user): ?>
            <div class="card">
                <a href="<?= $user->getURL($this->lang) ?>">
                    <img class="card-img-top" src="<?= $user->getAvatarLargeURL() ?>" alt="Card image cap">
                </a>
                <div class="card-body">
                    <a href="<?= $user->getURL($this->lang) ?>" class="link-inverted text-decoration-none">
                        <h4 class="h5 card-title"><?= $user->name ?></h4>
                    </a>
                    <h5 class="h6 card-subtitle mb-2 text-muted">
                        <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $user->createdAt) ?>
                    </h5>
                    <p class="card-text">Нет подписи</p>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    <?php endif; ?>

<?php endif; ?>
