<div class="mb-3 mt-3 ml-1 pl-3">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link <?= $this->list == 'questions' ? 'active' : '' ?>" href="<?= \Helper\URL\Search::get_search_questions_URL($this->lang, $this->query) ?>">
                <?= $this->translator->get('search', 'filters', 'questions'); ?>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $this->list == 'categories' ? 'active' : '' ?>" href="<?= \Helper\URL\Search::get_search_categories_URL($this->lang, $this->query) ?>">
                <?= $this->translator->get('search', 'filters', 'categories'); ?>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $this->list == 'users' ? 'active' : '' ?>" href="<?= \Helper\URL\Search::get_search_users_URL($this->lang, $this->query) ?>">
                <?= $this->translator->get('search', 'filters', 'users'); ?>
            </a>
        </li>
    </ul>
</div>