<!-- question item -->
<?php if ($this->list == 'questions' && count($this->questions)) : ?>
	<?php foreach ($this->questions as $question) : ?>

		<!-- question item -->
		<div class="border rounded bg-white p-3 my-4">

			<div class="mb-3">
				<a class="font-size-140 line-height-13 text-dark font-weight-bold text-decoration-none" href="<?= $question->getURL($this->lang) ?>">
					<?= $question->title ?>
				</a>
			</div>

			<!-- question image -->
			<?php if ($question->imageBaseName) : ?>
				<a class="d-block my-3" href="<?= $question->getURL($this->lang) ?>">
					<img class="img-fluid" src="<?= $question->getImageURLMedium($this->lang) ?>" alt="<?= $question->title ?>">
				</a>
			<?php endif; ?>
			<!-- / question image -->

			<!-- answer text -->
			<?php if (mb_strlen($question->answer->text)) : ?>
				<div class="my-3">
					<?= mb_substr($question->answer->text, 0, 150) ?><?= (mb_strlen($question->answer->text) > 150) ? '&hellip;' : '' ?>
					<?php if (mb_strlen($question->answer->text) > 150) : ?>
						<a class="text-secondary semi-small my-3" href="<?= $question->getURL($this->lang) ?>">
							(<?= __('page_main.item__top_question.read_more') ?>)
						</a>
					<?php endif; ?>
				</div>
			<?php endif; ?>
			<!-- / answer text -->

			<div class="mt-3">

				<!-- time to read -->
				<?php if (strlen($question->answer->text)) : ?>
					<span class="semi-small text-black-50">
						<i class="material-icons md-14">subject</i>
						<?= $question->getMinutesToRead() ?>&nbsp;<?= trans_choice('common.minutes_choice', $question->getMinutesToRead()); ?>
					</span>
				<?php endif; ?>
				<!-- / time to read -->

				<span class="mx-1">&middot;</span>

				<span class="semi-small text-black-50">
					<i class="material-icons md-14">edit</i>
					<?= \Humanizer\DateTime::humanizeTimestamp($this->lang, $question->answer->updatedAt) ?>
				</span>

			</div>
		</div>
		<!-- / question item -->

	<?php endforeach; ?>
<?php endif; ?>
<!-- / question item -->