<?php if ($this->list == 'questions' && count($this->questions) == 0 && strlen($this->query) > 0) : ?>
    <div class="alert alert-secondary my-4">

        <p class="font-weight-bold"><?= __('page_search.no_questions_found') ?></p>
        <p><?= str_replace('%query%', $this->query, __('page_search.no_questions_found_msg')); ?></p>

        <a class="btn btn-primary mb-2" href="<?= \Helper\URL\Questions::getNewestURL($this->lang) ?>" role="button">
            <?= __('page_search.view_all_questions') ?>
        </a>
    </div>
<?php endif; ?>