<!-- categories -->
<?php if ($this->list == 'users' && count($this->users)) : ?>
    <?php foreach ($this->users as $user) : ?>
        <div class="border rounded bg-white p-3 my-4">

            <div class="media position-relative">
                <a class="wh-48px mt-1 mr-3 rounded" href="<?= $user->getURL($this->lang) ?>">
                    <img src="<?= $user->getAvatarURLSmall() ?>" class="wh-48px rounded" alt="<?= $user->name ?>">
                </a>
                <div class="media-body">
                    <a class="mt-0 mr-2 font-weight-bold text-dark text-decoration-none" href="<?= $user->getURL($this->lang) ?>">
                        <?= $user->name ?>
                    </a>

                    <div class="semi-small text-black-50 mt-1">
                        <?php if ($user->signature) : ?>
                            <?= $user->signature ?>
                        <?php else : ?>
                            @<?= $user->username ?>
                        <?php endif; ?>

                        <?php if ($user->site) : ?>
                            <span class="font-weight-bold mx-1 text-dark">&middot;</span>
                            <a href="<?= $user->site ?>">
                                <?= parse_url($user->site, PHP_URL_HOST) ?>
                            </a>
                        <?php endif; ?>
                    </div>

                    <div class="small text-black-50 mt-2">
                        <a class="btn btn-sm btn-outline-gray mr-2" rel="nofollow" href="#">
                            Follow
                        </a>
                        <?= \Humanizer\DateTime::humanizeTimestamp($this->lang, $user->createdAt) ?>
                    </div>
                </div>
            </div>

        </div>
    <?php endforeach; ?>
<?php endif; ?>
<!-- / categories -->