<!-- question item -->
<div class="my-4">
    <div class="mb-2">
        <a class="lead text-dark text-decoration-none" href="<?= $question->get_URL($this->lang) ?>">
            <?= $question->title ?>
        </a>
    </div>

    <?php if ($question->imageBaseName) : ?>
        <a class="d-block max-width-240px" href="<?= $question->get_URL($this->lang) ?>">
            <img class="max-width-240px" src="<?= $question->get_image_URL_medium($this->lang) ?>" alt="<?= $question->title ?>">
        </a>
    <?php endif; ?>

    <div class="mt-2 text-secondary">
        <?php if ((strtotime("now") - strtotime($question->answer->updatedAt)) < (60 * 60 * 24)) : ?>
            <span class="badge badge-primary mr-3">New</span>
        <?php endif; ?>

        <?php if (strlen($question->answer->text) == 0) : ?>
            <a class="badge badge-primary mr-3" href="<?= $question->get_edit_URL($this->lang) ?>" rel="nofollow">
                <?= $this->translator->get('Write first answer') ?>
            </a>
        <?php endif; ?>

        <?php if ($question->categoriesCount == 0) : ?>
            <a class="text-success semi-small mr-3" href="<?= $question->get_update_categories_URL($this->lang) ?>" rel="nofollow">
                <i class="material-icons md-18">bubble_chart</i>
                <?= $this->translator->get('categories', 'add_categories') ?>
            </a>
        <?php endif; ?>

        <?php if (strlen($question->answer->text)) : ?>
            <i class="material-icons md-18">people_alt</i>
            <span class="semi-small">2</span>
            <span class="mx-1 text-muted font_weight_800">&middot;</span>
            <i class="material-icons md-14">access_time</i>
            <span class="semi-small" title="<?= $this->translator->get('Minutes to read') ?>">
                <?= $question->get_minutes_to_read() ?>&nbsp;<?= $this->translator->get('min') ?>
            </span>
            <span class="mx-1 text-muted font_weight_800">&middot;</span>
        <?php endif; ?>

        <span class="semi-small"><?= \Humanizer\DateTime::humanize_timestamp($this->lang, $question->answer->updatedAt) ?></span>
    </div>
</div>
<!-- / question item -->