
<!-- question item -->
<div class="my-4">
    <div class="mb-2">
        <a class="lead color-secondary-dark-4 text-decoration-none" href="<?= $question->getURL($this->lang) ?>">
            <?= $question->title ?>
        </a>
    </div>
    
    <?php if ($question->getShortAnswer()): ?>
        <div class="color-secondary-dark-2 my-2">
            <?= $question->getShortAnswer(); ?>
        </div>
    <?php endif; ?>

    <?php if ($question->imageBaseName): ?>
        <a class="d-block max-width-240px" href="<?= $question->getURL($this->lang) ?>">
            <img class="max-width-240px" src="<?= $question->getImageURLMedium($this->lang) ?>" alt="<?= $question->title ?>">
        </a>
    <?php endif; ?>

    <div class="mt-2 small color-secondary-light-1">
        <?php if ((strtotime("now") - strtotime($question->answer->updatedAt)) < (60*60*24)): ?>
            <span class="badge badge-primary mr-3">Новый</span>
        <?php endif; ?>

        <?php if (strlen($question->answer->text) == 0): ?>
            <a class="badge badge-primary mr-3" href="<?= $question->getEditURL($this->lang) ?>" rel="nofollow">
                <?= $this->translator->get('Write first answer') ?>
            </a>
        <?php endif; ?>

        <?php if ($question->categoriesCount == 0): ?>
            <a class="badge badge-success mr-3" href="<?= $question->getUpdateCategoriesURL($this->lang) ?>" rel="nofollow">
                Проставить темы
            </a>
        <?php endif; ?>

        <?php if (strlen($question->answer->text)): ?>
            2 автора
            <span class="mx-1 color-secondary-dark-2 font_weight_800">&middot;</span>
            <i class="far fa-clock"></i>
            <span title="<?= $this->translator->get('Minutes to read') ?>">
                <?= $question->getMinutesToRead() ?>&nbsp;<?= $this->translator->get('min') ?>
            </span>
            <span class="mx-1 color-secondary-dark-2 font_weight_800">&middot;</span>
        <?php endif; ?>

        <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->answer->updatedAt) ?>
    </div>
</div>
<!-- / question item -->
