
<!-- social groups -->
<div class="my-5">
    <div class="small color-gray-600">
        ОктоАнсверс в соцсетях
    </div>
    <ul class="list-inline small mt-2">
        <li class="list-inline-item">
            <a class="size-4" href="https://vk.com/octoanswers" target="_blank" rel="noopener">
                <img class="size-4" src="https://png.icons8.com/ios/32/4c75a3/vkontakte.png" alt="ВКонтакте">
            </a>
        </li>
        <li class="list-inline-item">
            <a class="size-4 mr-1" href="https://www.facebook.com/octoanswers" target="_blank" rel="noopener">
                <img class="size-4" src="https://png.icons8.com/ios/32/4267b2/facebook.png" alt="Facebook">
            </a>
        </li>
        <li class="list-inline-item">
            <a class="size-4" href="#" target="_blank" rel="noopener">
                <img class="size-4" src="https://png.icons8.com/ios/32/1da1f2/twitter.png" alt="Twitter">
            </a>
        </li>
    </ul>
</div>
<!-- / social groups -->
