
<div class="activity_item followed_H_added_Q">
    <p class="feed_item__type">
        <a href="<?= $activity['user']['profile_url'] ?>"><?= $activity['user']['name'] ?></a> <?= $activity['title'] ?>
    </p>
    <p class="question_title">
        <a href="<?= $activity['question']['url'] ?>"><?= $activity['question']['title'] ?></a>
    <p>
    <div class="feed_item__footer">
        <ul class="feed_item__actions">
            <li class="list-inline-item"><?= $activity['created_at__humanized'] ?></li>
            <li class="list-inline-item"><button class="btn btn-outline-secondary btn-sm">Ответить</button></li>
        </ul>
        <ul class="feed_item__share">
            <li class="list-inline-item"><button class="btn btn-outline-secondary btn-sm">Поделиться</button></li>
        </ul>
    </div>
</div>
