<!-- CATEGORY_ADDED_QUESTION -->
<div class="border align-middle rounded bg-white p-3 my-4">
    <div class="mb-1">
        <?php if (isset($data['category'])) : ?>

            <a class="d-inline-block wh-20px mr-1 rounded" href="<?= $data['category']['url'] ?>"><img class="wh-20px rounded" style="margin-top: -2px;" src="https://avatars.answeropedia.org/avatars/user.png?size=100&name=<?= urlencode($data['category']['title']) ?>"></a>

            <a class="font-weight-bold text-dark text-decoration-none" href="<?= $data['category']['url'] ?>">
                <?= $data['category']['title'] ?>
            </a>
        <?php elseif (isset($data['topic'])) : ?>
            <a class="font-weight-bold text-dark text-decoration-none" href="<?= $data['topic']['url'] ?>">
                <?= $data['topic']['title'] ?>
            </a>
        <?php endif; ?>

        <span class="semi-small text-black-50">&middot;</span>
        <span class="semi-small text-black-50">
            <?= __('item_activity.category_added_question') ?>
        </span>
    </div>
    <div class="mt-3 mb-1">
        <a class="font-size-140 line-height-13 text-dark font-weight-bold text-decoration-none" href="<?= $data['question']['url'] ?>">
            <?= $data['question']['title'] ?>
        </a>
    </div>
    <div class="small text-black-50">
        <?= $activity['created_at__humanized'] ?>
    </div>
</div>
<!-- / CATEGORY_ADDED_QUESTION -->