<!-- activity not_found -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block wh-2 mt-1" href="#">
            <img class="wh-2 rounded" src="https://answeropedia.org/uploads/avatar/0_100.jpg">
        </a>
    </div>
    <div class="width-full">
        <div class="text-muted">
            Undefined activity type
        </div>
        <pre class="mt-2 mb-0 alert alert-warning small"><?= $activity['activity_type'] . "\n\n" . print_r($activity, true) ?></pre>
    </div>
</div>
<!-- / activity not_found -->