
<!-- sidebar about_octo -->
<div class="box mt-4 d-none d-md-block">
    <div class="box-header">
        <a class="color-gray-800 font-weight-600 no-underline-hover" data-scroll href="#contributors_full_list">
            Что это за сайт?
        </a>
    </div>
    <div class="box-body color-gray-800 small">
        <p><?= _('Answeropedia is like Wikipedia, only for questions and answers. You ask a question and get one complete, comprehensive and competent answer from the community.') ?></p>

        <hr>

        <ul class="list-unstyled color-gray-700">
            <li class="mb-2">Смотрите, какие вопросы задают ваши друзья.</li>
            <li class="mb-2">Следите за новыми вопросами на интересующие вас темы.</li>
            <li class="mb-2">И, конечно, делитесь своими знаниями.</li>
        </ul>

        <button role="button" data-toggle="modal" data-target="#modal_signup" class="btn btn-danger btn-block mb-2">
            Стать автором
        </button>
    </div>
</div>
<!-- / sidebar about_octo -->
