
<div class="jumbotron jumbotron-fluid pt-3 <?= $this->jumbortonBgStyle ?>">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-8 ml-auto mr-auto">
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <span class="nav-link text-light pl-0"><?= _('Search'); ?></span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= $this->list == 'questions' ? 'active-yellow' : 'text-light' ?>" href="<?= $this->searchQuestionsLink ?>"><?= _('Questions'); ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= $this->list == 'hashtags' ? 'active-yellow' : 'text-light' ?>" href="<?= $this->searchHashtagsLink ?>"><?= _('Search.Filter.Hashtags'); ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= $this->list == 'users' ? 'active-yellow' : 'text-light' ?>" href="<?= $this->searchUsersLink ?>"><?= _('Users'); ?></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-sm-12 col-md-8 col-lg-8 ml-auto mr-auto text-center">
                <form action="<?= SITE_URL.'/search' ?>" method="GET">
                    <input type="hidden" name="list" value="<?= $this->list ?>">
                    <input name="q" class="form-control form-control-lg" type="text" placeholder="<?= $this->searchPlaceholder ?>" aria-label="Search" value="<?= $this->query ?>">
                </form>
            </div>
        </div>
    </div>
</div>


<?php if ($this->list == 'questions'): ?>

    <?php require_once 'block/div__no_questions.phtml' ?>

    <?php if ($this->questions && count($this->questions)): ?>
        <?php foreach ($this->questions as $question): ?>
            <div class="mt-5">
                <div class="" style="display: inline-block; max-width: 78%; flex: 1;">
                    <a class="link-inverted text-decoration-none lead" href="<?= $question->getURL($this->lang) ?>"><?= $question->getTitle() ?></a>
                    <div>
                    <?php if ($question->answer): ?>
                        <span class="text-muted">
                            <i class="fas fa-mail" style="color: #2BB462;"></i>
                            <?= 'getHumanizedMinutesToRead' ?>
                        </span>
                    <?php endif; ?>
                    </div>
                </div>
                <span class="text-muted float-right">
                    <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->answer->updatedAt) ?>
                </span>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

<?php endif; ?>

<?php if ($this->list == 'hashtags'): ?>

    <?php require_once 'block/div__no_hashtags.phtml' ?>

    <?php if (isset($this->hashtags)): ?>
        <?php foreach ($this->hashtags as $hashtag): ?>
            <div class="mt-5">
                <div class="" style="display: inline-block; max-width: 78%; flex: 1;">
                    <a class="link-inverted text-decoration-none lead" href="<?= $hashtag->getURL($this->lang) ?>"><?= $hashtag->getTitle() ?></a>
                    <div>
                        <span class="text-muted">
                            X вопросов
                        </span>
                    </div>
                </div>
                <span class="text-muted float-right">
                        22 декабря 2016 <!-- $hashtag->answer->getHumanizedUpdatedAt() -->
                </span>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

<?php endif; ?>

<?php if ($this->list == 'users'): ?>

    <?php require_once 'block/div__no_users.phtml' ?>

    <?php if (count($this->users)): ?>
        <div class="card-columns">
        <?php foreach ($this->users as $user): ?>
            <div class="card">
                <a href="<?= $user->getURL($this->lang) ?>">
                    <img class="card-img-top" src="<?= $user->getAvatarLargeURL() ?>" alt="Card image cap">
                </a>
                <div class="card-body">
                    <a href="<?= $user->getURL($this->lang) ?>" class="link-inverted text-decoration-none">
                        <h4 class="h5 card-title"><?= $user->getName() ?></h4>
                    </a>
                    <h5 class="h6 card-subtitle mb-2 text-muted">
                        <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $user->getCreatedAt()) ?>
                    </h5>
                    <p class="card-text">Нет подписи</p>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    <?php endif; ?>

<?php endif; ?>
