
<div class="my-4 pb-4 border-bottom">
    <div class="mb-3">
        <a class="h3 color-gray-900 no-underline" href="<?= $question->getURL($this->lang) ?>">
            <?= $question->getTitle() ?>
        </a>
    </div>
    <div class="color-gray-700 my-3">
        <?= mb_substr($question->getAnswer()->getText(), 0, mb_strpos($question->getAnswer()->getText(), "\n")); ?>
        <a href="<?= $question->getURL($this->lang) ?>" class="color-secondary-lightest">
            Полный ответ&hellip;
        </a>
    </div>

    <?php if ($question->getImageBaseName()): ?>
        <a class="d-block max-width-30" href="<?= $question->getURL($this->lang) ?>">
            <img class="max-width-30" src="<?= $question->getImageURLMedium($this->lang) ?>">
        </a>
    <?php endif; ?>

    <div class="mt-3 small color-gray-500">
        <?php if ((strtotime("now") - strtotime($question->getAnswer()->getUpdatedAt())) < (60*60*24)): ?>
            <span class="badge badge-sm badge-primary mr-3">Новый</span>
        <?php endif; ?>

        <?php if (count($question->getTopics()) == 0): ?>
            <a class="badge badge-sm badge-success mr-3" href="<?= $question->getUpdateTopicsURL($this->lang) ?>" rel="nofollow">
                Проставить темы
            </a>
        <?php endif; ?>

        <?php if (strlen($question->getAnswer()->getText()) == 0): ?>
            <a href="<?= $question->getEditURL($this->lang) ?>" rel="nofollow">
                <?= $this->l->t('sandbox', 'write_first_answer') ?>
            </a>
            <span class="mx-1 color-gray-700 font_weight_800">&middot;</span>
        <?php else: ?>
            2 автора
            <span class="mx-1 color-gray-700 font_weight_800">&middot;</span>
            <img class="size-20px" src="https://png.icons8.com/small/20/9E9E9E/clock.png">
            <?= $this->minutesToRead_humanizer->humanizeCharactersCount(mb_strlen($question->getAnswer()->getText())) ?>
            <span class="mx-1 color-gray-700 font_weight_800">&middot;</span>
        <?php endif; ?>

        <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->getAnswer()->getUpdatedAt()) ?>
    </div>
</div>
