<!-- flow_filter -->
<nav class="mt-2 mb-4">
    <div class="semi-small font-weight-bold text-uppercase text-primary mb-3">
        <?= __('page_flow.filters.title') ?>
    </div>

    <ul class="list-unstyled semi-small">
        <li class="my-2">
            <a class="text-dark font-weight-bold text-decoration-none" href="#">
                <?= $this->translator->get('flow', 'all_activities') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none" href="#">
                <?= $this->translator->get('flow', 'new_questions') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none" href="#">
                <?= $this->translator->get('flow', 'editing_answers') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none" href="#">
                <?= $this->translator->get('flow', 'add_to_friends') ?>
            </a>
        </li>
        <li class="my-2">
            <a class="text-dark text-decoration-none" href="#">
                <?= $this->translator->get('flow', 'new_categories') ?>
            </a>
        </li>
    </ul>
</nav>
<!-- / flow_filter -->