
<?php require TEMPLATE_PATH.'/flow/main/header.phtml'; ?>

<?php if (isset($this->activities)): ?>
    <?php foreach ($this->activities as $activity):
        switch ($activity['activity_type']) {
            case 'F_U_UPDATE_A':
            case 'F_U_FOLLOW_Q':
            case 'F_U_FOLLOW_U':
            case 'Q_RENAMED_BY_U':
            case 'U_RENAME_Q':
            case 'USER_RENAME_CATEGORY':
            case 'USER_FOLLOW_CATEGORY':
            case 'CATEGORY_ADDED_QUESTION':
            //case 'followed_U_asked_Q':
            //case 'followed_U_repost_Q':
            //case 'followed_H_got_achievement':
                $data = $activity['data'];
                require TEMPLATE_PATH.'/_common/activity/'.strtolower($activity['activity_type']).'.phtml';
                break;
            // Don`t show some activities
            case 'F_Q_UPDATE_A':
            case 'CATEGORY_RENAMED_BY_USER': // Doublicate of USER_RENAME_CATEGORY
                echo "<!-- Not show: ".$activity['activity_type']." -->";
                break;
            default:
                require TEMPLATE_PATH.'/_common/activity/not_found.phtml';
                break;
        };
    endforeach; ?>
<?php endif; ?>

<?php require_once TEMPLATE_PATH.'/flow/main/more_activities.phtml'; ?>
