<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <?php require TEMPLATE_PATH.'/flow/block/header.phtml'; ?>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8 col-xl-8">

                <?php if (isset($this->activities)): ?>
                    <?php foreach ($this->activities as $activity):
                        switch ($activity['activity_type']) {
                            // @TODO Bad
                            case 'Q_RENAMED_BY_U':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/_common/activity/f_q_renamed_by_u.phtml';
                                break;
                            // @TODO Bad
                            case 'U_RENAME_Q':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/_common/activity/f_u_rename_q.phtml';
                                break;
                            // @TODO Bad
                            case 'F_U_FOLLOW_H':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/_common/activity/f_u_follow_t.phtml';
                                break;
                            // @TODO Bad
                            case 'F_H_ADDED_Q':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/_common/activity/f_t_added_q.phtml';
                                break;
                            case 'F_U_UPDATE_A':
                            case 'F_U_FOLLOW_Q':
                            case 'F_U_FOLLOW_U':
                            //case 'followed_U_asked_Q':
                            //case 'followed_U_repost_Q':
                            //case 'followed_H_got_achievement':
                                $data = $activity['data'];
                                require TEMPLATE_PATH.'/_common/activity/'.strtolower($activity['activity_type']).'.phtml';
                                break;
                            // Don`t show some activities
                            case 'F_Q_UPDATE_A':
                                echo "<!-- Not show: ".$activity['activity_type']." -->";
                                break;
                            default:
                                require TEMPLATE_PATH.'/_common/activity/not_found.phtml';
                                break;
                        };
                    endforeach; ?>
                <?php endif; ?>

                <?php require_once TEMPLATE_PATH.'/flow/block/more_activities.phtml'; ?>

            </div>

            <div class="col-12 col-md-4 col-xl-4">
                <?php require TEMPLATE_PATH.'/flow/block/nav.phtml'; ?>
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
