
<h1 class="mb-5 text-center">
    <?= $this->l->t('flow__title') ?>
</h1>

<?php if (isset($this->activities)): ?>
    <?php foreach ($this->activities as $activity):
        switch ($activity['activity_type']) {
            case 'F_U_UPDATE_A':
            case 'F_U_FOLLOW_Q':
            case 'F_U_FOLLOW_H':
            case 'F_U_FOLLOW_U':
            case 'U_RENAME_Q':
            case 'F_H_ADDED_Q':
            //case 'followed_U_asked_Q':
            //case 'followed_U_repost_Q':
            //case 'followed_H_got_achievement':
                $data = $activity['data'];
                require TEMPLATE_PATH.'/flow/div/'.strtolower($activity['activity_type']).'.phtml';
                break;
            case 'Q_RENAMED_BY_U':
            case 'F_Q_UPDATE_A':
                echo "<!-- Not show: ".$activity['activity_type']." -->";
                break;
            default:
                require TEMPLATE_PATH.'/feed/div/activity_not_found.phtml';
                break;
        };
    endforeach; ?>
<?php endif; ?>

<?php require_once TEMPLATE_PATH.'/flow/block/more_activities.phtml'; ?>
