
<tr>
    <td style="width: 5rem !important;">
        <a class="wh-3" href="<?= $data['user']['profile_url'] ?>">
            <img class="wh-3 rounded-circle" src="<?= $data['user']['avatar_xs_url'] ?>">
        </a>
    </td>
    <td class="pb-5">
        <p class="mb-1">
            <a href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a> внес правки в ответ на вопрос <a href="<?= $data['question']['url'] ?>"><?= $data['question']['title'] ?></a>
        </p>
        <pre class="mb-1"><?= $data['revision']['diff_text'] ?></pre>
        <?php if (strlen($data['revision']['comment'])): ?>
            <p><?= $data['revision']['comment'] ?></p>
        <?php endif; ?>
        <span class="text-muted">
            <?= $activity['created_at__humanized'] ?>
        </span>
    </td>
</tr>
