
<?php if (!$this->answer->getText()): ?>
    <?php if ($this->authUser): ?>

        <!-- lure be_first_contributor -->
        <div class="d-flex box px-2 px-sm-3 py-2 py-sm-3 my-4">
            <div class="mr-3 d-none d-sm-block">
                <img class="size-4 rounded mt-1" src="https://png.icons8.com/small/32/e51e24/trophy.png" alt="<?= $this->l->t('block', 'first_answer', 'title') ?>">
            </div>
            <div class="width-full">
                <div class="color-gray-900 font-weight-600 mb-2">
                    <?= $this->l->t('block', 'first_answer', 'title') ?>
                </div>
                <div class="small color-gray-700 mb-3">
                    <?= $this->l->t('block', 'first_answer', 'lead') ?>
                </div>
                <a  class="btn btn-sm btn-outline-primary" href="<?= $this->question->getEditURL($this->lang) ?>">
                    <?= $this->l->t('block', 'first_answer', 'answer_btn') ?>
                </a>
            </div>
        </div>
        <!-- / lure be_first_contributor -->

    <?php else: ?>
        <div class="alert alert-secondary pb-4 pl-5 pr-5 mb-5 text-center">
            <div class="mt-3">
                <img class="img-size-96" alt="<?= $this->l->t('block', 'first_answer', 'title') ?>" src="https://png.icons8.com/material/96/546e7a/medal2.png">
            </div>
            <p class="h5 mt-4"><?= $this->l->t('block', 'first_answer', 'title') ?></p>
            <p class="lead"><?= $this->l->t('block', 'first_answer', 'lead') ?></p>
            <button type="button" class="btn btn-success mt-3" data-toggle="modal" data-target="#first_answer__signup">
                <img src="https://png.icons8.com/material/16/ffffff/pencil.png" class="mr-2" style="margin-top: -3px;">
                <?= $this->l->t('block', 'first_answer', 'answer_btn') ?>
            </button>
        </div>
        <?php require_once TEMPLATE_PATH.'/question/modal/first_answer__signup.phtml' ?>
    <?php endif; ?>
<?php endif; ?>
