<?php if (!$this->authUser): ?>
    <div class="my-5">
        <p class="title">
            <?= _('About OctoAnswers'); ?>
        </p>
        <p class="my-4">
            <?= _('OctoAnswers is a wiki-based site where users can ask questions, respond to them and supplement other people’s answers.'); ?>
        </p>
        <a rel="nofollow" class="btn btn-outline-secondary" href="#">
            <?= _('Signup'); ?>
        </a>
    </div>
<?php endif; ?>
