<?php if (!$this->authUser): ?>
    <div class="my-5">
        <p class="title">
            <?= _('Block - About OctoAnswers - Title'); ?>
        </p>
        <p class="my-4">
            <?= _('Block - About OctoAnswers - Message'); ?>
        </p>
        <a rel="nofollow" class="btn btn-outline-secondary" href="#">
            <?= _('Block - About OctoAnswers - Signup button'); ?>
        </a>
    </div>
<?php endif; ?>
