<!-- ask form -->
<form id="form__question_create">

    <div class="form-group">
        <textarea class="form-control" id="question_title" rows="6" placeholder="<?= __('page_ask.input_placeholder') ?>"></textarea>
    </div>

    <div class="my-4">
        <button type="submit" id="form__question_create__submit" class="btn btn-block btn-primary">
            <?= __('page_ask.btn_ask') ?>
        </button>
    </div>
</form>
<!-- / ask form -->