
<!-- question item -->
<div class="my-4 pb-4 border-bottom">
    <div class="mb-3">
        <a class="h3 color-gray-900 no-underline" href="<?= $question->getURL($this->lang) ?>">
            <?= $question->getTitle() ?>
        </a>
    </div>
    <div class="color-gray-700 my-3">
        <?= $question->getShortAnswer(); ?>
        <?php if ($question->getShortAnswer()): ?>
            <a href="<?= $question->getURL($this->lang) ?>">
                <i class="far fa-arrow-alt-circle-right"></i>
            </a>
        <?php endif; ?>
    </div>

    <?php if ($question->getImageBaseName()): ?>
        <a class="d-block size-rectangle-30x15" href="<?= $question->getURL($this->lang) ?>">
            <img class="size-rectangle-30x15" src="<?= $question->getImageURLMedium($this->lang) ?>" alt="<?= $question->getTitle() ?>">
        </a>
    <?php endif; ?>

    <div class="mt-3 small color-gray-500">
        <?php if ((strtotime("now") - strtotime($question->getAnswer()->getUpdatedAt())) < (60*60*24)): ?>
            <span class="badge badge-sm badge-primary mr-3">Новый</span>
        <?php endif; ?>

        <?php if (strlen($question->getAnswer()->getText()) == 0): ?>
            <a class="badge badge-sm badge-primary mr-3" href="<?= $question->getEditURL($this->lang) ?>" rel="nofollow">
                <?= _('Write first answer') ?>
            </a>
        <?php endif; ?>

        <?php if (count($question->getTopics()) == 0): ?>
            <a class="badge badge-sm badge-success mr-3" href="<?= $question->getUpdateTopicsURL($this->lang) ?>" rel="nofollow">
                Проставить темы
            </a>
        <?php endif; ?>

        <?php if (strlen($question->getAnswer()->getText())): ?>
            2 автора
            <span class="mx-1 color-gray-700 font_weight_800">&middot;</span>
            <i class="far fa-clock"></i>
            <?= $question->getHumanizedMinutesToRead() ?>
            <span class="mx-1 color-gray-700 font_weight_800">&middot;</span>
        <?php endif; ?>

        <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->getAnswer()->getUpdatedAt()) ?>
    </div>
</div>
<!-- / question item -->
