
<!-- question item -->
<div class="my-4 pb-4 border-bottom">
    <div class="mb-3">
        <a class="h3 color-gray-900 no-underline" href="<?= $question->getURL($this->lang) ?>">
            <?= $question->getTitle() ?>
        </a>
    </div>
    <div class="color-gray-700 my-3">
        <?= $question->getShortAnswer(); ?>
        <?php if ($question->getShortAnswer()): ?>
            <a href="<?= $question->getURL($this->lang) ?>">
                <!-- <img class="size-21px" src="https://png.icons8.com/material/21/9E9E9E/circled-right-2.png"> -->
                <img class="size-21px"  src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGmSURBVDhPxVTLTsJQFOzCB+rOj1B3Jj4Sgqh/4E+Y+Btd4pZlKX2KMe0C+AMXAitX7PwJV8JSnamDtFBKSHxMMmnPnDnn9j56jX+B53kl8AAs61lSanU4jnMJdsGx67ofKY6oN5vNC1mXIwzDHRTdT5rgfYinheetnownA7SiKNpSaT4sy9qGcaCCJ/BIqQyoo3lPvgHrlJoHjA8yuqZprklOYNv2LvKHCg3m6QM4m1ByFlwjGXqzDRlDfwZffd8/lsyZrdOvuqrkKSB2mQRzp4z8NfgOZhrDf6qmHUlf4DGBOAaHknKBfG5j1qHxqF6vb0oyjCAI9jRagzGW4grvNwv4KO93Y7w3qLEP4wQQKhTBmmLuPONCotmLNqwmrZI0JH7lS39iTcG3zJoSEDscLW1OA/nC3QfbkqaAeM4kino8f5ITLDqncRxvQOuzDrM9k5wFki0awKV/FAemD6DfkzyP9L/PL160FNjIE+bl6xf++wRvHZjvWKCi5JYCeWxmb6lgpfsVxVUUtcFRqgnJmPr0TK4KHhNMdx9fVOY55OYo9ZcwjE/Z/fs2Fpd2EgAAAABJRU5ErkJggg==">
            </a>
        <?php endif; ?>
    </div>

    <?php if ($question->getImageBaseName()): ?>
        <a class="d-block size-rectangle-30x15" href="<?= $question->getURL($this->lang) ?>">
            <img class="size-rectangle-30x15" src="<?= $question->getImageURLMedium($this->lang) ?>" alt="<?= $question->getTitle() ?>">
        </a>
    <?php endif; ?>

    <div class="mt-3 small color-gray-500">
        <?php if ((strtotime("now") - strtotime($question->getAnswer()->getUpdatedAt())) < (60*60*24)): ?>
            <span class="badge badge-sm badge-primary mr-3">Новый</span>
        <?php endif; ?>

        <?php if (strlen($question->getAnswer()->getText()) == 0): ?>
            <a class="badge badge-sm badge-primary mr-3" href="<?= $question->getEditURL($this->lang) ?>" rel="nofollow">
                <?= $this->l->t('sandbox', 'write_first_answer') ?>
            </a>
        <?php endif; ?>

        <?php if (count($question->getTopics()) == 0): ?>
            <a class="badge badge-sm badge-success mr-3" href="<?= $question->getUpdateTopicsURL($this->lang) ?>" rel="nofollow">
                Проставить темы
            </a>
        <?php endif; ?>

        <?php if (strlen($question->getAnswer()->getText())): ?>
            2 автора
            <span class="mx-1 color-gray-700 font_weight_800">&middot;</span>
            <img class="size-20px" src="https://png.icons8.com/small/20/9E9E9E/clock.png">
            <?= $this->minutesToRead_humanizer->humanizeCharactersCount(mb_strlen($question->getAnswer()->getText())) ?>
            <span class="mx-1 color-gray-700 font_weight_800">&middot;</span>
        <?php endif; ?>

        <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->getAnswer()->getUpdatedAt()) ?>
    </div>
</div>
<!-- / question item -->
