
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-2">
        </div>

        <div class="col-sm-12 col-md-9 col-lg-7 mt-5 text-center">
            <h1 class="h4 text-muted"><?= _("question_not_found", "title") ?></h1>
            <hr>
            <p class="h2"><?= $this->questionTitle ?></p>
            <p class="mt-4 mb-5">
                <a rel="nofollow" class="btn btn-primary" href="#" role="button">
                    <?= _('Ask a question') ?>
                </a>
                <a class="btn btn-outline-secondary" href="#" role="button" onclick="window.history.go(-1); return false;">
                    <?= _('Go back') ?>
                </a>
            </p>
        </div>
    </div>
</div>
