<!-- about_sandbox -->
<div class="mb-4 d-none d-lg-block">
	<div class="subtitle-1 mb-2 p-0 pl-md-2 text-secondary">
		<?= $this->translator->get('sandbox', 'about_block', 'title') ?>
	</div>

	<div class="bg-light p-0 p-md-3">

		<p class="semi-small"><?= $this->translator->get('sandbox', 'about_block', 'msg_1') ?></p>
		<p class="semi-small"><?= $this->translator->get('sandbox', 'about_block', 'msg_2') ?></p>

		<?php if (isset($this->questionsCount)) : ?>
			<p class="h1 mb-0"><?= $this->questionsCount ?></p>
			<p class="text-secondary semi-small mb-2">
				<?= $this->translator->get('sandbox', 'about_block', 'now_in_the_sandbox') ?>
			</p>
		<?php endif; ?>

		<?php if (!$this->authUser) : ?>
			<button role="button" data-toggle="modal" data-target="#modal_signup" class="btn btn-danger mt-3">
				<?= $this->translator->get('sandbox', 'about_block', 'btn_action') ?>
			</button>
		<?php endif; ?>
	</div>
</div>
<!-- / about_sandbox -->