
<!-- sandbox_nav -->

<nav class="ml-2 my-4">
	<div class="h5 color-secondary-dark-2">
        <?= $this->translator->get('Filters') ?>
	</div>
	<ul class="list-links">
		<li>
            <a href="<?= Sandbox_URL_Helper::getWithoutAnswersURL($this->lang) ?>" class="<?= ($this->list == 'without-answers') ? 'active' : '' ?>">
                <?= $this->translator->get('Questions without answers') ?>
            </a>
        </li>
        <li>
            <a href="<?= Sandbox_URL_Helper::getWithoutHashtagsURL($this->lang) ?>" class="<?= ($this->list == 'without_hashtags') ? 'active' : '' ?>">
                <?= $this->translator->get('Without hashtags') ?>
            </a>
        </li>
        <li>
            <a href="<?= Sandbox_URL_Helper::getAllURL($this->lang) ?>" class="<?= ($this->list == 'newest') ? 'active' : '' ?>">
                <?= $this->translator->get('All questions') ?>
            </a>
        </li>
	</ul>
</nav>

<!-- / sandbox_nav -->
