<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/_common/navbar.phtml'; ?>

    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-10 col-md-8">
                <?php require_once TEMPLATE_PATH.'/topic/block/header.phtml' ?>
                <?php require_once TEMPLATE_PATH.'/topic/block/actions.phtml' ?>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-8">

                <?php require_once TEMPLATE_PATH.'/topic/block/nav.phtml' ?>

                <?php if (count($this->topic_questions)): ?>
                    <?php foreach ($this->topic_questions as $question): ?>
                        <?php require TEMPLATE_PATH.'/_common/item/question_with_answer.phtml'; ?>
                    <?php endforeach; ?>
                <?php endif; ?>

                <div class="bg-color-gray-100 p-4 mb-5">
                    Есть вопрос на тему &laquo;<?= $this->topic->getTitle() ?>&raquo;?
                </div>

            </div>

            <div class="col-12 col-md-4">
                <?php require_once TEMPLATE_PATH.'/topic/block/related_topics.phtml' ?>
            </div>

        </div>
    </div>

    <?php require TEMPLATE_PATH.'/_common/js_bottom.phtml'; ?>
</body>
</html>
