<!-- categories -->
<?php if (count($this->categories)) : ?>
    <?php foreach ($this->categories as $category) : ?>
        <div class="border rounded bg-white p-3 my-4">

            <div class="media position-relative">
                <a class="wh-48px mt-1 mr-3 rounded" href="<?= $category->getURL($this->lang) ?>">
                    <img src="<?= $category->getAvatarURLSmall() ?>" class="wh-48px rounded" alt="<?= $category->title ?>">
                </a>
                <div class="media-body">
                    <a class="mt-0 mr-2 font-weight-bold text-dark text-decoration-none" href="<?= $category->getURL($this->lang) ?>">
                        <?= $category->title ?>
                    </a>

                    <div class="small text-black-50 mt-2">
                        <a class="btn btn-sm btn-outline-gray mr-2" rel="nofollow" href="#">
                            Follow
                        </a>
                        <!-- X вопросов
                        <span class="mx-1 font-weight-bold">&middot;</span>
                        X подписчиков -->
                    </div>
                </div>
            </div>

        </div>
    <?php endforeach; ?>
<?php endif; ?>
<!-- / categories -->