
<!-- how_it_works -->
<div class="border-bottom my-5 pb-4">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="mb-4">
                    <?= _('How it works?') ?>
                </h2>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-12 col-sm-4">
                <img class="size-8" src="https://png.icons8.com/small/64/3498db/ask-question.png">
                <p class="color-gray-600 mt-3">
                    <?= _('You ask a question about any topic of interest to you') ?>?
                </p>
            </div>
            <div class="col-12 col-sm-4">
                <img class="size-8" src="https://png.icons8.com/small/64/7458E1/hard-to-find.png">
                <p class="color-gray-600 mt-3">
                    <?= _('We find a specialist who can give a competent answer') ?>?
                </p>
            </div>
            <div class="col-12 col-sm-4">
                <img class="size-8" src="https://png.icons8.com/small/64/228C4C/secured-letter.png">
                <p class="color-gray-600 mt-3">
                    <?= _('You receive an answer to the email') ?>?
                </p>
            </div>
        </div>
    </div>
</div>
<!-- / how_it_works -->
