
<!-- how_it_works -->
<div class="border-bottom mb-5 pb-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-4">
                <?= _('Main - How it works - Title') ?>?
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-4">
                <p class="color-gray-600 mt-3">
                    <?= _('Main - How it works - First title') ?>?
                </p>
            </div>
            <div class="col-12 col-sm-4">
                <p class="color-gray-600 mt-3">
                    <?= _('Main - How it works - Second title') ?>?
                </p>
            </div>
            <div class="col-12 col-sm-4">
                <p class="color-gray-600 mt-3">
                    <?= _('Main - How it works - Third title') ?>?
                </p>
            </div>
        </div>
    </div>
</div>
<!-- / how_it_works -->
