
<!-- jumbotron -->
<div class="jumbotron bg-color-gray-200 border-bottom">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-10 mx-auto text-center">
                <h1 class="display-3">
                    <?= _('Main - Jumbotron - Title') ?>
                </h1>
                <p class="color-gray-600 mt-3">
                    <?= _('Main - Jumbotron - Subtitle') ?>?
                </p>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12 col-md-10 mx-auto">
                <form id="form__question_create_from_main">
                    <div class="form-group">
                        <textarea class="form-control form-control-lg" id="form__question_create_from_main__title" rows="6" placeholder="<?= _('Main - Jumbotron - Input placeholder') ?>?"></textarea>
                    </div>
                    <button type="submit" id="form__question_create_from_main__submit" class="btn btn-lg btn-block btn-primary">
                        <?= _('Main - Jumbotron - Ask button') ?>
                    </button>
                    <!-- <div class="font-weight-400 color-gray-700 mt-4">
                        или
                        <a class="link-underlined" href="https://octoanswers.com/ru/signup">присоединяйтесь</a>
                    </div> -->
                </form>
            </div>
        </div>
    </div>
</div>
<!-- / jumbotron -->
