
<ul class="nav nav-tabs mt-4">
    <li class="nav-item">
        <a class="nav-link <?= ($this->list == 'with-answers') ? 'active' : '' ?>" href="<?= Questions_URL_Helper::getNewestURL($this->lang) ?>">
            <?= _('Questions - Filter - Newest') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?= ($this->list == 'recently_updated') ? 'active' : '' ?>" href="<?= Questions_URL_Helper::getRecentlyUpdatedURL($this->lang) ?>">
            <?= _('Questions - Filter - Recently updated') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled <?= ($this->list == 'without-answers') ? 'active' : '' ?>" href="#">
            <?= _('Questions - Filter - Popular') ?>
        </a>
    </li>
</ul>
