
<?php if (isset($this->sandbox_questions) && count($this->sandbox_questions)): ?>
    <!-- questions from sandbox -->
    <div class="box mt-4 d-none d-md-block">
        <div class="box-header">
            <a class="font-weight-600 color-gray-800" href="<?= Sandbox_URL_Helper::getWithoutAnswersURL($this->lang) ?>">
                Вопросы из песочницы
            </a>
        </div>
        <div class="box-body pt-0 pb-0">
            <?php foreach ($this->sandbox_questions as $question): ?>
                <div class="my-3 small">
                    <a class="color-gray-800 no-underline-hover" href="<?= $question->getURL($this->lang) ?>">
                        <?= $question->getTitle() ?>
                    </a>
                    <div class="mt-1">
                        <?php if ((strtotime("now") - strtotime($question->getAnswer()->getUpdatedAt())) < (60*60*24)): ?>
                            <span class="badge badge-sm badge-success mr-2">Новый</span>
                        <?php endif; ?>
                        <span class="color-gray-500">
                            <?= DateTime_Humanizer::humanizeTimestamp($this->lang, $question->getAnswer()->getUpdatedAt()) ?>
                        </span>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <!-- / questions from sandbox -->
<?php endif; ?>
