
<!-- actions -->
<div class="mt-4">

    <a class="btn btn-success mr-2 mb-3" rel="nofollow" href="#">
        <i class="fas fa-plus mr-2"></i>
        Задать вопрос на эту тему
    </a>

    <?php if ($this->authUser): ?>
        <button
            class="btn follow_hashtag_button mr-2 mb-3 <?= $this->followed ? 'followed btn-success' : 'btn-primary'; ?>"
            data-hashtag-id="<?= $this->hashtag->getID() ?>"
            data-follow-title="<?= _('Follow') ?>"
            data-followed-title="<?= _('Followed') ?>"
            data-unfollow-title="<?= _('Unfollow') ?>"
            type="button">
            <i class="fas fa-bookmark mr-2"></i>
            <span>
                <?= $this->followed ? _('Followed') : _('Follow'); ?>
            </span>
        </button>
    <?php endif; ?>

    <?php if (false): ?>
        <!-- fake follow hashtag button -->
        <button type="button" class="btn btn-primary mr-2 mb-3" data-toggle="modal" data-target="#fake-follow-hashtag-modal">
            <?= _('Follow') ?>
        </button>
        <!-- fake follow hashtag modal -->
        <div class="modal fade" id="fake-follow-hashtag-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">
                            <?= _('Register or sign in and you can subscribe to this question.') ?>?
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <a href="#" data-toggle="modal" data-target="#modal_login">Log in</a> or <a href="#" data-toggle="modal" data-target="#modal_signup">signup</a> to follow this hashtag and get notifications when new questions will be added!
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= _('Cancel') ?></button>
                        <a href="#" data-toggle="modal" data-target="#modal_signup" type="button" class="btn btn-primary"><?= _('Signup') ?></a>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>

</div>
<!-- / actions -->
