
<!-- hashtag header -->
<div class="my-4">
    <div class="w-6">
        <img class="wh-6 rounded" src="https://answeropedia.org/uploads/avatar/0_200.jpg" alt="<?= $this->hashtag->getTitle() ?>">
    </div>
    <div class="ml-4">
        <p class="mb-0 color-gray-700">
            Вопросы на тему
        </p>
        <h1><?= $this->hashtag->getTitle() ?></h1>
        <div class="mb-0 color-gray-500">
            <?= count($this->hashtag_questions)+3 ?> вопросов
            <span class="mx-1 color-gray-900">&middot;</span>
            <?= count($this->hashtag_questions) ?> подписчиков
        </div>
    </div>
</div>
<!-- / hashtag header -->
