<!-- CATEGORY_ADDED_QUESTION -->
<div class="border align-middle rounded bg-white p-3 my-4">
    <div class="media position-relative">
        <i class="material-icons text-secondary wh-40px mt-1 mr-3" style="font-size: 40px;">
            bubble_chart
        </i>
        <div class="media-body">
            <div class="mb-1">
                <?php if (isset($data['category'])) : ?>
                    <a class="font-weight-bold text-dark text-decoration-none" href="<?= $data['category']['url'] ?>">
                        <?= $data['category']['title'] ?>
                    </a>
                <?php elseif (isset($data['topic'])) : ?>
                    <a class="font-weight-bold text-dark text-decoration-none" href="<?= $data['topic']['url'] ?>">
                        <?= $data['topic']['title'] ?>
                    </a>
                <?php endif; ?>


                <span class="semi-small text-black-50">&middot;</span>
                <span class="semi-small text-black-50">
                    <?= $this->translator->get('activity', 'category_added_question') ?>
                </span>
            </div>
            <div class="my-1">

                <a class="font-size-140 line-height-13 text-dark font-weight-bold text-decoration-none" href="<?= $data['question']['url'] ?>">
                    <?= $data['question']['title'] ?>
                </a>
            </div>
            <div class="small text-black-50">
                <?= $activity['created_at__humanized'] ?>
            </div>
        </div>
    </div>
</div>
<!-- / CATEGORY_ADDED_QUESTION -->