<!-- activity CATEGORY_ADDED_QUESTION -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block wh-2 mt-1" href="#">
            <img class="wh-2 rounded" src="https://answeropedia.org/uploads/avatar/0_100.jpg">
        </a>
    </div>
    <div class="width-full">
        <div class="text-muted">
            <?= $this->translator->get('category added question') ?>:

            <?php if (isset($data['category'])) : ?>
                <a class="text-dark font-weight-bold" href="<?= $data['category']['url'] ?>"><?= $data['category']['title'] ?></a>
            <?php elseif (isset($data['topic'])) : ?>
                <a class="text-dark font-weight-bold" href="<?= $data['topic']['url'] ?>"><?= $data['topic']['title'] ?></a>
            <?php endif; ?>
        </div>
        <div class="my-1">
            <a class="h3 text-dark text-decoration-none" href="<?= $data['question']['url'] ?>">
                <?= $data['question']['title'] ?>
            </a>
        </div>
        <div class="small text-secondary">
            <?= $activity['created_at__humanized'] ?>
        </div>
    </div>
</div>
<!-- / activity CATEGORY_ADDED_QUESTION -->