
<!-- activity f_q_update_a -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block size-4 mt-1" href="#">
            <img class="size-4 rounded" src="https://answeropedia.org/uploads/avatar/0_100.jpg">
        </a>
    </div>
    <div class="width-full">
        <div class="color-gray-700 mb-3">
            Внесены правки в ответ на вопрос <a class="color-gray-900 font-weight-600" href="<?= $data['question']['url'] ?>"><?= $data['question']['title'] ?></a>
        </div>
        <pre><?= $data['revision']['diff_text'] ?></pre>
        <div class="small color-gray-500">
            <a class="color-gray-700" href="<?= $data['user']['profile_url'] ?>">
                <?= $data['user']['name'] ?>
            </a>
            <?php if (strlen($data['revision']['comment'])): ?>
                <span class="mx-1 color-gray-700 font-weight-800">&middot;</span>
                <?= $data['revision']['comment'] ?>
            <?php endif; ?>
            <span class="mx-1 color-gray-700 font-weight-800">&middot;</span>
            <?= $activity['created_at__humanized'] ?>
        </div>
    </div>
</div>
<!-- / activity f_q_update_a -->
