
<!-- activity f_h_added_q -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block wh-2 mt-1" href="#">
            <img class="wh-2 rounded" src="https://answeropedia.org/uploads/avatar/0_100.jpg">
        </a>
    </div>
    <div class="width-full">
        <div class="color-gray-700">
            Задан новый вопрос на тему <a class="color-gray-900 font-weight-bold" href="<?= $data['hashtag']['url'] ?>"><?= $data['hashtag']['title'] ?></a>
        </div>
        <div class="my-1">
            <a class="h3 color-gray-900 text-decoration-none" href="<?= $data['question']['url'] ?>">
                <?= $data['question']['title'] ?>
            </a>
        </div>
        <div class="small color-gray-500">
            <?= $activity['created_at__humanized'] ?>
        </div>
    </div>
</div>
<!-- / activity f_h_added_q -->
