<!-- USER_FOLLOW_CATEGORY -->
<div class="border align-middle rounded bg-white p-3 my-4">
    <div class="media position-relative">
        <a class="wh-40px mt-1 mr-3 rounded" href="<?= $data['user']['profile_url'] ?>">
            <img src="<?= $data['user']['avatar_xs_url'] ?>" class="wh-40px rounded" alt="<?= $contributor->name ?>">
        </a>
        <div class="media-body">
            <div class="mb-1">
                <a class="font-weight-bold text-dark text-decoration-none" href="<?= $data['user']['profile_url'] ?>">
                    <?= $data['user']['name'] ?>
                </a>
                <span class="semi-small text-black-50">&middot;</span>
                <span class="semi-small text-black-50">
                    <?= $this->translator->get('activity', 'follow_user') ?>
                </span>
            </div>

            <div class="media position-relative my-2">
                <a class="wh-40px mt-1 mr-3 rounded" href="<?= $data['followed_user']['profile_url'] ?>">
                    <img src="<?= $data['followed_user']['avatar_xs_url'] ?>" class="wh-40px rounded" alt="<?= $contributor->name ?>">
                </a>
                <div class="media-body">
                    <div class="mb-1">
                        <a class="font-weight-bold text-dark text-decoration-none" href="<?= $data['followed_user']['profile_url'] ?>">
                            <?= $data['followed_user']['name'] ?>
                        </a>
                        <div>
                            <?php if (isset($data['followed_user']['signature']) && mb_strlen($data['followed_user']['signature'])) : ?>
                                <?= $data['followed_user']['signature'] ?>
                            <?php else : ?>
                                New user on Answeropedia
                            <?php endif; ?>
                        </div>
                    </div>

                </div>
            </div>

            <div class="small text-black-50">
                <?= $activity['created_at__humanized'] ?>
            </div>
        </div>
    </div>
</div>
<!-- / USER_FOLLOW_CATEGORY -->