
<!-- activity f_u_rename_q -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block wh-2 mt-1" href="<?= $data['user']['profile_url'] ?>">
            <img class="wh-2 rounded" src="<?= $data['user']['avatar_xs_url'] ?>">
        </a>
    </div>
    <div class="width-full">
        <div class="color-secondary-dark-2">
            <a class="color-secondary-dark-4 font-weight-bold" href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a>
            <?= $this->translator->get('renamed question') ?> 
            <span class="color-secondary-dark-4 font-weight-bold"><?= $data['question']['title_old'] ?></span>
        </div>
        <div class="my-1">
            <a class="h3 color-secondary-dark-4 text-decoration-none" href="<?= $data['question']['url'] ?>">
                <?= $data['question']['title_new'] ?>
            </a>
        </div>
        <div class="small color-secondary-light-1">
            <?= $activity['created_at__humanized'] ?>
        </div>
    </div>
</div>
<!-- / activity f_u_rename_q -->
