
<!-- activity f_u_update_a -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block wh-2 mt-1" href="<?= $data['user']['profile_url'] ?>">
            <img class="wh-2 rounded" src="<?= $data['user']['avatar_xs_url'] ?>">
        </a>
    </div>
    <div class="width-full">
        <div class="color-secondary-dark-2 mb-3">
            <a class="color-secondary-dark-4 font-weight-bold" href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a>
            <?= $this->translator->get('change answer') ?> 
            <a class="color-secondary-dark-4 font-weight-bold" href="<?= $data['question']['url'] ?>"><?= $data['question']['title'] ?></a>
        </div>
        <pre><?= $data['revision']['diff_text'] ?></pre>
        <div class="small color-secondary-light-1">
            <?php if (strlen($data['revision']['comment'])): ?>
                <?= $data['revision']['comment'] ?>
                <span class="mx-1 color-secondary-dark-2 font-weight-bold">&middot;</span>
            <?php endif; ?>
            <?= $activity['created_at__humanized'] ?>
        </div>
    </div>
</div>
<!-- / activity f_u_update_a -->
