
<!-- activity f_u_follow_t -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block wh-2 mt-1" href="<?= $data['user']['profile_url'] ?>">
            <img class="wh-2 rounded" src="<?= $data['user']['avatar_xs_url'] ?>">
        </a>
    </div>
    <div class="width-full">
        <div class="color-gray-700">
            <a class="color-gray-900 font-weight-bold" href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a>
            подписался на тему
            <a class="color-gray-900 font-weight-bold" href="<?= $data['hashtag']['url'] ?>">#<?= $data['hashtag']['title'] ?></a>
        </div>
        <span class="small color-gray-500">
            <?= $activity['created_at__humanized'] ?>
        </span>
    </div>
</div>
<!-- / activity f_u_follow_t -->
