
<div class="block mt-md-4 mb-md-4">
    <div class="pl-md-4 pt-md-3 pr-md-4 pb-md-2">
        <table class="table mb-0">
            <tbody>
                <tr class="mb-5">
                    <td class="p-0 w-3">
                        <a class="wh-2" href="<?= $data['user']['profile_url'] ?>">
                            <img class="wh-2 rounded-circle" src="<?= $data['user']['avatar_xs_url'] ?>">
                        </a>
                    </td>
                    <td class="p-0">
                        <p class="mb-0">
                            <a href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a>
                        </p>
                        <p class="text-muted mb-0"><small><?= $data['signature'] ?></small></p>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="border-top border-bottom pl-md-4 pr-md-4 pt-3 pb-3">
        <p class="mb-1 text-secondary">
            <?= _('activity__change_signature') ?>:
        </p>
        <p class="mb-0 lead">
            <?= $data['signature'] ?>
        </p>
    </div>
    <div class="pl-md-4 pb-md-2 pr-md-4 pt-md-2">
        <span class="text-muted"><small><?= $activity['created_at__humanized'] ?></small></span>
    </div>
</div>
