<!-- activity f_q_renamed_by_u -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block wh-2 mt-1" href="#">
            <img class="wh-2 rounded" src="https://answeropedia.org/uploads/avatar/0_100.jpg">
        </a>
    </div>
    <div class="width-full">
        <div class="text-muted">
            <?= $this->translator->get('question renamed') ?>:
            <span class="text-dark font-weight-bold"><?= $data['question']['title_old'] ?></span>
        </div>
        <div class="my-1">
            <a class="h3 text-dark text-decoration-none" href="<?= $data['question']['url'] ?>">
                <?= $data['question']['title_new'] ?>
            </a>
        </div>
        <div class="small text-secondary">
            <a class="text-muted" href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a>
            <span class="mx-1 text-muted font-weight-bold">&middot;</span>
            <?= $activity['created_at__humanized'] ?>
        </div>
    </div>
</div>
<!-- / activity f_q_renamed_by_u -->