<div class="border align-middle rounded bg-white p-3 my-4">

    <div class="media position-relative">
        <a class="wh-40px mt-1 mr-3 rounded" href="<?= $data['user']['profile_url'] ?>">
            <img src="<?= $data['user']['avatar_xs_url'] ?>" class="wh-40px rounded" alt="<?= $contributor->name ?>">
        </a>
        <div class="media-body">
            <a class="font-weight-bold text-dark text-decoration-none" href="<?= $data['user']['profile_url'] ?>">
                <?= $data['user']['name'] ?>
            </a>
            <span class="semi-small text-black-50">
                обновил подпись:
            </span>

            <p class="text-black mb-0">
                <?= $data['signature'] ?>
            </p>
        </div>
    </div>
</div>