<!-- USER_FOLLOW_CATEGORY -->
<div class="border align-middle rounded bg-white p-3 my-4">
    <div class="media position-relative">
        <a class="wh-40px mt-1 mr-3 rounded" href="<?= $data['user']['profile_url'] ?>">
            <img src="<?= $data['user']['avatar_xs_url'] ?>" class="wh-40px rounded" alt="<?= $contributor->name ?>">
        </a>
        <div class="media-body">
            <div class="mb-1">
                <a class="font-weight-bold text-dark text-decoration-none" href="<?= $data['user']['profile_url'] ?>">
                    <?= $data['user']['name'] ?>
                </a>
                <span class="semi-small text-black-50">&middot;</span>
                <span class="semi-small text-black-50">
                    <?= $this->translator->get('activity', 'follow_category') ?>
                </span>
            </div>
            <div class="my-1">
                <a class="font-size-140 line-height-13 text-dark font-weight-bold text-decoration-none" href="<?= $data['category']['url'] ?>">
                    <?= $data['category']['title'] ?>
                </a>
            </div>
            <div class="small text-black-50">
                <?= $activity['created_at__humanized'] ?>
            </div>
        </div>
    </div>
</div>
<!-- / USER_FOLLOW_CATEGORY -->