<!-- activity USER_FOLLOW_CATEGORY -->
<div class="d-flex border-bottom py-3">
    <div class="mr-3 d-none d-sm-block">
        <a class="d-block wh-2 mt-1" href="<?= $data['user']['profile_url'] ?>">
            <img class="wh-2 rounded" src="<?= $data['user']['avatar_xs_url'] ?>">
        </a>
    </div>
    <div class="width-full">
        <div class="text-muted">
            <a class="text-dark font-weight-bold" href="<?= $data['user']['profile_url'] ?>"><?= $data['user']['name'] ?></a>
            <?= $this->translator->get('follow category') ?>
            <a class="text-dark font-weight-bold" href="<?= $data['category']['url'] ?>">#<?= $data['category']['title'] ?></a>
        </div>
        <span class="small text-secondary">
            <?= $activity['created_at__humanized'] ?>
        </span>
    </div>
</div>
<!-- / activity USER_FOLLOW_CATEGORY -->