
<div class="mt-4 mb-5">
    <p class="lead text-muted mb-1"><?= _('Edit answer') ?></p>
    <h1 class="h2 mt-0">
        <a class="link-inverted text-decoration-none" href="<?= $this->question->getURL($this->lang) ?>">
            <?= $this->question->getTitle() ?>
        </a>
    </h1>
    <!-- <div class="mt-3">
        <a class="btn btn-sm btn-outline-secondary mr-2" role="button" href="<?= $this->question->getURL($this->lang) ?>">
            <?= _('Back to question') ?>
        </a>
        <a rel="nofollow" class="btn btn-outline-secondary btn-sm" target="_blank" href="<?= DDG_URL_Helper::getSearchURL($this->question->getTitle()) ?>">
            <?= _('Search in DuckDuckGo') ?>
        </a>
    </div> -->
</div>
