
<!-- topic header -->
<div class="flex-container my-4">
    <div class="width-12">
        <img class="size-12 rounded" src="https://octoanswers.com/uploads/avatar/0_200.jpg" alt="<?= $this->topic->getTitle() ?>">
    </div>
    <div class="flex-grow-4 ml-4">
        <p class="mb-0 color-gray-700">
            Вопросы на тему
        </p>
        <h1><?= $this->topic->getTitle() ?></h1>
        <div class="mb-0 color-gray-500">
            <?= count($this->topic_questions)+3 ?> вопросов
            <span class="mx-1 color-gray-900">&middot;</span>
            <?= count($this->topic_questions) ?> подписчиков
        </div>
    </div>
</div>
<!-- / topic header -->
