<!DOCTYPE html>
<html lang="<?= $this->lang ?>">
<head>
    <?php require TEMPLATE_PATH.'/common/head.phtml'; ?>
</head>
<body>
    <?php require TEMPLATE_PATH.'/common/navbar.phtml'; ?>

    <div class="container-fluid">
        <div class="row">

            <div class="col-12 col-lg-8">
                <?php require TEMPLATE_PATH.'/'.$this->template.'.phtml'; ?>
            </div>

            <?php if (file_exists(TEMPLATE_PATH.'/'.$this->template.'_sidebar.phtml')): ?>
            <div class="col-12 col-lg-4">
                <?php require TEMPLATE_PATH.'/'.$this->template.'_sidebar.phtml'; ?>
            </div>
            <?php endif; ?>

        </div>
    </div>

    <?php require_once TEMPLATE_PATH.'/common/footer.phtml'; ?>

    <?php require TEMPLATE_PATH.'/common/js_bottom.phtml'; ?>
</body>
</html>
