<!DOCTYPE html>
<html lang="<?= $this->lang ?>" <?= isset($this->htmlAttr) ? $this->htmlAttr : '' ?>>

<head>
	<?php require TEMPLATE_PATH . '/_common/head.phtml'; ?>
</head>

<body <?= isset($this->bodyAttr) ? ' ' . $this->bodyAttr : '' ?>>

	<?php require_once __DIR__ . '/_common/navbar.phtml'; ?>

	<div class="container">
		<div class="row">

			<!-- main_column -->
			<main class="col-12 col-lg-8 py-3 py-md-4">
				<?php require TEMPLATE_PATH . '/' . $this->template . '/main.phtml'; ?>
			</main>
			<!-- / main_column -->

			<!-- right_sidebar -->
			<div class="d-none d-md-block col-lg-4 py-md-3">

				<?php if (file_exists(TEMPLATE_PATH . '/' . $this->template . '/right.phtml')) : ?>
					<?php require TEMPLATE_PATH . '/' . $this->template . '/right.phtml'; ?>
				<?php endif; ?>

			</div>
			<!-- / right_sidebar -->


		</div>
	</div>

	<?php require __DIR__ . '/_common/footer.phtml'; ?>

	<?php require __DIR__ . '/_common/modals.phtml'; ?>
	<?php require __DIR__ . '/_common/js.phtml'; ?>

</body>

</html>