<!DOCTYPE html>
<html lang="<?= $this->lang ?>" <?= isset($this->htmlAttr) ? $this->htmlAttr : '' ?>>
<head>
	<?php require TEMPLATE_PATH.'/_common/head.phtml'; ?>
</head>

<body class="mdc-typography" <?= isset($this->bodyAttr) ? ' '.$this->bodyAttr : '' ?>>

	<noscript>You need to enable JavaScript to run this app.</noscript>

	<?php require TEMPLATE_PATH.'/_common/drawer_modal.phtml'; ?>
    
	<?php require TEMPLATE_PATH.'/_common/app_bar.phtml'; ?>

	<?php require TEMPLATE_PATH.'/_common/drawer_permanent.phtml'; ?>

    <div class="mdc-drawer-app-content mdc-top-app-bar--fixed-adjust">
        <main class="main-content">
            <div class="mdc-layout-grid">
                <div class="mdc-layout-grid__inner">
                    <div class="mdc-layout-grid__cell--span-8">
						
						<?php require TEMPLATE_PATH.'/'.$this->template.'/main.phtml'; ?>
                        
                    </div>
                    <div class="mdc-layout-grid__cell--span-4">
						
						<?php if (file_exists(TEMPLATE_PATH.'/'.$this->template.'/right.phtml')): ?>
							<?php require TEMPLATE_PATH.'/'.$this->template.'/right.phtml'; ?>
						<?php endif; ?>
						
						<!-- Render textfield component -->
                        <!-- <div class="mdc-text-field">
                            <input type="text" id="my-text-field" class="mdc-text-field__input">
                            <label class="mdc-floating-label" for="my-text-field">Hint text</label>
                            <div class="mdc-line-ripple"></div>
                        </div> -->

                    </div>
                </div>
            </div>

        </main>
    </div>

	<?php require TEMPLATE_PATH.'/_common/modals.phtml'; ?>
	<?php require TEMPLATE_PATH.'/_common/js.phtml'; ?>

    <div></div>
</body>

</html>
