
<div id="modal_lure__edit_answer" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal_lure__edit_answer" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <img class="img-size-96 ml-auto mr-auto mt-3" src="<?= IMAGE_URL.'/icons8/edit-file-96-color.png' ?>">
            </div>
            <div class="modal-body">
                <p><?= $this->l->t('modal__fake_edit_answer__text') ?></p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal_signup">
                    <?= $this->l->t('nav__signup') ?>
                </a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <?= $this->l->t('btn', 'close') ?>
                </button>
            </div>
        </div>
    </div>
</div>
