
<div id="modal_lure__edit_answer" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal_lure__edit_answer" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <img class="img-size-96 ml-auto mr-auto mt-3" src="https://png.icons8.com/material/96/546e7a/edit-file.png">
            </div>
            <div class="modal-body">
                <p><?= _('Question - Fake edit modal - Text') ?></p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal_signup">
                    <?= $this->l->t('nav__signup') ?>
                </a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <?= _('Button - Close') ?>
                </button>
            </div>
        </div>
    </div>
</div>
