
<div id="modal__feedback_thanks" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal__feedback_thanks" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <img class="img-size-96 ml-auto mr-auto mt-3" src="<?= IMAGE_URL.'/icons8/ok-96-color.png' ?>">
            </div>
            <div class="modal-body">
                <p><?= $this->l->t('modal__feedback_thanks__text') ?></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-block" data-dismiss="modal">
                    <?= $this->l->t('btn', 'close') ?>
                </button>
            </div>
        </div>
    </div>
</div>
