
<div id="first_answer__signup" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content text-center">
            <div class="modal-header border-0">
                <img class="img-size-96 ml-auto mr-auto" src="https://png.icons8.com/ios/96/546e7a/login-rounded-down-filled.png">
            </div>
            <div class="modal-body">
                <p><?= $this->l->t('q__first_answer__modal_text') ?></p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal_signup">
                    <?= $this->l->t('nav__signup') ?>
                </a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <?= $this->l->t('btn', 'close') ?>
                </button>
            </div>
        </div>
    </div>
</div>
