
<!-- header -->
<div class="my-4 border-bottom clearfix">

    <h1 class="h5 mt-1 mb-3 float-sm-left">Темы вопросов</h1>

    <form class="form-inline float-sm-right" action="<?= SITE_URL.'/'.$this->lang.'/search/topics' ?>" method="GET">
        <div class="form-group mb-2">
            <input name="q" class="form-control form-control-sm" type="text" placeholder="<?= _('Search topics') ?>" aria-label="Search">
        </div>
        <input type="hidden" name="list" value="topics">
    </form>

</div>
<!-- / header -->
