
<!-- nav -->
<ul class="nav nav-tabs my-4">
    <li class="nav-item">
        <a class="nav-link active" href="<?= Topics_URL_Helper::getNewestURL($this->lang) ?>">
            <?= $this->l->t('topics__filter__newest') ?>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">
            <?= $this->l->t('topics__filter__popular') ?>
        </a>
    </li>
</ul>
<!-- / nav -->
