
<?php if (count($this->topics)): ?>
    <div class="row mt-3">
        <div class="col-12 mx-auto">
            <?php foreach ($this->topics as $topic): ?>
                <div class="flex-container box p-3 my-3">
                    <div class="width-6">
                        <a class="size-6" href="<?= $topic->getURL($this->lang) ?>">
                            <img class="size-6 rounded-circle" src="http://octoanswers.com/uploads/avatar/0_100.jpg">
                        </a>
                    </div>
                    <div class="flex-grow-4 ml-3">
                        <div class="font-weight-700">
                            <a class="color-gray-900 no_underline mr-2" href="<?= $topic->getURL($this->lang) ?>">
                                <?= $topic->getTitle() ?>
                            </a>
                            <button class="btn btn-sm btn-outline-success align-middle" role="button">
                                Подписаться
                            </button>
                        </div>
                        <div class="mt-2 small color-gray-700">
                            <?= (int) (1 + strlen($topic->getTitle()) / 2) ?> вопросов
                            <span class="mx-1 color-gray-900 font_weight_800">&middot;</span>
                            <?= strlen($topic->getTitle()) ?> подписчиков
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
