<div class="mb-3 mt-4 ml-1 pl-3">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="#">
                <?= __('page_category.nav.questions') ?>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                <?= __('page_category.nav.followers') ?>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">
                <?= __('page_category.nav.related_categories') ?>
            </a>
        </li>
    </ul>
</div>